### ISSUE TITLE
A similar issue as #988.

### ISSUE THREAD

**Issue by tak1000** [tiny-dnn/tiny-dnn#1041]
I complied this simple program for a test, but I got a similar issue as #988. I would appreciate for your supports.

---c++---
#include <iostream>
#include <tiny_dnn/tiny_dnn.h>

int main(int argc, char const* argv[])
{
    return 0;
}

---My c++ environmental---
Win 10
MinGw
g++ (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Code::Blocks 17.2

----
g++.exe -Wall -fexceptions -std=c++14 -g -pthread -DDNN_USE_IMAGE_API -I..\tiny-dnn-master -c C:\Users\Tak-san\Downloads\test\main.cpp -o obj\Debug\main.o
g++.exe  -o bin\Debug\test.exe obj\Debug\main.o   

--- Error ---
||=== Build: Debug in test (compiler: GNU GCC Compiler) ===|
..\tiny-dnn-master\tiny_dnn\xtensor\xiterable.hpp||In member function 'xt::xiterable<D>::layout_iterator<L> xt::xiterable<D>::storage_begin()':|
..\tiny-dnn-master\tiny_dnn\xtensor\xiterable.hpp|740|error: expected primary-expression before ')' token|
..\tiny-dnn-master\tiny_dnn\xtensor\xiterable.hpp||In member function 'xt::xiterable<D>::layout_iterator<L> xt::xiterable<D>::storage_end()':|
..\tiny-dnn-master\tiny_dnn\xtensor\xiterable.hpp|746|error: expected primary-expression before ')' token|
..\tiny-dnn-master\tiny_dnn\xtensor\xiterable.hpp||In member function 'xt::xiterable<D>::reverse_layout_iterator<L> xt::xiterable<D>::storage_rbegin()':|
..\tiny-dnn-master\tiny_dnn\xtensor\xiterable.hpp|753|error: expected primary-expression before ')' token|
..\tiny-dnn-master\tiny_dnn\xtensor\xiterable.hpp||In member function 'xt::xiterable<D>::reverse_layout_iterator<L> xt::xiterable<D>::storage_rend()':|
..\tiny-dnn-master\tiny_dnn\xtensor\xiterable.hpp|760|error: expected primary-expression before ')' token|

**Comment by tak1000** [comment]
I don't find the answer yet, but VS2019 is able to built it.

**Comment by GiovanniCmpaner** [comment]
I got those errors on GCC 8.2.0.
I could get it to work modifying those lines, in the file `xiterable.hpp`, to:
```
740: return this->template begin<L>();
746: return this->template end<L>();
753: return this->template rbegin<L>();
760: return this->template rend<L>();
```
I believe it should have the same effect, I'm not 100% sure because of template overload resolution.
It could be using something outside the file, so I'm relying on IntelliSense.
But I'm stuck with this compiler version, will see if it works.
