### ISSUE TITLE
Train vs Fit Difference?

### ISSUE THREAD

**Issue by TrevorBlythe** [tiny-dnn/tiny-dnn#1047]
I tried code with both... legit the same output doe.

**Comment by GiovanniCmpaner** [comment]
If you see the source code of `train`, it just calls `fit` after a few checks and normalization:
https://github.com/tiny-dnn/tiny-dnn/blob/c0f576f5cb7b35893f62127cb7aec18f77a3bcc5/tiny_dnn/network.h#L305-L308

Some elaboration, according to:
https://github.com/tiny-dnn/tiny-dnn/blob/c0f576f5cb7b35893f62127cb7aec18f77a3bcc5/tiny_dnn/network.h#L258-L259
The signature of `train` is:
https://github.com/tiny-dnn/tiny-dnn/blob/c0f576f5cb7b35893f62127cb7aec18f77a3bcc5/tiny_dnn/network.h#L284-L286
And the signature of `fit` is:
https://github.com/tiny-dnn/tiny-dnn/blob/c0f576f5cb7b35893f62127cb7aec18f77a3bcc5/tiny_dnn/network.h#L368-L370
So `train` is more appropriate for label classification problems, as it takes a vector of labels in the output argument (third one).
And `fit` would be more appropriate for non-classification problems, maybe detecting an object boundary, for example.

So essentially, both achieve can achieve the same result.
