### ISSUE TITLE
RNN Dataset question

### ISSUE THREAD

**Issue by erkan612** [tiny-dnn/tiny-dnn#1053]
I'm struggling to understand the way rnn data is being prepared. I'm looking at recurrent_addition readme.md and there says "Note that since we are adding two numbers, there is no x[-1] so that y[0] = x[-1] + x[0]. Thus we start the output sequence with y[0]=x[0]." which confuses me because i don't understand. My question is; in the code there are item0 and item1 but item0 is taken by s - 1 and item1 is taken by s, what if there was an item2?

which one is correct here:
Option 1
```
int item0_start = seq_start + (s - 1) * batch_size;  // x[t]
int item1_start = seq_start + s * batch_size;        // x[t+1]
int item2_start = seq_start + (s + 1) * batch_size;        // x[t+2]
```

Option 2
```
int item0_start = seq_start + (s - 2) * batch_size;  // x[t]
int item1_start = seq_start + (s - 1) * batch_size;        // x[t+1]
int item2_start = seq_start + s * batch_size;        // x[t+2]
```

or is there any other example or documentation or anything that shows the way it works?
Also, why "output[**item1_start** + b]" ? if there was an item2, then it should be "output[`item2_start` + b]" or doesn't change?
Thanks.

**Comment by ArchieGu** [comment]
这是自动回复信息。
