### ISSUE TITLE
Build fails with internal compiler error

### ISSUE THREAD

**Issue by alexge233** [tiny-dnn/tiny-dnn#11]
./waf configure --BOOST_ROOT=/usr/include/boost
Setting top to                           : /tiny-cnn-master 
Setting out to                           : /tiny-cnn-master/build 
Checking for program g++,c++             : g++ 
Checking for program ar                  : /usr/bin/ar 
'configure' finished successfully (0.034s)

./waf build
Waf: Entering directory `/tiny-cnn-master/build'
[1/2] cxx: src/main.cpp -> build/src/main.cpp.1.o
In file included from /tiny-cnn-master/include/fully_connected_layer.h:28:0,
                 from /tiny-cnn-master/include/network.h:39,
                 from /tiny-cnn-master/include/tiny_cnn.h:31,
                 from ../src/main.cpp:31:
/tiny-cnn-master/include/layer.h: In lambda function:
/tiny-cnn-master/include/layer.h:114:32: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
Preprocessed source stored into /tmp/ccXet206.out file, please attach this to your bugreport.
Waf: Leaving directory`/tiny-cnn-master/build'
Build failed

I am using gcc-4.7.2 on Debian Wheezy amd64 and boost-1.49.0.1.
Any idea why this fails?
Seems to complain about a lambda in layer.h

**Comment by edgarriba** [comment]
@alexge233 Still having the same issue?
Notice that new version is released with lot of bug fixes.

https://github.com/nyanp/tiny-cnn/releases/tag/v0.1.0

**Comment by alexge233** [comment]
@edgarriba haven't tried it since then, will give it a go.

**Comment by Randl** [comment]
@alexge233 Did you have a chance to check it? In no, do you intend to?

**Comment by alexge233** [comment]
@Randl Hi, I never managed to get it to build so I abandoned my effort. In hindsight, gcc 4.7.2 did not have full C++1y support.

**Comment by Randl** [comment]
@alexge233 I suppose you to try with supported compiler if you're still interested. Feel free to open an issue if you find some bug or problem
