### ISSUE TITLE
Saving Caffe Converted Models 

### ISSUE THREAD

**Issue by rcmalli** [tiny-dnn/tiny-dnn#117]
Is there any way to save weights of caffe converted models and reloading them? I have tried basic ofstream way but it did not work.

`std::ofstream ofs("weights.m");
    ofs << net;`

**Comment by nyanp** [comment]
@Refikcanmalli 
Currently, tiny-cnn save only weights, and can't save network model itself. So before loading weights from istream, we should construct models manually, or reload them from caffe's prototxt.

**Comment by elife33** [comment]
You should use ofs << *net in caffe_converter.cpp's 
void test(const string& model_file,
          const string& trained_file,
          const string& mean_file,
          const string& label_file,
          const string& img_file)

**Comment by edgarriba** [comment]
@Refikcanmalli Is this solution working for you?

**Comment by zhangqianhui** [comment]
@Refikcanmalli 
Is this solution working for you?

**Comment by Randl** [comment]
@rcmalli ping

**Comment by Randl** [comment]
No answer for more than a week. Closing
