### ISSUE TITLE
word2vec example

### ISSUE THREAD

**Issue by skprasadu** [tiny-dnn/tiny-dnn#119]
Can we do a word2vec example in this framework? an example will be good.

I am looking for something like @ https://code.google.com/archive/p/word2vec/ . Can we implement this?

Thanks
Krishna

**Comment by edgarriba** [comment]
@skprasadu 
Do you have any idea which models they use in their backend in order to design your network?

**Comment by bhack** [comment]
@edgarriba https://www.tensorflow.org/versions/r0.9/tutorials/word2vec/index.html

**Comment by edgarriba** [comment]
@bhack Thanks for link ! @skprasadu Based on that, examples are welcome!

**Comment by bhack** [comment]
There are also some new advanced models released.
See https://spacy.io/blog/syntaxnet-in-context

**Comment by edgarriba** [comment]
@bhack That would be a good contribution!

**Comment by Randl** [comment]
@skprasadu Are you satisfied with answer? If you manage to implement this, PR would be appreciated.

**Comment by Randl** [comment]
No answer for more than a week. Closing
