### ISSUE TITLE
Run-time

### ISSUE THREAD

**Issue by ZHYXL** [tiny-dnn/tiny-dnn#12]
For my notebook, core i5. It takes more than several hours to run through the 1st epoch, and accuracy is very low. I didn't revise any parameters but just download and run.
What is wrong?

**Comment by davidstutz** [comment]
Did you try to use TBB or SSE? For me (on a desktop with i7 and 8GB RAM) this significantly increased performance.

**Comment by edgarriba** [comment]
@ZHYXL Still having the same issue?

**Comment by Randl** [comment]
@ZHYXL Did you check if the issue still present?

**Comment by Randl** [comment]
No answer for a week, closing
