### ISSUE TITLE
how to save vec_t in file?

### ISSUE THREAD

**Issue by GminChaconne** [tiny-dnn/tiny-dnn#120]
I use OpenCv convert images into an vec_t, then try to use ofstream save it in file, but get a long error msg.  

> ‘std::vector<std::vector<double, tiny_cnn::aligned_allocator<double, 64ul> > >’ is not derived from ‘const std::poisson_distribution<_IntType>’

How to solve it?

**Comment by pansk** [comment]
>> operator is for reading from an input stream, if you want to write to an output stream you should use operator <<.

**Comment by GminChaconne** [comment]
@pansk 
Here is my code:

> 	std::ofstream ofs("example",ios_base::out);
	if(!ofs.is_open())
	{
	cout << "fall to open file." <<endl;
	return(-1);
	}
	ofs << data1;

and when I got this when building it:

> 

> ...
> test.cpp:58:9: note:   cannot convert ‘data1’ (type ‘std::vector<std::vector<double, tiny_cnn::aligned_allocator<double, 64ul> > >’) to type ‘char’
> ...
> test.cpp:58:9: note:   cannot convert ‘data1’ (type ‘std::vector<std::vector<double, tiny_cnn::aligned_allocator<double, 64ul> > >’) to type ‘unsigned char’
> ...
> test.cpp:58:9: note:   cannot convert ‘data1’ (type ‘std::vector<std::vector<double, tiny_cnn::aligned_allocator<double, 64ul> > >’) to type ‘const char*’
> ...

**Comment by nyanp** [comment]
@GminChaconne
It seems that there is a syntax error around the declaration of data1. What type is it? Show us all of test.cpp would help.

**Comment by GminChaconne** [comment]
@nyanp 
Thanks you very much! Here is my code.
The function  'convert_image' was copy from [https://github.com/nyanp/tiny-cnn/wiki/Data-Format](url)

> /*
 g++ -std=c++11 -ggdb -Wextra -pedantic `pkg-config --cflags opencv` -o `basename test.cpp .cpp` test.cpp `pkg-config --libs opencv`  -I ./ -O3 -lpthread
*/
#include <iostream>
#include <opencv2/opencv.hpp>
#include <unistd.h>
#include <fstream>
#include <iterator>
#include <stdio.h>
#include <vector>
//#include "rs232.h"
#include "tiny_cnn/tiny_cnn.h"


using namespace std;
using namespace tiny_cnn;
using namespace tiny_cnn::activation;
using namespace cv;

// convert image to vec_t
void convert_image(const std::string& imagefilename,
                   double scale,
                   int w,
                   int h,
                   std::vector<vec_t>& data)
{
    auto img = cv::imread(imagefilename, cv::IMREAD_GRAYSCALE);
    if (img.data == nullptr) return; // cannot open, or it's not an image

    cv::Mat_<uint8_t> resized;
    cv::resize(img, resized, cv::Size(w, h));
    vec_t d;

    std::transform(resized.begin(), resized.end(), std::back_inserter(d),
                   [=](uint8_t c) { return c * scale; });
    data.push_back(d);
}


int main()
{
	std::vector<vec_t> data1;
	convert_image("./3.png", 1, 60, 60, data1);
	std::ofstream ofs("example",ios_base::out);
	if(!ofs.is_open())
	{
		cout << "fall to open file." <<endl;
		return(-1);
	}
	ofs << data1;
	
	Mat x = imread("./3.png",1);
	imshow("view",x);
	waitKey(0);
 }

**Comment by GminChaconne** [comment]
@nyanp `/*
 g++ -std=c++11 -ggdb -Wextra -pedantic `pkg-config --cflags opencv` -o `basename test.cpp .cpp` test.cpp `pkg-config --libs opencv`  -I ./ -O3 -lpthread
*/
#include <iostream>
#include <opencv2/opencv.hpp>
#include <unistd.h>
#include <fstream>
#include <iterator>
#include <stdio.h>
#include <vector>
//#include "rs232.h"
#include "tiny_cnn/tiny_cnn.h"


using namespace std;
using namespace tiny_cnn;
using namespace tiny_cnn::activation;
using namespace cv;

// convert image to vec_t
void convert_image(const std::string& imagefilename,
                   double scale,
                   int w,
                   int h,
                   std::vector<vec_t>& data)
{
    auto img = cv::imread(imagefilename, cv::IMREAD_GRAYSCALE);
    if (img.data == nullptr) return; // cannot open, or it's not an image

    cv::Mat_<uint8_t> resized;
    cv::resize(img, resized, cv::Size(w, h));
    vec_t d;

    std::transform(resized.begin(), resized.end(), std::back_inserter(d),
                   [=](uint8_t c) { return c * scale; });
    data.push_back(d);
}


int main()
{
	std::vector<vec_t> data1;
	convert_image("./3.png", 1, 60, 60, data1);
	std::ofstream ofs("example",ios_base::out);
	if(!ofs.is_open())
	{
		cout << "fall to open file." <<endl;
		return(-1);
	}
	ofs << data1;
	
	Mat x = imread("./3.png",1);
	imshow("view",x);
	waitKey(0);
 }`

**Comment by GminChaconne** [comment]
[test.txt](https://github.com/nyanp/tiny-cnn/files/202564/test.txt)
here is it;

**Comment by GminChaconne** [comment]
@nyanp 
[test.txt](https://github.com/nyanp/tiny-cnn/files/202570/test.txt)
here is it...

**Comment by nyanp** [comment]
@GminChaconne 
Ok, insert following code before ```main()``` will solve it :)
You can customize output format by modifying this funtion.

```cpp
template <typename T>
std::ostream& operator << (std::ostream& os, const vector<T>& tensor) {
    for (auto& vec : tensor) {
        for (auto& x : vec) os << x << " "; // separated by space
        os << std::endl; // new line for each vector
    }
    return os;
}
```

**Comment by pansk** [comment]
I'm sorry, apparently the response I sent from mobile didn't get through.
Indeed there's no operator << for vector<T>s in the standard library, you need to provide one yourself (like the one above).

**Comment by edgarriba** [comment]
@GminChaconne Did you solve your issue?

**Comment by Randl** [comment]
@GminChaconne Can we close the issue?

**Comment by Randl** [comment]
No answer for a week, closing
