### ISSUE TITLE
output dimension mismatch?!

### ISSUE THREAD

**Issue by GminChaconne** [tiny-dnn/tiny-dnn#124]
I'm sure that my labet_t only '0' and '1', but when I start training my network, the labet_t was changed. 't[364]=2038136191', it just impossible. Where went wrong?

`0%   10   20   30   40   50   60   70    80   90   100%
|----|----|----|----|----|----|----|----|----|----|
terminate called after throwing an instance of 'tiny_cnn::nn_error'
  what():  output dimension mismatch!
 t[364]=2038136191, dim(network output)=3
in classification task, dim(network output) must be greater than max class id.`

@nyanp @Abai @Teemperor @balintfodor @dicroce 
[train.txt](https://github.com/nyanp/tiny-cnn/files/208952/train.txt)

**Comment by GminChaconne** [comment]
[y1.txt](https://github.com/nyanp/tiny-cnn/files/208960/y1.txt)
[y0.txt](https://github.com/nyanp/tiny-cnn/files/208961/y0.txt)
each folder are only 1 kind samples, and the "y.txt" is copy from 2 file.

**Comment by edgarriba** [comment]
@GminChaconne Is this issue in last version?

**Comment by Randl** [comment]
@GminChaconne You can try the last version of tiny-dnn, which has a lot of improvements. If the issue still present, please report it.
