### ISSUE TITLE
New Version Won't compile on Visual Studio 2012

### ISSUE THREAD

**Issue by dmagee** [tiny-dnn/tiny-dnn#128]
The examples won't compile on VS2012. The errors appear all to be to do with the use of default functions in base classes, e.g.

display.h: progress_display &operator = (const progress_display &) = delete;
error C2059: sintax error ';'

activation_function.h:     function() = default;
error C2065: 'default' undeclared identifier 

plus lots of similar errors to the second in activation_function.h, layer.h, optimizer.h, display.h, 

Personally I've never seen such code, and always use {} for defaults in base classes if there is no default code (which is supported by just about every compiler I've ever seen). 

D.

**Comment by pansk** [comment]
You will need vs2013+: =default-ing and =delete-ing the constructors/assignment operators/destructors is a C++11 feature, which isn't supported by vs2012 (and it's not even fully supported by vs2013, but we created a workaround for that version).

The reason why I personally introduced those default/delete s in three PRs (#81, #83, #116), is explained in the tickets, and it is that some constructors were implicitly deleted by the presence of other items (constructors or virtual destructors).

You're correct, your solution of using empty braces for defaulting will work for parameterless constructors and for destructors, but it would be pointless. What we really needed was to default some copy/move constructor/assignments, for which you can't simply use {}, and those functions, if hand-written, need to be constantly updated, so the manual solution is error prone and hard to maintain.

A workaround can be used for deleting copy assignment operators (for classes containing references): declaring and not implementing a copy assignment operator. The main difference between this workaround and the =delete is that in the workaround the errors produced by some compilers are harder to read.

I have no strong opinion against workarounds, but I also like to remember what's in the first line of README.md: "tiny-cnn: A header only, dependency-free deep learning framework in C++11".

**Comment by nyanp** [comment]
@dmagee 
As @pansk said, we've dropped vs2012 support. I want to keep source code maintainable and simple as much as possible, but if some users have issues to migrate to the newer visual studio, we should consider to remove `default` and `delete` keywords.

**Comment by patrikhuber** [comment]
It goes the other way round too. The modern code base is one of the main reasons I am using tiny-cnn. The compiler of VS2012 is really outdated. People that can't use a modern compiler shouldn't use a library that builds on modern C++. In my opinion, tiny-cnn does not move forward fast enough, I would've even dropped support for VS2013 already.

**Comment by Randl** [comment]
As for now, VS2015 is the earliest supported version.
