### ISSUE TITLE
How can I train my own images?

### ISSUE THREAD

**Issue by zhidebushizhan** [tiny-dnn/tiny-dnn#141]
Hello,
       I saw the examlple that MNIST trained by tiny_cnn. Whether can I train my own images like .jpg or .png ? Should I change the format about them ?

**Comment by nyanp** [comment]
@zhidebushizhan 
Hi, you can convert format using opencv, or mnisten. See below:

https://github.com/nyanp/tiny-cnn/wiki/Data-Format

**Comment by edgarriba** [comment]
@zhidebushizhan Have you solved that?

**Comment by zhidebushizhan** [comment]
@edgarriba First, U should run mnisten.sln. it will create a mnisten.exe. Second, U run the mnisten.exe in cmd...............The images data you should prepare like author said before running mnisten.exe

**Comment by edgarriba** [comment]
Ok. So I that case you can close this issue :-)

**Comment by edgarriba** [comment]
thx!
