### ISSUE TITLE
Computational graph merge and gsoc

### ISSUE THREAD

**Issue by edgarriba** [tiny-dnn/tiny-dnn#153]
Hi @nyanp, 

we are starting the gsoc. /cc @bhack @mtamburrano
In the first place we would like to know when do you plan to merge the computational graph branch?

The current short/mid term goals to cover are the following (in order) :

- [x] Adapt computational-graph branch to load caffe models. *06/02/2016*
- [x] Design a backend engine API to support multiple optimizations. See https://github.com/BVLC/caffe/issues/4155
- [x] Add optimizations for CPU on x86 with [NNPACK](https://github.com/Maratyszcza/NNPACK)
- [x] Create proper CMake with package relocation
- [x] Refactor session and device API. 
- [x] Add optimizations for [libdnn](https://github.com/BVLC/caffe/blob/opencl/include/caffe/greentea/libdnn.hpp) @naibaf7
- [ ] Prepare timing benchmarks in order to be added to [convnet-benchmarks](https://github.com/soumith/convnet-benchmarks)

**Comment by nyanp** [comment]
Hi @edgarriba , /cc @bhack @mtamburrano

Great, I'm really looking forward to it!

> In the first place we would like to know when do you plan to merge the computational graph branch?

The merge will be done at the least 6/8. Maybe it is too late to wait, but you can start your work right now on computational-graph branch (My remaining tasks are caffe-converter and documents local, so we can avoid conflict). 
Rough sketch of our schedule plan until mid-term evaluation:

![schedule](https://cloud.githubusercontent.com/assets/378738/15543354/831e6b96-22cf-11e6-8714-56ab35286e6f.jpg)

How do you think about this schedule?

**Comment by bhack** [comment]
It is ok for us.

**Comment by edgarriba** [comment]
seems pretty nice to me.

Before to start with the backend API I'll finish the TODO issues in the pull request for the Caffe importer
https://github.com/nyanp/tiny-cnn/pull/154

Additionally, trying to fix some other issues in tiny
https://github.com/nyanp/tiny-cnn/pull/156

**Comment by edgarriba** [comment]
@bhack @mtamburrano
Since lasts PR, the computational-graph branch is able to load caffe models among other features. Said that, I think we're good to start with the backend API.

From my side I'll start looking at the NNPack and how to abstract tiny.

@nyanp  Are you planning any other feature before merging? Regarding the backend API, is it okay for you or do you have any suggestion?

**Comment by nyanp** [comment]
@edgarriba
There is no feature to implement before merging. I'll write a bit more tests&docs in these few days, and merge them around 6/5. If you want me to merge sooner, I'll do it :)

NNPack seems interesting, it's ok to start your work! From tiny-cnn's point of view, my requests are:

- Using NNPack ( or other backends ) must be *optional*, like the caffe-converter. "Dependency-free&header only" are strong features for tiny-cnn.
- It's excellent if we can control the trade-off between memory cunsumptions and speed: tiny-cnn and of course opencv are intended to be used in embedded systems, too.

**Comment by edgarriba** [comment]
@nyanp I think we can wait until you merge. Meanwhile, I will work in local.

@nyanp @bhack  @mtamburrano In order to design an abstraction model I was thinking in create an engine system based on current Caffe model
https://github.com/BVLC/caffe/blob/opencl/include/caffe/layer.hpp#L523

More suggestions?

**Comment by bhack** [comment]
You can take a look also at https://github.com/BVLC/caffe/issues/4187 that mention also an old device device abstraction effort never finalized in Caffe. Probably we need also to see if we want to handle [device placement in some way](https://www.tensorflow.org/versions/r0.8/how_tos/using_gpu/index.html)

**Comment by bhack** [comment]
@nyanp We need also to consider that many ops of TF are contributed upstream to [Eigen tensor](https://bitbucket.org/eigen/eigen). Eigen is template only but I don't know if or how do you want to have a relationship with this template library. This can make some sense from a strategical point of view or not.

**Comment by nyanp** [comment]
@bhack
I think tiny-cnn shouldn't depend on Eigen by *default*. If the dependency of tiny-cnn is bloated, it will be just a poor copy of TF/Caffe (it's not "tiny" at all). I want to treat it as plug-in if we need Eigen's functionalities.

**Comment by nyanp** [comment]
@edgarriba
To be honest I haven't the clear idea, but it seems that @naibaf7 's consideration in caffe#4187 makes sense to me. We can also focus on performance critical layers: conv, fully-connected and lstm.

**Comment by bhack** [comment]
Can we close this meta issue?
