### ISSUE TITLE
how to use dropout layer ? please give a example.

### ISSUE THREAD

**Issue by zhangqianhui** [tiny-dnn/tiny-dnn#155]
thanks .

**Comment by zhangqianhui** [comment]
dropout layer with the CNN layer.

**Comment by edgarriba** [comment]
@zhangqianhui Is this helping to you?
https://github.com/nyanp/tiny-cnn/blob/master/test/test_network.h#L90-L100

**Comment by bhack** [comment]
Can we close this?

**Comment by Randl** [comment]
No answer for a week, closing
