### ISSUE TITLE
mean-squared-error loss function little bug

### ISSUE THREAD

**Issue by jairodelgado** [tiny-dnn/tiny-dnn#159]
hi again,
I have found a little bug with mean-squared-error loss function. Turns out that the current result for this is the halved total squared error over all training patterns. In file loss_function.h line 36 :
`return (y - t) * (y - t) / 2;`

After in file network.h line 447 there is something like:
`for_i(out.size(), [&](int i){ e += E::f(out[i], t[i]); });`

Which is actually wrong.

**Comment by edgarriba** [comment]
@jairodelgado Thanks to point out this issue. Contributions are always welcome.

**Comment by Randl** [comment]
Fixed in https://github.com/tiny-dnn/tiny-dnn/pull/232
