### ISSUE TITLE
LibDNN integration

### ISSUE THREAD

**Issue by edgarriba** [tiny-dnn/tiny-dnn#187]
@naibaf7 @nyanp @bhack @mtamburrano
I open this ticket for LibDNN integration discussion.

@naibaf7 What's the current status of LibDNN standalone?
Recently, the initial backend architecture was merged. 
Please, give it a shot and feel free to comment about design or any consideration you think that will be convenient for LibDNN or others optimizations.  Thx !

**Comment by naibaf7** [comment]
@edgarriba 
I was mostly doing kernel experiments the last week. You can expect an initial standalone until at latest Sunday 26th.

**Comment by bhack** [comment]
A related overview of a known backend integration in TF at https://github.com/tensorflow/tensorflow/issues/2937

**Comment by bhack** [comment]
@naibaf7 What do you think about the policy in https://github.com/tensorflow/tensorflow/issues/2937#issuecomment-226878382?

**Comment by naibaf7** [comment]
@bhack 
It seems that's only because cuDNN is closed-source. I will release libDNN outside of caffe under a permissible opensource licence, allowing them to file PR's against libDNN if they can improve performance, or integrate libDNN as source code instead of using it as a library.
I'm ok with both.

**Comment by bhack** [comment]
I've commented on this Topic in that issue. If your interpretation it is correct I think that libDNN could have more margin to be integrated also in other frameworks. If the problem it is more unbalanced on API standardization I think that you can have some problem in common with libcudnn.

**Comment by naibaf7** [comment]
@bhack 
I added libDNN & my name on the TensorFlow OpenCL responsibility list. So far no one complained and/or had another suggestions. So as soon as TF OpenCL is ready, I will try to integrate libDNN there.

**Comment by bhack** [comment]
Probably cause the scope of libdnn it is more restricted than libcudnn. Also here we will the other layers/nodes CPU only if we don't get some of your GPU layers implementation from the Opencl branch.

**Comment by naibaf7** [comment]
@bhack 
Which layers are you talking about? What more do you need with the current integration?
I could give you some tips what to do about them. But feel free to use the OpenCL kernels from my Caffe branch whenever needed. Most of these kernels for auxiliary layers are very simple.

**Comment by bhack** [comment]
With you integration we will introduce Opencl in tinycnn for the first time.
Probably we can pass CL context already created in OpenCV when we will integrate back in OpenCV_contrib but we still need CL context for the standalone version.
I think that switching between CPU and Opencl nodes it is not the best solution from a performance point of view. So also with libdnn we need some other node/layers on Opencl to have a decent performance.

**Comment by bhack** [comment]
Sorry I missed to link (Opencv cl api)[http://docs.opencv.org/master/d5/d96/namespacecv_1_1ocl.html#gsc.tab=0] /cc @vpisarev @nyanp

**Comment by bhack** [comment]
@vpisarev Do you want to comment on how we want to handle the CL context in tinycnn standalone and when we will integrate in OpenCV?

**Comment by naibaf7** [comment]
@edgarriba 
In the process of getting libDNN standalone ready (currently writing CMAKE scripts): https://github.com/naibaf7/libdnn
I think the dependencies will be C++11, Boost, Threads, ViennaCL, OpenCL and CUDA. Either CUDA, OpenCL or both can be present.

**Comment by edgarriba** [comment]
nice! why is Boost needed?

**Comment by naibaf7** [comment]
@edgarriba 
The benchmark function for the autotuner relies on some boost timer. I'll check if it is replaceable with some C++11 equivalent high-precision timer though.
But the boost dependency will most likely stay due to cross-plattform filesystem capabilities which I will need for storing and loading autotuning configurations.

**Comment by bhack** [comment]
I think that with c++11 timers and http://en.cppreference.com/w/cpp/filesystem we could remove boost dependency.

**Comment by bhack** [comment]
@naibaf7 Will you remove caffe namespace at some point?

**Comment by naibaf7** [comment]
@bhack 
True. I will do that.

**Comment by edgarriba** [comment]
awesome, it could be nice to keep multi-platform support. Besides, how will the user specify the use of  OpenCL or CUDA?

**Comment by naibaf7** [comment]
@edgarriba 
The library can be compiled with support for CUDA or OpenCL enabled or disabled. Users with an nVidia chip can compile & install the version with CUDA support, otherwise just OpenCL support.
If tiny-cnn does only support OpenCL otherwise, it makes sense to disable CUDA support.
When creating a libDNN instance at runtime, a device has to be specified, and that device can either be with CUDA or OpenCL backend.

**Comment by edgarriba** [comment]
good explanation. thx! Ping us when you have a beta version

**Comment by bhack** [comment]
@naibaf7 I think also that ViennaCL could be removed in the future when [StreamExecutor](https://github.com/henline/streamexecutordoc/blob/master/README.rst) will complete its transition into LLVM.

**Comment by edgarriba** [comment]
yes, it could nice to let user specify the context

**Comment by bhack** [comment]
[LLVM integration started](http://lists.llvm.org/pipermail/llvm-dev/2016-June/101028.html) as subproject some days ago.

**Comment by naibaf7** [comment]
@bhack 
Yeah there are more elegant solutions in the future. It's flexible enough for now though, and ViennaCL is lightweight & header-only. Pure OpenCL kernel launch would also be possible though.

**Comment by bhack** [comment]
Yes was only to monitor on how Google is moving inside LLVM but it is not a short term solition.

**Comment by naibaf7** [comment]
The standalone is now available in "beta". It still lacks of documentation and is a little bit rough, but it compiles and can be used.

**Comment by edgarriba** [comment]
@naibaf7 thx for your effort! What do you think it's the best way to integrate it in tiny-cnn, as a submodule?

/cc @bhack @nyanp

**Comment by naibaf7** [comment]
@edgarriba 
I am not sure what the best way for tiny-cnn is, to be honest. What did you think of and why?

**Comment by edgarriba** [comment]
well the idea behind tiny-cnn is to not have dependencies which means no third-party source code inside the core project. An alternative to git submodule maybe could be cross-compile libdnn as a shared/static link in order to be linked to tiny-cnn among others.

**Comment by naibaf7** [comment]
@edgarriba 
Both sound good to me... the CMake files are set up to have a .so target, but submodule is also possible. Probably the bigger question is how to deal with viennacl (header-only) and opencl (shared library and headers).

**Comment by edgarriba** [comment]
you mean to call it from tiny's CMake?

**Comment by naibaf7** [comment]
@edgarriba 
Have you been able to run a test forward/backward step now, or are there still issues?
If you wait for the "simplified" interface, that will take until the 17th of July (holidays now...).

**Comment by edgarriba** [comment]
Same here. I tried to call init function in LibDNN but still nothing happens. I'm learning how to handle GPU data, and well not sure if that's the issue.

**Comment by naibaf7** [comment]
@edgarriba can you make an issue-branch with the latest experiments? I can clone that then and try to see what's wrong.

**Comment by edgarriba** [comment]
In fact, I think that the easiest way is to setup small tests in LibDNN to use it later as sample case for further integration.

**Comment by edgarriba** [comment]
I close this since LibDNN was included in a589c622f8db49cc0765127a3534421306acbcb0
