### ISSUE TITLE
Multi-inputs layers such as max-unpool, concat, element-wise operation layers.

### ISSUE THREAD

**Issue by wangyida** [tiny-dnn/tiny-dnn#201]
@bhack @nyanp @edgarriba 
## 1. Basically for tiny_cnn codes structure

I'm going to optimize max_unpooling layer with multi-input/output, the max element location index is need ed for the un-pooling layer afterwards to get a better performance in segmentation task compared to average-unpooling. Now tiny_cnn is mainly constructed based on sequence operation:

``` cpp
network<sequential>& operator << (network<sequential>& n, Layer&& l);
```

And layers are connected based on:

``` cpp
inline void connect(layerptr_t head,
                    layerptr_t tail,
                    cnn_size_t head_index = 0,
                    cnn_size_t tail_index = 0) {
    auto out_shape = head->out_shape()[head_index];
    auto in_shape = tail->in_shape()[tail_index];

    head->setup(false);

    if (out_shape.size() != in_shape.size()) {
        connection_mismatch(*head, *tail);
    }

    if (!head->next_[head_index]) {
        throw nn_error("output edge must not be null");
    }

    tail->prev_[tail_index] = head->next_[head_index];
    tail->prev_[tail_index]->add_next_node(tail);
}

inline layer& operator << (layer& lhs, layer& rhs) {
    connect(&lhs, &rhs);
    return rhs;
}
```

There are also worker storage containing important parameters such as:

``` cpp
struct max_pooling_layer_worker_specific_storage {
    /* mapping out => max_index(in) (1:1) */
    std::vector<cnn_size_t> out2inmax_;
};
```
## 2. My question with max_unpooling layer with multi-input/output

I think that concat_layer, max_unpooling_layer and arithmetic_layer must use multi-input/output, so for regular sequential network there will be 2 solution on this condition:
### Using head_index and tail_index

These implementation are here:

``` cpp
inline void connect(layerptr_t head,
                    layerptr_t tail,
                    cnn_size_t head_index = 0,
                    cnn_size_t tail_index = 0)
```
### Utilise other parameter output by particular previous layer by using the worker storage from that layer.

Here:

``` cpp
struct max_pooling_layer_worker_specific_storage {
    /* mapping out => max_index(in) (1:1) */
    std::vector<cnn_size_t> out2inmax_;
};
```

**Comment by edgarriba** [comment]
just a reminder that now tiny is a graph where `head_index` and `tail_index` are variables pointing to class edge which hold the data.

Check new graph structure:
https://github.com/nyanp/tiny-cnn/blob/feat/generic-computational-graph/tiny_cnn/nodes.h#L261

**Comment by Wangyida** [comment]
@edgarriba OK, I will do this.

**Comment by Wangyida** [comment]
@edgarriba @nyanp @bhack A remind for all: if you build tiny_cnn in tiny_cnn/build folder rather than tiny_cnn folder, when you cmake .. and make all -j4 for the first time, it might alert you with:

fatal error: 'caffe.pb.h' file not found
Solution is cmake .. and make all -j4 again. I don't know how to fix this now and it is caused by the compiled caffe.pb.h file is not put in a suitable place such as rootpath.
