### ISSUE TITLE
Use tiny-cnn to extract parameters from images

### ISSUE THREAD

**Issue by H4kor** [tiny-dnn/tiny-dnn#213]
I want to extract parameters from an image using a neural network.

**Example:**
Given an image of a brick wall the NN should extract the width and height of the bricks, the color and the roughness.
I can generate images for given parameters to train the NN and want to use it to extract the parameters from an actual image.

I've tested several CNNs but all extract very similar parameters(from generated and actual images). Do you have any advice on the construction/complexity and used functions to solve such tasks?

**Comment by Randl** [comment]
@H4kor This is general ML question and isn't connected to tiny-dnn itself. I suppose you to try other places to ask.

If you have any tinydnn-specific issues, feel free to open issue.
