### ISSUE TITLE
How can I train my color image?

### ISSUE THREAD

**Issue by xiaomingabc** [tiny-dnn/tiny-dnn#220]

**Comment by zhangqianhui** [comment]
What's meaning ?

**Comment by zhangqianhui** [comment]
https://github.com/nyanp/tiny-cnn/wiki/Data-Format

**Comment by xiaomingabc** [comment]
Thank you.I have already seen this page. they can convert the gray image into vec_t..I need to convert the color image into vec_t. But i can not understand issue#16.

**Comment by zhangqianhui** [comment]
https://github.com/zhangqianhui/CnnForAndroid/blob/master/jni/test.cpp

Hope this help you

**Comment by pi-null-mezon** [comment]
If you are familiar with Opencv you can use this code to convert color images to vec_t: https://github.com/pi-null-mezon/OpenIST/blob/master/Utils/cnnseg/cnnsegmentnet.cpp#L205

**Comment by bhack** [comment]
@nyanp Can we close this?
