### ISSUE TITLE
Speed Questions ,  dose tiny-cnn compute faster than "blas method" ?

### ISSUE THREAD

**Issue by WoooHaa** [tiny-dnn/tiny-dnn#222]
Hi, you project is reallly great. But i notice that, most NN-tools use "blas method" to speed their computing up. 
Have you ever tested the speed comparing whith "blas method" ?(like convolution/fully-connected forward computing time.)

**Comment by Randl** [comment]
@WoooHaa no, as for now we aren't measuring performance and have no solid comparison with other libs.

See following issues:
https://github.com/tiny-dnn/tiny-dnn/issues/75
https://github.com/tiny-dnn/tiny-dnn/issues/548
