### ISSUE TITLE
Automatic differentiation & co.

### ISSUE THREAD

**Issue by bhack** [tiny-dnn/tiny-dnn#223]
In the middle term what is our idea about AD in tinycnn? Seems to me that there are [some interesting initiative](http://www.met.reading.ac.uk/clouds/adept2/) for modern c++. /cc @nyanp @edgarriba @wangyida

**Comment by bhack** [comment]
As support a [gentle introduction to AD](https://justindomke.wordpress.com/2009/02/17/automatic-differentiation-the-most-criminally-underused-tool-in-the-potential-machine-learning-toolbox/)

**Comment by bhack** [comment]
Just to add another basic resource http://alexey.radul.name/ideas/2013/introduction-to-automatic-differentiation/

**Comment by Randl** [comment]
https://github.com/0xd34df00d/IAmMad

**Comment by bhack** [comment]
I add also https://github.com/joaoleal/CppADCodeGen/

**Comment by bhack** [comment]
@joaoleal Do you know any c++ deep learning proejct that has already tried to integrated with you effort?

**Comment by joaoleal** [comment]
Do not know of any. I'm currently using it for dynamic modeling based on first-principles and advanced process control.

**Comment by Randl** [comment]
Closing in favor of https://github.com/tiny-dnn/tiny-dnn/issues/539
