### ISSUE TITLE
caffe converter  module doesn't work

### ISSUE THREAD

**Issue by carlosb1** [tiny-dnn/tiny-dnn#224]
I am trying to execute the /tiny-cnn/examples/caffe_converter.cpp how it is explained in the README.md file and it get this error when I execute the example:

```
➜  build git:(0f104b1) ✗ ./test deploy.prototxt bvlc_reference_caffenet.caffemodel imagenet_mean.binaryproto synset_words.txt June_odd-eyed-cat.jpg
[ERROR] input_shape not found in caffemodel. must specify input shape explicitly
```

I tried to change the deploy.prototxt file how this commit explains:
https://github.com/BVLC/caffe/commit/2f5889cb84b8c7f8f64a6b7eb48e1dc624b18162 <- but I received the same error..

**Comment by dicroce** [comment]
I had the same issue. Perhaps it would be useful to have a caffe revision number somewhere that the converter is known to work with?

**Comment by gruenebohne** [comment]
Got the same with the [Levi & Hassner's](http://www.openu.ac.il/home/hassner/projects/cnn_agegender/) age and gender models.
