### ISSUE TITLE
Putting a LICENSE file into repo

### ISSUE THREAD

**Issue by nyanp** [tiny-dnn/tiny-dnn#228]

**Comment by edgarriba** [comment]
@nyanp @bhack What type of LICENCE do we want to hold?

**Comment by nyanp** [comment]
@edgarriba 
I want to keep the BSD 3-Clause License. This should harmonize with OpenCV.

**Comment by edgarriba** [comment]
yes, looks okay to me. So, we need to create a templated file and there will be an extra work to update all files with that, right?

/cc @bhack

**Comment by nyanp** [comment]
@edgarriba 
All headers in tiny-cnn already have [bsd-style header comments](https://github.com/nyanp/tiny-cnn/blob/master/tiny_cnn/tiny_cnn.h#L1-L26). Although we need to create a LICENSE file to conform to conventions, I wonder if we need extra works. But I'm not a professional of oss license, so I'd like some advice from professionals. /cc @bhack

**Comment by bhack** [comment]
http://www.addalicense.com
BSD it is ok for me... Apache could give a [little bit more protection on IP](http://choosealicense.com) and we have discussed some year ago for OpenCV (but we need to contact too many contributors for accepting relicensing). /cc @vrabaud @garybradski

**Comment by bhack** [comment]
We have other contributors probably in the git history.

**Comment by nyanp** [comment]
@edgarriba @bhack
How about using [keras style](https://github.com/fchollet/keras/blob/master/LICENSE#L3-L16) in LICENSE, and put a AUTHORS file like [nodejs](https://github.com/nodejs/node/blob/master/AUTHORS) to list all contributors?

**Comment by edgarriba** [comment]
yes, I think it will be the best

**Comment by patrikhuber** [comment]
If you haven't seen it that file is [auto-generated](https://github.com/nodejs/node/blob/master/tools/update-authors.sh) :-)

**Comment by nyanp** [comment]
@patrikhuber 
I didn't notice. Cool!

**Comment by edgarriba** [comment]
we need to tune this script since I noticed that some authors are repeated :)

**Comment by vrabaud** [comment]
Apache 2.0 is indeed preferred as it makes some problem (and their solutions) more explicit (like patent). And it's compatible with BSD so OpenCV is totally fine with it.

**Comment by edgarriba** [comment]
I close this since we updated LICENSE in 7542463da2dd2d590dfbd3b6f670743184f45037
