### ISSUE TITLE
Training and recognition with color image

### ISSUE THREAD

**Issue by manguyen** [tiny-dnn/tiny-dnn#237]
Hello,
I have dataset of color images in idx format and 
how can I  to train these data?

Many thanks in advance.

**Comment by H4kor** [comment]
If you have RGB-images as input the first layer needs 3 input channels.
(i.e. `net << conv<tan_h>(32, 32, 5, 3, 6)  // in:32x32x3, 5x5conv, 6fmaps` )

To my knowledge you don't have to change anything for importing the data.

**Comment by nyanp** [comment]
@manguyen 
mnist-parser doesn't support color image, but you can use opencv and [this example](https://github.com/nyanp/tiny-cnn/issues/16) to load your color images.

**Comment by Randl** [comment]
@manguyen Have you succeeded with training?

**Comment by Randl** [comment]
No answer for a week, closing
