### ISSUE TITLE
Add GitHub Pages

### ISSUE THREAD

**Issue by edgarriba** [tiny-dnn/tiny-dnn#239]
Could be nice to have public documentation.

Git Hub Pages I think it's the best solution: https://pages.github.com

**Comment by nyanp** [comment]
Another idea is [read the docs](https://readthedocs.org/) - it partially supports markdown, and has [webhook](http://read-the-docs.readthedocs.io/en/latest/webhooks.html).

**Comment by edgarriba** [comment]
oh, nice! go for it

**Comment by nyanp** [comment]
Done. http://tiny-dnn.readthedocs.io/
If we need better design, we should submit a new issue and clarify the requirement. /cc: @edgarriba
