### ISSUE TITLE
Modern C++ Memory Management With unique_ptr 

### ISSUE THREAD

**Issue by edgarriba** [tiny-dnn/tiny-dnn#250]
I was reading this post about the use unique_ptr instead of raw pointers.
http://genbattle.bitbucket.org/blog/2016/02/06/Modern-C-Memory-Management-With-unique-ptr/

We have yet some raw pointers in the low level infrastructure that can be benefited of unique_ptr
https://github.com/edgarriba/tiny-cnn/blob/master/tiny_cnn/node.h#L80

**Comment by nyanp** [comment]
Yes, I agree smart pointer is much better than raw pointer. We need to select a proper smart pointer from ```unique_ptr```, ```shared_ptr```, and ```weak_ptr```, but in tiny-dnn it is difficult to use smart pointer without breaking API changes.

```unique_ptr``` has the semantics of ownership. We can't assign multiple owner for the single object. ```node``` is already owned by ```nodes```, or outside of tiny-dnn so we can't use this for the returning type of ```node::prev_nodes```.
Besides tiny-dnn accepts local variables as its building blocks. It makes using ```shared_ptr``` and ```weak_ptr``` much harder:

```cpp
{
  // c1, p2 are automatically destructed in the end of this scope
  conv<tan_h> c1(...);
  pool<tan_h> p2(...);

  // We can't create shared_ptr & weak_ptr from an object
  // which is already constructed on the stack.
  network<sequential> net;
  net << c1 << p2;
}
```

**Comment by pansk** [comment]
Please note, smart pointers are good for defining ownership, are interesting to be sure that everything is still alive when working, but could slow down your execution heavily if used as function parameters, and in general will lock the caller to a specific memory management strategy.

See also this:
https://herbsutter.com/2013/06/05/gotw-91-solution-smart-pointer-parameters/

**Comment by bhack** [comment]
Can we close this?
