### ISSUE TITLE
Android example with NDK

### ISSUE THREAD

**Issue by carlosb1** [tiny-dnn/tiny-dnn#251]
Hello,
I am trying to use the tiny-cnn project in Android. I compiled the library and its dependencies with my ndk. Also, I created a  wrapper (with SWIG tool) from the caffe_converter example, but It doesn't work when It tries to read and load the neural network with this:
`reload_weight_from_caffe_protobinary(trained_file, net.get());`
It throws a signal error 6, it seems an allocation memory, It doesn't have enough memory to work.

In order to avoid the utilization of multiple  CPUs, I changed the flag in config.h like this:

```
#ifdef CNN_USE_OMP
#define CNN_TASK_SIZE 1
#else
#define CNN_TASK_SIZE 1
#endif
```

Also, I  uses a alexnet trained model ( 230 Mb) to test.. I don't know if someone could port the library for Android or has advices. 

P.D: this is my [project](https://github.com/carlosb1/tiny-cnn)

**Comment by zhangqianhui** [comment]
this is my project .
https://github.com/zhangqianhui/CnnForAndroid
but seems it also don't support alexnet that needs lots of memory

**Comment by edgarriba** [comment]
@carlosb1 looks interesting your wrapper!

@carlosb1  @zhangqianhui 
Could you guys collaborate to design an official Android example?

Another big thing TODO is setup some tests in ARM architectures.
Not sure if TravisCI can handle that. Any idea? /cc @nyanp

**Comment by bhack** [comment]
Probably we could cover java with a javacpp preset [like for Tensorflow](https://github.com/bytedeco/javacpp-presets/tree/master/tensorflow). /cc @saudet

**Comment by bhack** [comment]
Here you can find Android build instruction https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

**Comment by nyanp** [comment]
@edgarriba 
We can use qemu approach. https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html
It might be slow and we should probably select subset of unit tests.

**Comment by carlosb1** [comment]
I will check this link to configure tiny-cnn with travis-arm, It can be useful as a first step in the creation of integration tests.

**Comment by zhangqianhui** [comment]
very good

**Comment by bhack** [comment]
Have you already seen https://docs.travis-ci.com/user/languages/android?

**Comment by bhack** [comment]
Probably @wangyida could be interested in https://docs.travis-ci.com/user/languages/objective-c/ if he want to support an iOS demo.

**Comment by bhack** [comment]
There is the possibility that you can share some effort between android java and iOS. See google tool at http://j2objc.org/docs/Writing-Native-Methods.html

**Comment by edgarriba** [comment]
@bhack I think here there two things:
- test  general ARM architectures
- test/provide Android example

**Comment by bhack** [comment]
Yes I'm talking of the last two.
For the first I suggest https://github.com/travis-ci/travis-ci/issues/3376#issuecomment-168003756. I think that we could test arm (not IOS and Android) with ready multiarch docker images.

**Comment by edgarriba** [comment]
I think that from: https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html
we change increase `env` matrix. If we can can avoid Docker for testing in TravisCI it will be better.

**Comment by bhack** [comment]
Probably extending the matrix is good if it is not too complex to setup in .Travis. But having an Arm ready docker file could help very much developers on x86.

**Comment by Wangyida** [comment]
For general parametric model parser like caffe_converter, I am doing some implementation based on these core functions: [basic api](https://github.com/Wangyida/tiny-cnn/tree/tf/thrid_party/tensorflow) in my repo, Now they are not striped apart from TensorFlow session, so the the weights and graph in proto for forward pass in tiny-cnn must be based on [TensorFlow Session](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/public).
If these functions are striped apart from TensorFlow well, this might be a general solution for multi-platform just like these:[IOS serialize](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/ios_examples/simple/RunModelViewController.mm) and [Java serialize](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/jni/jni_utils.cc).
