### ISSUE TITLE
Fully convolutional networks using tiny-cnn?

### ISSUE THREAD

**Issue by Sthipp29** [tiny-dnn/tiny-dnn#253]
Can this header be used to design a fully convolutional neural network? I'm working on an idea to create a CNN that has 1 or 2 convolutional layers with stride > 1, no pooling layers (since the increased stride would perform downsampling) and then upsample (or deconvolve?) using a fractional stride. Can this be done using tiny-cnn? I would greatly appreciate some guidance and/or options to implement this.

**Comment by edgarriba** [comment]
@Sthipp29 
Thanks for your interest in tiny-cnn.

In regards of your question, take a look at deconvolutional layers and their examples

https://github.com/nyanp/tiny-cnn/blob/master/tiny_cnn/layers/deconvolutional_layer.h
https://github.com/nyanp/tiny-cnn/blob/master/examples/deconv/train.cpp
