### ISSUE TITLE
Segmentation fault when changing the minibatch size

### ISSUE THREAD

**Issue by keijimaeda82** [tiny-dnn/tiny-dnn#255]
for my NN model, i load the weights of 2 previously trained NN models, pass two inputs through to get the features, append the 2 vectors to get 1 feature vector (for a total of 10000 feature vectors). However, when I try to change the minibatch size from 30 to any other number, I will get segmentation fault. Additionally, when i reduce the number of feature vectors for training, I will need a different minibatch size as 30 will also give segmentation fault.

Thanks for the help

**Comment by zhangqianhui** [comment]
set the minibatch size = 1? try ?

**Comment by keijimaeda82** [comment]
it seems that for lower minibatch size it works but for higher values it will not work. Can you tell me what can be the cause of this issue? (size 1, 10, 15 works fine but 20 and above doesn't)

**Comment by edgarriba** [comment]
@keijimaeda82 Could you run with gdb or similar in Debug mode and backtrace the seg fault?

**Comment by keijimaeda82** [comment]
`Program received signal SIGSEGV, Segmentation fault.
0x0000000000458e58 in std::vector<std::vector<double, tiny_cnn::aligned_allocator<double, 64ul> >, std::allocator<std::vector<double, tiny_cnn::aligned_allocator<double, 64ul> > > > tiny_cnn::gradient<tiny_cnn::mse>(std::vector<std::vector<double, tiny_cnn::aligned_allocator<double, 64ul> >, std::allocator<std::vector<double, tiny_cnn::aligned_allocator<double, 64ul> > > > const&, std::vector<std::vector<double, tiny_cnn::aligned_allocator<double, 64ul> >, std::allocator<std::vector<double, tiny_cnn::aligned_allocator<double, 64ul> > > > const&) ()
`

that's the error I got with gdb

**Comment by edgarriba** [comment]
As you can see minibatch feature is quite new and a bit experimental. For your log it seems to be related to an allocation memory error. 

Could you describe a bit more your network architecture? Besides, how many RAM do you have? Was it working in a previous version?

**Comment by keijimaeda82** [comment]
I run the network on my Ubuntu VM with 4gb of ram. I was working with the standard MNIST for minibatch of size 30 to 50, I have not tested further. 

About the network, I have previously trained 2 networks (NN1 and NN2) and stored the weights in NN1 and NN2 weight files. The fusion network loads the weights, pass the input through the NN1 and NN2 separately to get 2 sets of features (size 50x1 each). Afterwards, I append the 2 feature vectors into 1 vector and add it to the train vector for the fusion network. This is repeated 10000 times (1000 x 10 digits). Then i feed the training vector into the network and start training for classification. Most of the structure is similar to the mnist example, with slight modification (layer sizes, depth, activator)

**Comment by nyanp** [comment]
@keijimaeda82  Thanks for your detailed report :) but it's a bit difficult to estimate what's happened... could you show me your code?

**Comment by Randl** [comment]
@keijimaeda82  Can you try the latest version and check if the bug is still present?
