### ISSUE TITLE
How to use RELU?

### ISSUE THREAD

**Issue by fslzj** [tiny-dnn/tiny-dnn#268]
In the mnist example (main.cpp), I use "relu" insted of "tan_h" in the last layer and then get low accuracy. 

`	nn << convolutional_layer<tan_h>(32, 32, 5, 1, 6) 
		<< average_pooling_layer<tan_h>(28, 28, 6, 2) 
		<< convolutional_layer<tan_h>(14, 14, 5, 6, 16,			connection_table(connection, 6, 16)) 
		<< average_pooling_layer<tan_h>(10, 10, 16, 2)
		<< convolutional_layer<tan_h>(5, 5, 5, 16, 120)
		<< fully_connected_layer<relu>(120, 10);`

**Comment by zhangqianhui** [comment]
fully_connected_layer<relu>(120, 10)  ?

**Comment by fslzj** [comment]
sorry,  <tan_h> and <relu> didn't display

**Comment by zhangqianhui** [comment]
maybe others problems

**Comment by pi-null-mezon** [comment]
Is that question an issue? What is the accuracy you need?
