### ISSUE TITLE
A bug in max_pooling_layer.h?

### ISSUE THREAD

**Issue by fslzj** [tiny-dnn/tiny-dnn#271]
the function void forward_propagation()
`for (cnn_size_t sample = 0, sample_count = in_data.size(); sample < sample_count; ++sample)` should be `for (cnn_size_t sample = 0, sample_count = in_data[0]->size(); sample < sample_count; ++sample)` ?

**Comment by Randl** [comment]
@nyanp Can be closed? Seems like this code even doesn't exist anymore
