### ISSUE TITLE
How to train CIFAR-100 dataset?

### ISSUE THREAD

**Issue by xuanzhaopeng** [tiny-dnn/tiny-dnn#274]
As CIFAR-100 have two labels for each picture, how to support 2 labels in tiny cnn?

**Comment by Tyler-D** [comment]
I guess you may have to make your own loss layer to handle it. Why don't train your model on caffe and use the weights on tiny-dnn?

**Comment by xuanzhaopeng** [comment]
@Tyler-D  U r totally correct.... at first I think I only use CPU with tiny-cnn could do this, also do not need to install other 3rd party tools for training..... but finally I have to go back to caffe... also I get very nice performance and accuracy !
