### ISSUE TITLE
Non-square size input

### ISSUE THREAD

**Issue by virtan** [tiny-dnn/tiny-dnn#282]
All the examples show the usage of tiny-dnn for square size images (width == height). In practice you often may need to deal with rectangular images. Padding rectangular images with white or black fields at the top and bottom is not a good solution since it increases computational complexity. The convolutional layer can work with rectangular kernels now (however it may make recognition worse), but the major size reducer — the pooling layers — work with square fields only.

So what's the best practice of creating network configuration for non-square input? Considering mnist example and extending it to two symbols attached horizontally (2x 28x28 or 56x28) how one can change the network configuration in the mnist example to achieve the same results?

**Comment by edgarriba** [comment]
@virtan 
check out this PR https://github.com/tiny-dnn/tiny-dnn/pull/230 :smile:

**Comment by virtan** [comment]
Thanks! But doesn't it make recognition worse when we process different number of horizontal points comparing to vertical ones for a single output? Isn't it similar to resize the image before processing in the same way breaking the aspect ratio?
