### ISSUE TITLE
Hi,if tiny-dnn supports distribute version?

### ISSUE THREAD

**Issue by haibarasiao** [tiny-dnn/tiny-dnn#299]
I download tiny-dnn and find it is really a good tool. But I want to know if it support distribute version? As I want to run it on three computer. Any suggestions?

**Comment by edgarriba** [comment]
@haibarasiao 
thanks to use tiny-dnn ! Unfortunately, it doesn't support such feature.
However, it's in the [roadmap](https://github.com/tiny-dnn/tiny-dnn/issues/286) to support multiple device.

**Comment by haibarasiao** [comment]
thanks!
