### ISSUE TITLE
when I run cifar10 with tiny-cnn in examples, I get this error:

### ISSUE THREAD

**Issue by haibarasiao** [tiny-dnn/tiny-dnn#300]
*** Error in `/home/haibara/workspace/tiny_cnn/Debug/tiny_cnn': corrupted double-linked list: 0x000000002b792500 ***

and I seems that in network.h line 687, this problem occur.

The dataset is cifar-10 dataset.
any suggestions?

**Comment by haibarasiao** [comment]
and it seems that when function 'train_onebatch'(in network.h line 674) has ended, it occurred.

**Comment by edgarriba** [comment]
@haibarasiao thanks for the feeback!
What's your batch size? Could you also provide the backtrace log you get?

**Comment by haibarasiao** [comment]
batch_size is 10(default)

Thread #1 [tiny_cnn] 28375 [core: 1] (Suspended : Signal : SIGABRT:Aborted)	
	__GI_raise() at raise.c:56 0x7ffff700dcc9	 
	__GI_abort() at abort.c:89 0x7ffff70110d8	
	__libc_message() at libc_fatal.c:175 0x7ffff704a394	
	malloc_printerr() at malloc.c:4,996 0x7ffff70550f7	
	_int_free() at malloc.c:3,996 0x7ffff70567a7	
	tiny_dnn::aligned_allocator<float, 64ul>::aligned_free() at aligned_allocator.h:133 0x49e014	
	tiny_dnn::aligned_allocator<float, 64ul>::deallocate() at aligned_allocator.h:80 0x495543	
	std::_Vector_base<float, tiny_dnn::aligned_allocator<float, 64ul> >::_M_deallocate() at stl_vector.h:174 0x48c8c4	
	std::_Vector_base<float, tiny_dnn::aligned_allocator<float, 64ul> >::~_Vector_base() at stl_vector.h:160 0x489bcb	
	std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >::~vector() at stl_vector.h:416 0x482075	
	std::_Destroy<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > >() at stl_construct.h:93 0x4a485a	
	std::_Destroy_aux<false>::__destroy<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >*>() at stl_construct.h:103 0x49c048	
	std::_Destroy<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >*>() at stl_construct.h:126 0x492d9c	
	std::_Destroy<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >*, std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > >() at stl_construct.h:151 0x48a099	
	std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > >::~vector() at stl_vector.h:415 0x482563	
	std::_Destroy<std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > > >() at stl_construct.h:93 0x4a525b	
	std::_Destroy_aux<false>::__destroy<std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > >*>() at stl_construct.h:103 0x49d184	
	std::_Destroy<std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > >*>() at stl_construct.h:126 0x494433	
	std::_Destroy<std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > >*, std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > > >() at stl_construct.h:151 0x48b4cf	
	std::vector<std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > >, std::allocator<std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > > > >::~vector() at stl_vector.h:415 0x4834c1	
	<...more frames...>

**Comment by nyanp** [comment]
memory corruption in Cifar-10 default example was solved in v1.0.0alpha
