### ISSUE TITLE
Compiling the master branch suffer some errors 

### ISSUE THREAD

**Issue by zhangqianhui** [tiny-dnn/tiny-dnn#309]
1.in vs 2013 , 
    (1) fatal error C1128: Please compile it useing "/bigobj" 
    (2)error C3861: “alignof”:  can't find the  identifier
2. in vs12 and vs14 , have the same problem:  “picotest/picotest.h”: No such file or directory

for 1 , I have solved it!

**Comment by zhangqianhui** [comment]
@nyanp @edgarriba @bhack

**Comment by zhangqianhui** [comment]
oh I fount it 
https://github.com/nyanp/picotest

**Comment by nyanp** [comment]
@zhangqianhui 
Thanks for your report, compile errors on msvc2013 are fixed.

As for picotest, you need to use ```git submodule update --init``` command to execute unit tests. see: http://stackoverflow.com/questions/10168449/git-update-submodule-recursive/10168693

**Comment by zhangqianhui** [comment]
ok!
