### ISSUE TITLE
How to reshape input_data_layer?

### ISSUE THREAD

**Issue by chendd14** [tiny-dnn/tiny-dnn#310]
I use tiny-dnn for full connected networks, but the size of the input image changes over time. How can I reshape the input data layer without re-init the whole network?

**Comment by nyanp** [comment]
@chendd14 
Hi, the simplest way in general is resizing your image as fixed size.

tiny-dnn doesn't provide image resizing function, but you can use opencv, stb_image or other 3rd party libs to resize your input. I hope [MNIST example](https://github.com/tiny-dnn/tiny-dnn/blob/master/examples/mnist/test.cpp) would help you.
