### ISSUE TITLE
Tracing the call path for MNIST example

### ISSUE THREAD

**Issue by KarthikGanesan88** [tiny-dnn/tiny-dnn#314]
Hi, I just found out about Tiny-dnn last week and it looks really neat! I was trying the MNIST example and it works fine but I am trying to find out the exact path of function calls. I am using the default network (which has a fully connected layer as the last layer in the network). 

In the "/mnist/train.cpp" file, the backend_type is set to tiny_dnn. So I went to the 'tiny_fully_connected_kernel.h" file to see if this is indeed the kernel being used. However, when i tried to put a simple cout here nothing gets printed! So i tried to print out somewhere else (the load function in nn ) and that printed just fine! So i tried modifying the calculation to see if that changed the output but that didnt change anything either! 

So am I doing something wrong here? I need to modify the layers for my experiment!

**Comment by edgarriba** [comment]
@KarthikGanesan88 
Thanks to use tiny-dnn !
Regarding your question, you are looking the wrong routine. Take a look at this one: 
https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/core/kernels/fully_connected_op_custom.h

I know it's a bit confusing right now, but since this summer we are in the middle of a massive refactoring and I hope we soon can remove old codes.

**Comment by KarthikGanesan88** [comment]
@edgarriba Hi, First off thank you for the extremely quick reply! I had to wait days for a reply sometimes on Caffe / TensorFlow. Seems like i found a 'hidden gem' with Tiny-dnn! :-) 

Seems like your suggestion worked! I was able to modify the program to try what I wanted. 

I want to try the other layers too. so should I be looking at 'conv2d_op_custom.h' for convolution layer? and will max pooling still be 'tiny_maxpool_kernel.h'? 

Thank you!

**Comment by edgarriba** [comment]
right! For 2D convolution you should check `conv2d_op_*.h` files.
For pooling the migration it's not finished yet so you might want to check old codes `tiny_maxpool_kernel.h`

It's in the agenda to migrate pooling operations. If you are interested you can take a look at conv2d and you'll see. Not difficult at all, just move codes and make sure that tests pass.

**Comment by edgarriba** [comment]
@bhack @Wangyida What do you we want to do with deconv2d and quantized ops ? We need to complete ops refactoring ASAP. I would like to start with `Tensor` class implementation.
