### ISSUE TITLE
a  problem that makes me crazy

### ISSUE THREAD

**Issue by yyfsss** [tiny-dnn/tiny-dnn#315]
when i run the tiny_cnn.sln that you give in the vc,
it always crashed and notes that
错误	2	error C2275: “T”: It is illegal to have this type used as an expression	
错误	4	error C2975: “_Align”:“std::aligned_storage”	Invalid template argument, which should be a compile time constant expressio
错误	3	error C3861: “alignof”:  Cannot find identifier

**Comment by nyanp** [comment]
@yyfsss 
If you use visual studio 2013, compile errors are fixed from b1fe7fc. Please retry at the latest version.

**Comment by zhangqianhui** [comment]
@yyfsss  Just use "__alignof" replace "alignof" . You can try! Or Please vs 2015.

**Comment by yyfsss** [comment]
@nyanp  thanks ,it works successfully in the vs 2013 version.

**Comment by nyanp** [comment]
@yyfsss 
I'm happy to hear that :) Thanks for your report!
