### ISSUE TITLE
How to get weights of the particular layer?

### ISSUE THREAD

**Issue by pi-null-mezon** [tiny-dnn/tiny-dnn#328]
Hi! I am trying to migrate on version 1.0.0 and has found that [get_weights()](http://tiny-dnn.readthedocs.io/en/latest/how_tos/How-Tos.html#get-weight-vector) is not a member of tyny_dnn::layer no more. With version 0.1.1 I have used it to save weights in Opencv FileStorage. So, how to get layers weights in v1.0.0?

**Comment by edgarriba** [comment]
@pi-null-mezon we simplified interfaces for version 1.0.0 alpha: use  `weights()` instead
https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/layers/layer.h#L183

**Comment by pi-null-mezon** [comment]
Great, thank you!

**Comment by samathasolupati** [comment]
how can we see the weights for each layer?
