### ISSUE TITLE
Where USE_SERIALIZER flag resides?

### ISSUE THREAD

**Issue by pi-null-mezon** [tiny-dnn/tiny-dnn#329]
I thought in config.h but could not find it there.

**Comment by edgarriba** [comment]
@pi-null-mezon serialization is enabled/disabled by the `CNN_NO_SERIALIZATION` macro.
You can find it in the [`config.h`.](https://github.com/tiny-dnn/tiny-dnn/blob/d232db30c1f9ae5c3a8721c3d271a15ed86d644b/tiny_dnn/config.h#L66)

However, note that it's possible to do the same via CMake: `cmake -DUSE_SERIALIZATION=OFF`
https://github.com/tiny-dnn/tiny-dnn/blob/master/CMakeLists.txt#L98

**Comment by pi-null-mezon** [comment]
Thanks, I get it. The reason I have not found it previously is that I downloaded from release but not pulled last commit. Once again thanks!
