### ISSUE TITLE
Should I explicitly call init_weight()?

### ISSUE THREAD

**Issue by pi-null-mezon** [tiny-dnn/tiny-dnn#330]
If I do not want to use built-in serialization method and prefer to use my own (for compatibility reasons), should I explicitly call init_weight() before upload weights into the network? I asked because on version 0.1.1 all works without this method call, but on modern 1.0.0 without this call my project crashes and debuger points to the "nodes.h" line297: nn_error("Layer " + l->layer_type() + " not initialized."); .

**Comment by nyanp** [comment]
@pi-null-mezon 
Hi,
It's not an intentional behavior. tiny-dnn should work without calling init_weight() explicitly. I'll check and fit it. Thanks for reporting!
