### ISSUE TITLE
Why vec_t type have 64 alignment?

### ISSUE THREAD

**Issue by pi-null-mezon** [tiny-dnn/tiny-dnn#331]
Now 'vec_t' is defined as:
````c++
typedef std::vector<float_t, aligned_allocator<float_t, 64>> vec_t;
````
but why 64-alignment is used here?

**Comment by nyanp** [comment]
@pi-null-mezon 
tiny-dnn uses SSE/AVX, and it's performance depends on the alignment (See [product.h](https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/util/product.h#L293_L298), for example).
tiny-dnn/tiny-cnn is using 64bit-aligned types from v0.1.0 to maximize SIMD performance.
