### ISSUE TITLE
Compilation errors when tiny_dnn::float_t type is defined as double

### ISSUE THREAD

**Issue by pi-null-mezon** [tiny-dnn/tiny-dnn#336]
In the last commit of the version 1.0.0 (master branch) if you define float_t as double a lot of errors occur when 'tiny_quantized_(de)conv2d_kernel.h' is compiled. It seems, that in most cases this errors are produced because type float is used when float_t should be.

**Comment by edgarriba** [comment]
@pi-null-mezon unfortunately we don't test against double type in TravisCI, so I'm not surprised that you find some errors. However, could paste the log? /cc @wangyida

**Comment by pi-null-mezon** [comment]
Issue log is too big (contains 505 strings), but most of the errors point to this:
````
C:\Programming\3rdParties\tiny-dnn-1.0.0\tiny_dnn\core\kernels\tiny_quantized_conv2d_kernel.h:49: error: C2782: 'const _Ty &std::max(const _Ty &,const _Ty &) noexcept(<expr>)': template parameter '_Ty' is ambiguous
```` 
and they happens because function std::max/min is called with arguments pair (float, double).
