### ISSUE TITLE
Use tiny-cnn in Ubuntu eclipse

### ISSUE THREAD

**Issue by meanmee** [tiny-dnn/tiny-dnn#34]
can I only use tiny-cnn package as .h files folder. Then other cpp file in the project just use include "**_.h".But i have some trouble with this idea.Almost caused by "**_ can not resolve"

**Comment by varunbezzam** [comment]
Did you try #include"../tiny-cnn/tiny_cnn/tiny_cnn.h" ? Worked for me!

**Comment by meanmee** [comment]
yes ,it worked,but get some new problems.I want to get CNN's Weight,But there sems like is no function to get the W

**Comment by edgarriba** [comment]
@meanmee Please, check the tutorials.
https://github.com/nyanp/tiny-cnn/blob/master/doc/How-Tos.md#visualize-the-model

**Comment by Randl** [comment]
@meanmee Can we close the issue?

**Comment by Randl** [comment]
No answer for a week, closing
