### ISSUE TITLE
hyperbolic tangent activation function issue

### ISSUE THREAD

**Issue by jairodelgado** [tiny-dnn/tiny-dnn#347]
Hello!
I have been checking the current hypervolic tangent activation function and for high activation values (specially after max_pooling layers) the std::exp function will throw a result towards infinity and the resulting activation will be of course nan. I would recomend using std::tanh function instead wrapping arround std::exp. However, for practictioners, they would need to pay attention to network paralylisis issues.

**Comment by nyanp** [comment]
@jairodelgado 
Hi, thanks for pointing out! You're right and it's always better to use ```std::tanh``` instead of current implementation. I'll fix it..
