### ISSUE TITLE
How should I create the dataset files?

### ISSUE THREAD

**Issue by anubhavrohatgi** [tiny-dnn/tiny-dnn#35]
I have images of faces. Images are of 64x64 dimensions. I used MNISTEN to build the file training and test both. Now when I pass this file to the convnet I get an exception:

throw nn_error("input dimension mismatch");

nn << convolutional_layer<tan_h>(64, 64, 7, 1, 6) 
        << average_pooling_layer<tan_h>(58, 58, 6, 2) 
        << convolutional_layer<tan_h>(29, 29, 8, 6, 16, connection_table(connection, 6, 16)) 
        << average_pooling_layer<tan_h>(22, 22, 16, 2) //S4
        << convolutional_layer<tan_h>(11, 11, 11, 16, 180) //C5
        << fully_connected_layer<tan_h>(180, 15);//F6

I am referring to this paper. 

http://dap.vsb.cz/wsc17conf/Media/Default/Page/online_wsc17_submission_59.pdf

Kindly suggest and point out where I could be wrong.

My dataset is perfect, all the images are of 64x64.

Also I tried using 32x32 images on Le net version here .

Please provide a solution. What could be possibly wrong.

**Comment by meanmee** [comment]
I also face a problem likely, I save the lenet model like this :	
     std::ofstream ofs("LeNet-weights");
     ofs << nn;
And then open the file ,using it to predict:
     std::ifstream ifs("LeNet-weights");
     ifs>>nn;
And All the case it throw "input dimension mismatch"

**Comment by anubhavrohatgi** [comment]
Hey I understood how to create the database.

Well here it is -

First You have to know what is the input filter size if it is 5x5 , 7x7 and so on. Also you have to know what is the input size to the CNN..

No say your input size is 32x32 and filter u are using is 5x5 then 

using this formula 2n+1= filter(x)
so n = 2 here right

so what I mean is that you size of the image before it goes to the mnist parser should be ::
X + 2(n) = 32
X  + 2(2) = 32
X = 28

so the input image should be 28x28 size.

**Comment by bezita** [comment]
i try to create dataset of cifar-10 , the images' size is 32x32,so i changed the filter as below:

nn << convolutional_layer<tan_h>(36, 36, 5, 1, 6)
		<< average_pooling_layer<tan_h>(32, 32, 6, 2) 
		<< convolutional_layer<tan_h>(16, 16, 5, 6, 16,connection_table(connection, 6, 16))
		<< average_pooling_layer<tan_h>(12, 12, 16, 2)
		<< convolutional_layer<tan_h>(6, 6, 5, 16, 144)
		<< fully_connected_layer<tan_h>(144, 10);

 it always throwed "input dimension mismatch" :(

**Comment by nyanp** [comment]
@bezita 
parse_mnist_images function has "x_padding" and "y_padding" parameters (default is 2). it is why parsed data size is larger than database's original size.
parse_cifar10 function hasn't these parameters, so "implicit padding" doesn't occur in cifar-10 format. If your image size is 32x32grayscale, your network should be

```cpp
nn << convolutional_layer(32, 32, 5, 1, 6)
     << ...
```

or, if your image size is 32x32rgb color, your network should be

```cpp
nn << convolutional_layer(32, 32, 5, 3, 6)   // require 3channels (r,g,b)
     << ...
```

Implicit padding and difference between mnist/cifar-10 is very confusing, so it should be improved...

**Comment by anubhavrohatgi** [comment]
yea there are a few glitches, but nothing can beat this library. I guess in the course of time the authors will improve it further..

**Comment by anubhavrohatgi** [comment]
I was wondering, like how can I start designing a neural net for face recognition. I tried several papers but most of them are restricted to a standard dataset. What if I have my own sort of dataset abiding by a law/structure like say all pics faces only and say 128x128 size. So how should I go about laying out the structure of the neural net.

**Comment by nyanp** [comment]
@anubhavrohatgi 
I don't understand about your dataset format, but traditional deep convolutional nets works well only when data has spatially local correlation (i.e. images, voice)...
And I've just updated tiny-cnn's parser (add comments, remove default params, and fix interface differences between mnist/cifar) :)

**Comment by anubhavrohatgi** [comment]
Let us say I am using ORL dataset for faces.

**Comment by anubhavrohatgi** [comment]
I use the mnisten to make a dataset of the ORL faces. in Grayscale. 

There are 27 classes s0 to s26. By classes I mean subject. I use dlib to detect align and rescale the images.

**Comment by edgarriba** [comment]
@anubhavrohatgi Solved that?

**Comment by Randl** [comment]
@anubhavrohatgi How is your experience with tiny-dnn? Have you achieved desired result? Do you still have any issues?

**Comment by Randl** [comment]
No reply, closing
