### ISSUE TITLE
Survelliance system with person detector

### ISSUE THREAD

**Issue by PiSimo** [tiny-dnn/tiny-dnn#351]
<b>Hi</b> !
I'm working on a survelliance system on my raspberry pi .The system is motion based , so every time something changes I get the rect of the image where the motion was detected. The camera is outdoor so every day there are a lot of vain alerts like cats,shadows and so on. So to fix that I've used a feature based neural network with opencv with positive and negative examples but the results aren't so good, so i decided to switch to tiny_dnn any advices to solve that ? I've tryed to train a CNN but i always get bad results !

**Comment by bhack** [comment]
Join the chat: https://gitter.im/tiny-dnn/users

**Comment by bhack** [comment]
Can we close this? There was a quite compatible support request at http://stackoverflow.com/questions/40367232/error-with-tiny-dnn-for-pedestrian-recognition
