### ISSUE TITLE
mnisten error

### ISSUE THREAD

**Issue by yyfsss** [tiny-dnn/tiny-dnn#371]
When i use mnisten master to convert my image. It always shows that  no images. It seems that it cant recognition my own images. When i use opencv to convert my color to the vec_t. Caffe also says no images and drop out of the vector.

 here is the command when i use mnisten :
 --mnisten -d E:\train3\ -o prefix -s 32x24
here is the error messages:
0:cat 0images
1:dog 0images
2:horse 0images
error:total images are less than num_tests

**Comment by nyanp** [comment]
@yyfsss
Hi, since it isn't a problem of tiny-dnn side, could you reopen this issue at mnisten's repository? I also want you to tell us about file format of your images. thx

**Comment by yyfsss** [comment]
ok
