### ISSUE TITLE
compiling and running /example/main.cpp - getting 9% accuracy!

### ISSUE THREAD

**Issue by virusme** [tiny-dnn/tiny-dnn#38]
Hi,
Thanks for sharing this tiny-CNN.

I compiled /example/main.cpp with TBB and SSE options enabled.  I did not make any changes to "main.cpp". When the run the compiled executable, I get an accuracy of 9.58%!. Looking at the confusion matrix it appears that the network classifies every test sample as number "6"!

I am not sure if I am doing something wrong or not.

**Comment by nyanp** [comment]
@virusme 
In my environments (core-i7/win7/vc2013, and amazon ec2/ubuntu14.04/gcc4.8), I got an accuracy around 99%...What accuracy do you get when you compile it without TBB and SSE? Could you tell me TBB and compiler version?

**Comment by virusme** [comment]
Yes, I did use TBB+SSE. My configure command is:
./waf configure --SSE --TBB --TBB_ROOT=your-tbb-root --BOOST_ROOT=your-boost-root

I am on Ubuntu 14.04, G++ version 4.8.4,TBB 4.3 update 6

**Comment by edgarriba** [comment]
@virusme New tiny-cnn version has been released with a lots of bug fixes and multiple new features. Could you check again your measurements?

**Comment by pliptor** [comment]
Is example/main.cpp an older piece of code that has been split into subparts in the mnist folder? I see a built.bat meant for it.

**Comment by Randl** [comment]
@virusme Are you still interested in tiny-dnn? We had many changes since you opened the issue, try it :)

**Comment by pliptor** [comment]
For cross checking. example/main.cpp compiled on ubuntu 16.04  with

 g++ -std=c++11 -Wall -Werror -Wextra -pedantic -I ../ -O3 main.cpp -o main -lpthread

The output looks fine. 99.02% accuracy. Confusion matrix seems typical.

[examples_main.txt](https://github.com/tiny-dnn/tiny-dnn/files/770466/examples_main.txt)
