### ISSUE TITLE
Tensor class design

### ISSUE THREAD

**Issue by edgarriba** [tiny-dnn/tiny-dnn#388]
I open this ticket to discuss about the Tensor class design.

This is a second stage discussion started in https://github.com/tiny-dnn/tiny-dnn/issues/273.
We can resume the work using the following prototype as a base
https://github.com/tiny-dnn/tiny-dnn/pull/319/files

I propose to iterate over this UML extracted from the mentioned prototype
[http://uml.mvnsearch.org/gist/66f7cfd43699ebb0010a59dd65864f0d](http://uml.mvnsearch.org/gist/66f7cfd43699ebb0010a59dd65864f0d)

![66f7cfd43699ebb0010a59dd65864f0d](https://cloud.githubusercontent.com/assets/5157099/20109271/9d7a477e-a5df-11e6-997b-53d11ab14fca.png)

**Comment by pansk** [comment]
My questions/notes:

Why is data_gpu a shared_ptr and data_cpu a unique_ptr?

As I said elsewhere, I would consider the single-gpu case first. How can I transfer back data from the GPU to the CPU?
I'd make this object lazily move the memory back and forth, every time gpu or cpu memory is requested, like @nyanp was saying in #71 (those functions could actually become no-op on unified memory devices).

**Comment by edgarriba** [comment]
@pansk 

maybe with `unique_ptr` for `data_gpu` and `data_cpu` will be enough since we won't share the encapsulated data container.

for sure we'll consider single-gpu case, however `toDevice()` method will let us to handle device manual placement. To copy back we could introduce a routine called `fromDevice()` where the host CPU will be modeled by `my_cpu_device =`[`Device(device_t::CPU)`](https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/core/framework/device.fwd.h#L78)

Did I answer all of your questions?

**Comment by bhack** [comment]
@keryell We are brainstorming if design tensor with a single source approach so we are evaluating SyCL but we want to force users to use closed source compliers. As I see we are still in compatibility mode in trySYCL right?

**Comment by keryell** [comment]
@bhack Yes the Clang/LLVM-based outlining compiler is not ready yet in triSYCL. In the meantime you can play with ComputeCpp...

**Comment by bhack** [comment]
We are using CLCUDAPI here but I see that you rely on boost.compute.

**Comment by bhack** [comment]
@keryell Do you have any example code on how a Opencl kernel it is launched?

**Comment by patrikhuber** [comment]
FYI, Eigen-3.3 was released yesterday, with a preview of their [Tensor module](http://eigen.tuxfamily.org/index.php?title=3.3#Unsupported_Tensor_module).

**Comment by bhack** [comment]
@patrikhuber We have already touched this topic some months ago. See https://github.com/tiny-dnn/tiny-dnn/issues/153#issuecomment-223344341

**Comment by patrikhuber** [comment]
@bhack Ah I think I missed that. Anyway maybe there's some inspiration to draw from in their tensor class design ;-)

Btw, I'm not saying this necessarily applies here, but sometimes having a (header-only) dependency can actually make the actual library itself less bloated. If you do your own tensor class there's so many things to think about and implement (e.g. in the form of device backends), which bloats the library, makes it harder to contribute, maintain, more prone to bugs, etc. I'm mentioning this the second time this week actually, just be aware that the code you have now is already not "tiny" anymore and quite hard to maintain.

**Comment by bhack** [comment]
This depend much on how many tensor operations you need to still implement. It is hard to have many features and still being tiny.

**Comment by keryell** [comment]
@bhack You can look at the unit tests with "opencl" in their names in https://github.com/keryell/triSYCL/tree/master/tests/kernel, for example opencl_kernel_vector_add_args.cpp

You give me the idea to talk about this compatibility mode next week at SuperComputing.
For example it is possible to have a C++ tensor application using SYCL and use incrementally some existing optimized OpenCL-compatible (OpenCL or built-in) kernels for a specific device such as an FPGA.

**Comment by bhack** [comment]
Yes this could be our case I.e. for autotuning convolutional kernels. Boost compute has the interesting function of caching kernel but we actually use clcudaapi. Do you think that accessor could be handled also in https://github.com/CNugteren/CLCudaAPI?

**Comment by bhack** [comment]
@CNugteren could be interesting to have a kernel caching machanism upstream. What do you think?

**Comment by keryell** [comment]
@bhack yes it might be possible to use another underlying API. It is Open Source... Otherwise I think CUDA provides already the kernel caching behaviour.

**Comment by bhack** [comment]
@keryell So actually in the compatibility mode the only thing that remain of sycl are the accessor?

**Comment by keryell** [comment]
@bhack well, in compatibility mode you can construct basically most of the SYCL objects on top of the lower-level OpenCL objects. The accessors remain as a way to express dependencies. The SYCL runtime moves the underlying OpenCL buffers around for you and schedules the SYCL and plain OpenCL kernels accordingly.

**Comment by bhack** [comment]
So seems that has many simarites with CLCUDAAPI in compatiblity mode. We need to check differences in details.

**Comment by bhack** [comment]
An initial PR of the Tensor is at https://github.com/tiny-dnn/tiny-dnn/pull/400

**Comment by CNugteren** [comment]
Indeed, [CLCudaAPI](https://github.com/CNugteren/CLCudaAPI) mostly wraps OpenCL functions behind a much nicer API, so similar to this mode of SYCL. But it is not complete - it only supports functions currently used by users of the API. Also, it needs to maintain compatibility with it's CUDA counter-part, so certain features might not be possible to implement. So although it has its advantages (see the README) it is not perfect.

About your remark earlier about adding a cache in CLCudaAPI: I don't think that's the right place in this tiny light-weight header. For [CLBlast](https://github.com/CNugteren/CLBlast) I am actually caching compiled programs created by the CLCudaAPI, it is not different from regular caching and - if you implement it yourself - you can tune it to your own needs.

**Comment by edgarriba** [comment]
closing this since tensor is already in https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/core/framework/tensor.h
