### ISSUE TITLE
Precompiled headers

### ISSUE THREAD

**Issue by bhack** [tiny-dnn/tiny-dnn#393]
Evaluate the introduction of [precompiled headers](https://en.m.wikipedia.org/wiki/Precompiled_header) to speedup compile time expecially with serializzation enabled.

**Comment by bhack** [comment]
Some usefull links https://github.com/sakra/cotire/ and https://github.com/sakra/cotire/blob/master/README.md

**Comment by patrikhuber** [comment]
I'm not sure this belongs in a (header-only) library (I'd say "no"). In my opinion, a header-only library provides the headers (and a CMake target for people who use CMake), and if a user wants to use PCH (or any other build-acceleration), then it's completely up to the user, and up to them if and how they want to integrate that into **their** build-system, but not into tiny-dnn's. I am just advocating (again) for less complexity here. Less files, less scripts, easier scripts, it all means the project is easier to use, build, maintain and contribut to, particularly for less experienced users.

**Comment by bhack** [comment]
Yes this was for the user apps. I.e. boost has some guidance http://www.boost.org/build/doc/html/bbv2/reference/precompiled_headers.html

**Comment by patrikhuber** [comment]
Well I think my argument still stands - I don't think the example apps need this, they're there to have easy, simple examples to get started with tiny-dnn. Anyone doing serious work will create their own executable in their own project, and they can integrate PCH there if they are bothered by compile times and want to do it. And the other executables like caffe-converter etc. the compile times don't matter because they will very seldomly be modified.

**Comment by Randl** [comment]
@edgarriba @nyanp @beru @wangyida What do you think? Adding [Cotire](https://github.com/sakra/cotire/) sounds not that complicated, do we want to add it or somehow make it easier to use for end users?

**Comment by Randl** [comment]
https://github.com/tiny-dnn/tiny-dnn/issues/420 is obviously connected

**Comment by bhack** [comment]
Want we to introduce for our binaries (tools, examples, tutorials) or simply inform third party developers?

**Comment by Randl** [comment]
I'd say at least provide one example of how to use it and add couple of words in readme about speedup

**Comment by ArchieGu** [comment]
这是自动回复信息。
