### ISSUE TITLE
New name for cnn_size_t

### ISSUE THREAD

**Issue by Randl** [tiny-dnn/tiny-dnn#399]
As explained [here](https://github.com/tiny-dnn/tiny-dnn/pull/397#discussion_r87693123), `cnn_size_t` is a type used by serializer, and it should be reasonable size to keep model file small. If we need a big enough type compared to the memory space, we still need to use `size_t`, not `cnn_size_t`.

The naming is quite misleading, so I suppose to rename `cnn_size_t`. The name should

- not be confusing and mixed up with `size_t`
- be expressive, i.e. be connected to serialization in some way.

Options that were supposed are

1. `serial_size_t`.  Somewhat long, but seems OK for me
2.  `ssize_t`. Not good imho. Too similar with `size_t` and not expressive.
3. `serial_t`. Nice. Short, expressive and easy distinguished
4. `cnn_serial_t`. Longer, but mentions `cnn`.
5. Anything else?

**Comment by edgarriba** [comment]
I vote for 3

**Comment by beru** [comment]
I vote for 1.
3 and 4 can be misleading to serialized_type (data type? size type?).

**Comment by bhack** [comment]
I don't mention cnn prefix if we are in progress to bet not only a cnn. We could also use cereal_type it is a little bit less future prof but it is clear

**Comment by nyanp** [comment]
@Randl 
Nice suggestions :)

I vote for 1. A bit long, but it's clear. ```ssize_t``` is already used in some systems (ex. [sys/types.h](http://pubs.opengroup.org/onlinepubs/7908799/xsh/systypes.h.html)), and I don't think it's good to expose the name of 3rd-party library.

**Comment by edgarriba** [comment]
`cnn_size_t` is a typdef of [`uint32_t`](https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/config.h#L99) , why not just renamed to `uint_t`?
