### ISSUE TITLE
NNpack engine does not get initialized for FC layer

### ISSUE THREAD

**Issue by Kamairo** [tiny-dnn/tiny-dnn#403]
MWE:
```cpp
#define CNN_USE_NNPACK
#include "tiny_dnn/tiny_dnn.h"

int main(int argc, char** argv)
{
  using namespace tiny_dnn;
  const int size = 20;
  vec_t numbers(size);

  for (int i = 0; i < size; i++)
  {
    numbers.at(i) = i;
  }
  network<sequential> n;
  n << fully_connected_layer<sigmoid>(size, 2, true, backend_t::nnpack);
  n.weight_init(weight_init::constant(2));
  n.init_weight();

  auto res = n.predict_label(numbers);
}

```
Results in `nnp_status_uninitialized` status.

**Comment by nyanp** [comment]
cc: @edgarriba @azsane

**Comment by edgarriba** [comment]
@Kamairo you are right, in fully_connected and in maxpool it's missing. 
Check how is initialized in conv2d
https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/core/kernels/conv2d_op_nnpack.h#L53-56

**Comment by edgarriba** [comment]
Well check that https://github.com/tiny-dnn/tiny-dnn/pull/398/files fixes this

**Comment by azsane** [comment]
nnp_initailize only needs to be called once,but it's called every time net performs conv operation.

Is that a suitable place to call nnp_initialize globally?

**Comment by edgarriba** [comment]
@azsane You are right, I don't thin it's the best place. We need a global variable at network level to check if nnpack was initialized before.

**Comment by bhack** [comment]
In caffe2 there is a factory https://github.com/caffe2/caffe2/blob/master/caffe2/contrib/nnpack/nnpack_ops.cc#L52

**Comment by edgarriba** [comment]
but do we want static variables ? 
https://github.com/caffe2/caffe2/blob/master/caffe2/contrib/nnpack/nnpack_ops.cc#L49

**Comment by bhack** [comment]
We could follow this https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#i3-avoid-singletons

**Comment by edgarriba** [comment]
that's better, I'll try a quick fix for this.

@azsane could you check my review in https://github.com/tiny-dnn/tiny-dnn/pull/398 so that we can merge it?

**Comment by bhack** [comment]
Can we close this?

**Comment by bhack** [comment]
Ping

**Comment by Kamairo** [comment]
sorry, yeah sure, close it.

**Comment by bhack** [comment]
@Kamairo You can push the close button as the issue owner
