### ISSUE TITLE
Compilation errors 

### ISSUE THREAD

**Issue by tdlshashi** [tiny-dnn/tiny-dnn#409]
I am not able to compile even a basic program. I tried using eclipse and g++ in linux. Also, used visual studio and g++ windows . I tried to run main.cpp in examples folder, The following errors are shown.
![image](https://cloud.githubusercontent.com/assets/6492426/20339812/6edc3f82-ac04-11e6-9783-c10f533decf2.jpg)
Also, when I run in visual studio 2010, following errors are there

_1>------ Build started: Project: test1, Configuration: Release Win32 ------
1>Build started 11/16/2016 2:09:14 PM.
1>InitializeBuildStatus:
1>  Touching "Release\test1.unsuccessfulbuild".
1>ClCompile:
1>  All outputs are up-to-date.
1>  test1.cpp
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(59): error C2143: syntax error : missing ';' before '='
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(59): error C2873: 'size_type' : symbol cannot be used in a using-declaration
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(59): error C2513: 'int' : no variable declared before '='
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(59): error C2226: syntax error : unexpected type 'uint64_t'
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(140): error C2873: 'Type' : symbol cannot be used in a using-declaration
1>          E:\tiny-dnn-master\cereal/details/helpers.hpp(165) : see reference to class template instantiation 'cereal::NameValuePair<T>' being compiled
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(140): error C2143: syntax error : missing ';' before '='
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(144): error C2238: unexpected token(s) preceding ';'
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(164): error C2146: syntax error : missing ';' before identifier 'value'
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(164): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(164): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(211): error C2873: 'PT' : symbol cannot be used in a using-declaration
1>          E:\tiny-dnn-master\cereal/details/helpers.hpp(219) : see reference to class template instantiation 'cereal::BinaryData<T>' being compiled
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(211): error C2143: syntax error : missing ';' before '='
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(213): error C2238: unexpected token(s) preceding ';'
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(217): error C2146: syntax error : missing ';' before identifier 'data'
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(217): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(217): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(255): error C2873: 'Type' : symbol cannot be used in a using-declaration
1>          E:\tiny-dnn-master\cereal/details/helpers.hpp(265) : see reference to class template instantiation 'cereal::SizeTag<T>' being compiled
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(255): error C2143: syntax error : missing ';' before '='
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(257): error C2238: unexpected token(s) preceding ';'
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(264): error C2146: syntax error : missing ';' before identifier 'size'
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(264): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(264): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(291): error C2873: 'KeyType' : symbol cannot be used in a using-declaration
1>          E:\tiny-dnn-master\cereal/details/helpers.hpp(317) : see reference to class template instantiation 'cereal::MapItem<Key,Value>' being compiled
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(291): error C2143: syntax error : missing ';' before '='
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(294): error C2238: unexpected token(s) preceding ';'
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(296): error C2873: 'ValueType' : symbol cannot be used in a using-declaration
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(296): error C2143: syntax error : missing ';' before '='
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(299): error C2238: unexpected token(s) preceding ';'
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(307): error C2146: syntax error : missing ';' before identifier 'key'
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(307): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(307): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(308): error C2146: syntax error : missing ';' before identifier 'value'
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(308): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(308): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(353): error C2780: 'std::pair<_Ty1,_Ty2> std::_Hash<_Traits>::emplace(_Valty &&)' : expects 1 arguments - 2 provided
1>          with
1>          [
1>              _Ty1=std::_List_iterator<std::_List_val<std::pair<const size_t,uint32_t>,std::allocator<std::pair<const size_t,uint32_t>>>>,
1>              _Ty2=bool,
1>              _Traits=std::tr1::_Umap_traits<size_t,uint32_t,std::_Hash_compare<size_t,std::hash<size_t>,std::equal_to<size_t>>,std::allocator<std::pair<const size_t,uint32_t>>,false>
1>          ]
1>          C:\Program Files\Microsoft Visual Studio 10.0\VC\include\xhash(296) : see declaration of 'std::_Hash<_Traits>::emplace'
1>          with
1>          [
1>              _Traits=std::tr1::_Umap_traits<size_t,uint32_t,std::_Hash_compare<size_t,std::hash<size_t>,std::equal_to<size_t>>,std::allocator<std::pair<const size_t,uint32_t>>,false>
1>          ]
1>E:\tiny-dnn-master\cereal/details/helpers.hpp(353): fatal error C1903: unable to recover from previous error(s); stopping compilation
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:12.24
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========_

**I am new to tiny-dnn. If you can guide me into environment setup and running a simple program, I would really appreciate it.**

**Comment by bhack** [comment]
Probably it is a pure support ticket. Can you post this on stackoverflow?

**Comment by beru** [comment]
> tdlshashi wrote:
> Also, when I run in visual studio 2010, following errors are there...

@tdlshashi 
tiny-dnn uses serialization library named `cereal`.
http://uscilab.github.io/cereal/index.html
Its documentation says it supports MSVC 2013 (or newer) and tiny-dnn itself also uses C++11 language features. Therefore, I recommend you to use Visual Studio 2015.

Support For C++11/14/17 Features (Modern C++)
https://msdn.microsoft.com/en-us/library/hh567368.aspx

**Comment by tdlshashi** [comment]
@beru 

Can you please guide me through..  Even briefly...

**Comment by bhack** [comment]
Please move this on stackoverflow.

**Comment by beru** [comment]
@tdlshashi You can download Visual Studio Community from [here](https://www.visualstudio.com/downloads/). Please try tiny-dnn library again with latest IDE from Microsoft.

@bhack Some people are having difficulty with running example programs so I'll update Wiki on this weekend.

**Comment by nyanp** [comment]
@beru 
Nice!
I recommend you to update docs or readme.md instead of wiki, because its traffic is much better (~10x) than wiki.

**Comment by beru** [comment]
@nyanp I updated Wiki. I'll update docs or readme.md next time.

**Comment by frostRed** [comment]
@beru I also compile examples folder failed. `cmake .` and `make`, then get `pthread create undefined reference.` 

but at outer folder, I can use `cmake -D BUILD_EXAMPLES=ON` to compile examples. It works well.

**Comment by bhack** [comment]
@frostRed What is your environment?

**Comment by frostRed** [comment]
@bhack 

In tiny_dnn **root** fold, run `cmake .`:

```
-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type specified; defaulting to CMAKE_BUILD_TYPE=Release.
-- Found Intel TBB
-- Could not find NNPACK include. Turning NNPACK_FOUND off
-- Could not find NNPACK lib. Turning NNPACK_FOUND off
-- TBB and OMP disabled: Using Pthread instead.
-- C++11 support has been enabled by default.
-- Performing Test COMPILER_HAS_SSE_FLAG
-- Performing Test COMPILER_HAS_SSE_FLAG - Success
-- Performing Test COMPILER_HAS_AVX_FLAG
-- Performing Test COMPILER_HAS_AVX_FLAG - Success
-- Performing Test COMPILER_HAS_AVX2_FLAG
-- Performing Test COMPILER_HAS_AVX2_FLAG - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PROTOBUF Compiler: /usr/bin/protoc
```

In **examples** folder, `cmake .` get

```
-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
```

**Comment by bhack** [comment]
I don't rember if exemple could be builded alone. Why do you want to try to compile inside example?

**Comment by edgarriba** [comment]
examples have to be built from root cmake

**Comment by Randl** [comment]
@tdlshashi Do you still have any problems?

**Comment by Randl** [comment]
No answer for a week, closing
