### ISSUE TITLE
read the trained model and predict error

### ISSUE THREAD

**Issue by kingloo2014** [tiny-dnn/tiny-dnn#41]
I have a trained model and saved it. But a mistake happened when I predict a test sample's class attribute. Of course, I have load the model before the prediction correctly. The debugging information gave the tips "the input layer's size is empty", I donnot understand the information, because the entire proccess is right!

**Comment by kingloo2014** [comment]
I found the error. when the model is a member varable of a class, the model's parameters will be modified at the different member function. I donnot know why!

**Comment by nyanp** [comment]
@kingloo2014 
It would be helpful if you show me example code and tell me your compiler version. Thanks!

**Comment by edgarriba** [comment]
@kingloo2014 Still having this issue?

**Comment by Randl** [comment]
@kingloo2014 Do you still have this issue?

**Comment by Randl** [comment]
No reply, closing
