### ISSUE TITLE
Adding parameter beyond pixel data

### ISSUE THREAD

**Issue by pixelglow** [tiny-dnn/tiny-dnn#42]
In the LeNet example:

https://github.com/nyanp/tiny-cnn/wiki/MNIST-Example

Is there any way to add a parameter beyond just the raw pixel data? For example, I would like to add in the (x, y) coordinates of the given image within a larger image. Presumably this would be added on the last layer, the fully connected layer, as additional 2 inputs. I have no idea how to do this, or if it is possible.

**Comment by nyanp** [comment]
@pixelglow 
I don't know much about it, but following paper proposes deep neural networks, which output a fixed number of object coordinates.

[Dumitru Erhan, Christian Szegedy, Alexander Toshev, and Dragomir Anguelov, "Scalable object detection using deep neural networks", CVPR2014](http://www.cv-foundation.org/openaccess/content_cvpr_2014/papers/Erhan_Scalable_Object_Detection_2014_CVPR_paper.pdf)

**Comment by pixelglow** [comment]
I should rephrase my question.

I want to add a few more parameters to the tiny-cnn neural network expressed in the the MNIST-Example. How do I do that? Does the API support a few more parameters other than the pixel data that is passed in?

In a classic neural network, there's no geometric interpretation to the input parameters, but convolutional networks like LeNet interpret their input data as adjacent pixels. I want to be able to add some non-geometric input parameters to the neural net.

**Comment by nyanp** [comment]
@pixelglow 
Oh, I misunderstood.
There is no API support for such purpose. (caffe may support such network)

**Comment by edgarriba** [comment]
@pixelglow 
In last version you can handle graph based networks that could handle those cases.
https://github.com/nyanp/tiny-cnn/releases/tag/v0.1.0

@nyanp  Is that right?

**Comment by Randl** [comment]
@pixelglow Have you tried the proposed solution?

**Comment by Randl** [comment]
No reply, closing
