### ISSUE TITLE
un-Tiny compilation time

### ISSUE THREAD

**Issue by bhack** [tiny-dnn/tiny-dnn#420]
Compilation time it is a little bit really out of control and on different system it is exhausting compilation memory. Actually on some system I needed to manually limit gcc with [some flags](http://jkroon.blogs.uls.co.za/it/scriptingprogramming/preventing-gcc-from-trashing-the-system)

**Comment by bhack** [comment]
Add -ftime-report -fmemory-report in CMake and try to analyze reports on your environment

**Comment by pansk** [comment]
This is one of the drawbacks of a header-only library.

**Comment by bhack** [comment]
Yes if we enable the reports flags we could see how this issue is specially on serialization

**Comment by bhack** [comment]
http://stackoverflow.com/questions/12290639/quantifiable-metrics-benchmarks-on-the-usage-of-header-only-c-libraries

**Comment by bhack** [comment]
A little bit of feeback with serializzation ON that actually it is required for compiling mnist example for mnist/train.cpp:

```
Memory Total          1556M

Top Execution times (seconds)

 phase lang. deferred    :  37.50 (50%) usr   4.45 (35%) sys  41.95 (43%) wall 2069816 kB (52%) ggc
 phase opt and generate  :  30.19 (40%) usr   6.80 (53%) sys  38.03 (39%) wall 1573418 kB (40%) ggc
 template instantiation  :  16.79 (22%) usr   3.86 (30%) sys  20.88 (21%) wall 1672857 kB (42%) gg 
|overload resolution    :  13.20 (18%) usr   3.06 (24%) sys  16.41 (17%) wall 1316716 kB (33%) ggc
```

**Comment by bhack** [comment]
I've also tried to run iowyu http://stackoverflow.com/questions/30951492/how-to-use-the-tool-include-what-you-use-together-with-cmake-to-detect-unused-he to see if we could minimize includes

**Comment by bhack** [comment]
http://baptiste-wicht.com/posts/2016/02/use-templight-and-templar-to-debug-cpp-templates.html

**Comment by bhack** [comment]
Some more tips at http://stackoverflow.com/questions/28919285/identify-slow-to-compile-function

**Comment by nyanp** [comment]
- Unfortunately iowyu doesn't help much for header only libraries.
- Note that tiny-dnn's serialization obeys the zero-overhead principle in C++ - When we don't call serialization API, the compilation time is as fast as previous release.

**Comment by beru** [comment]
@bhack You can decrease build time of `example_mnist_train` by following method.

In file `tiny_dnn/util/serialization_helper.h`, change
```
#define CNN_REGISTER_LAYER_BODY(layer_type, layer_name) \
    register_loader(layer_name, detail::load_layer_impl<InputArchive, layer_type>);\
    register_type<layer_type>(layer_name);\
    register_saver(layer_name, detail::save_layer_impl<OutputArchive, layer_type>)
```
to
```
#define CNN_REGISTER_LAYER_BODY(layer_type, layer_name) \
    /*register_loader(layer_name, detail::load_layer_impl<InputArchive, layer_type>);*/\
    register_type<layer_type>(layer_name);\
    register_saver(layer_name, detail::save_layer_impl<OutputArchive, layer_type>)
```

But promise me you won't try this when you use `example_mnist_test`.

**Comment by bhack** [comment]
@nyanp We cannot contniue to tink that the library could wotk without serializzation. The number are here. Memory 1556M for mnist example train.cpp. And more than one minute only for the first top two compiling stages.

**Comment by beru** [comment]
This issue is related with #316 #291 

After reading `examples/mnist/test.cpp` program, I finally noticed that the nn is constructed on the fly and the program does not use `construct_net` function. So that's why naynp denied the idea I wrote on gitter room yesterday.

@nyanp I'm counting on you for this!
https://github.com/tiny-dnn/tiny-dnn/issues/316#issuecomment-249406603

**Comment by beru** [comment]
@nyanp 

Currently, if `USE_SERIALIZER=OFF` then `example_mnist_train`, `example_mnist_test`, `example_mnist_quantized_train`, `example_deconv_train` are not built, but this is unfavourable.

What about supporting `only network *weights*, not network configuration load/save` feature and reviving `construct_net` function in test programs using preprocessor macros when `USE_SERIALIZER=OFF`? Moreover, `content_type::weights` will be specified to 2nd argument of `network::load` and `network::save` in that case.

In such case, I wish the library will keep binary compatibility with standard implementation that is using `cereal` and it would be good if the library appropriately handles errors (such as checking content_type of serialized file data and printing error message, etc...).

**Comment by Randl** [comment]
http://baptiste-wicht.com/posts/2016/02/use-templight-and-templar-to-debug-cpp-templates.html http://baptiste-wicht.com/posts/2016/01/improve-dll-and-etl-compile-time-further.html might adress the issue

**Comment by ArchieGu** [comment]
这是自动回复信息。

**Comment by TrevorBlythe** [comment]
just precompile the library?
