### ISSUE TITLE
update the readme for tensorflow

### ISSUE THREAD

**Issue by wdroz** [tiny-dnn/tiny-dnn#431]
Tensorflow support officially windows from 29 november : https://developers.googleblog.com/2016/11/tensorflow-0-12-adds-support-for-windows.html

So you can update your table in your readme ;-)

**Comment by edgarriba** [comment]
@wdroz Thanks to point this out.
We'll put it on the todo list, however you could pull request it :smile:

**Comment by bhack** [comment]
Yes if you could open this trivial PR we could merge it soon.
