### ISSUE TITLE
Add Mxnet in ReadMe

### ISSUE THREAD

**Issue by edmBernard** [tiny-dnn/tiny-dnn#432]
I think it must be important to add Mxnet as it is a direct concurrent in C++ framework and for embed deep learning. 
It could be interesting to add one more line to split training and execution. As it could be different for exemple : Tensorflow API in C++ with graph freeze allows to execute NN in C++.

I'm not a pro in Mxnet and all of these framework but I try to complete the comparison : 
## Comparison with other libraries

||tiny-dnn|[Caffe](https://github.com/BVLC/caffe)|[Theano](https://github.com/Theano/Theano)|[TensorFlow](https://www.tensorflow.org/)|[Mxnet](http://mxnet.io/)|
|---|---|---|---|---|---|
|Prerequisites|__Nothing__(Optional:TBB,OpenMP)|BLAS,Boost,protobuf,glog,gflags,hdf5, (Optional:CUDA,OpenCV,lmdb,leveldb etc)|Numpy,Scipy,BLAS,(optional:nose,Sphinx,CUDA etc)|numpy,six,protobuf,(optional:CUDA,Bazel)|BLAS (optional:CUDA)|
|Modeling By|C++ code|Config File|Python Code|Python Code|C++, Python, R, Julia ...|
|Training|C++|C++, Python|Python|Python|C++, Python, R, Julia ...|
|Execution|C++|C++, Python|Python|Python, C++*2|C++*4, Python, R, Julia ...|
|GPU Support|No|Yes|Yes|Yes|Yes|
|Installing|Unnecessary|Necessary|Necessary|Necessary|Necessary*3|
|Windows Support|Yes|No*|Yes|Yes|Yes|
|Pre-Trained Model|Yes(via caffe-converter)|Yes|No*|No*|Yes(via caffe-converter)|

*2 limited C++ API
*3 I don't think installation is necessary with the Mxnet amalgamation Api
*4 both full API and limited api via amalgamation

**Comment by bhack** [comment]
Can you propose a PR?

**Comment by beru** [comment]
@edmBernard I posted a PR for you. Would it be alright?

**Comment by edmBernard** [comment]
yeah sure no problem

**Comment by beru** [comment]
@edmBernard The PR is now merged.

By the way, [Chainer](https://github.com/pfnet/chainer) is another famous library for deep learning. It's hard for me to believe that it has less number of stargazers for it... the fact is worthy enough to put my head into disgusting pie.

**Comment by bhack** [comment]
And also [Caffe2](https://github.com/caffe2/caffe2)

**Comment by beru** [comment]
@bhack We will may need dedicated pages for Caffe2.x vs Caffe3.

**Comment by bhack** [comment]
@beru There isn't any Caffe3 but [...](https://en.m.wikipedia.org/wiki/Ammazzacaffè). :smile:

**Comment by edmBernard** [comment]
I think the problem is the number of implemented examples. When I begin with NN I search an implementation for object detection and at this time there is only Tensorflow (Tensorbox), Caffe (Faster RCNN) and Mxnet (Faster RCNN, SSD).
The good point for Mxnet, they have lots of examples in their official git. Tensorflow and Caffe have a good community. (Against caffe lots of algo on github use Matlab :( )

**Comment by beru** [comment]
@edmBernard I'll wait future AIs will create a time machine to make NN examples flourish.
By the way, I've found [this](https://github.com/bittnt/Objectness) last year.
