### ISSUE TITLE
static 

### ISSUE THREAD

**Issue by moazzemi** [tiny-dnn/tiny-dnn#433]
I've tried the mnist example and it works great but now I need to make a statically linked version of it for compatibility. Does anyone know if this is possible and what I have to change in Makefiles?

**Comment by bhack** [comment]
What do you want to make?

**Comment by moazzemi** [comment]
for example binary for example_mnist_test
statically linked to all the required libraries.

**Comment by bhack** [comment]
But are using/comping it header only or with some optional optimized engine enabled?

**Comment by moazzemi** [comment]
no optional optimized engine.

**Comment by bhack** [comment]
So what kind of libraries linking is required?

**Comment by moazzemi** [comment]
I'm not sure as I'm using a cross compiler and can't figure out how to tell the cmake that generates the examples to do static linking.

**Comment by bhack** [comment]
[This lines](https://github.com/tiny-dnn/tiny-dnn/blob/master/examples/CMakeLists.txt#L7,L8) in Cmake pilots executable and "eventually" required linking for examples including Mnist

**Comment by moazzemi** [comment]
great. that probably would have been a better solution but I found that if I change link.txt from -rdynamic to -static it also works.

**Comment by bhack** [comment]
Follow official [Cmake docs](https://cmake.org/cmake/help/v3.0/command/add_library.html).

**Comment by bhack** [comment]
@edgarriba I think that we can close it. Need we to add something about static in our cmake (example/tools/docs)?

**Comment by Randl** [comment]
@bhack I don't think we need to add anything to doc. This is mostly compiler-related and not tiny-dnn-related
