### ISSUE TITLE
Compiler issues a lot of warnings during compilation

### ISSUE THREAD

**Issue by festlv** [tiny-dnn/tiny-dnn#440]
I tried to use tiny-dnn in an existing project but got a lot of warnings by just including tiny-dnn.h
The list of warnings is available here: https://paste.ee/p/0mPze

Warnings are possibly related to project's compiler flags (which are the strictest that I know of):
> -Werror -Wall -Wextra -Wpedantic

GCC version:

> Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
> Thread model: posix
> gcc version 6.2.1 20160830 (GCC) 

Since I had -Werror, these warnings were treated as errors and I had to loosen the flags to build tiiny-dnn.

By quickly scanning the list, I see two types of warnings:

1. Issues in stb_image.h (should be reported upstream?)
2. Unused parameters when some feature is turned off:
```
inline void func(int param1) {
#if defined(USE_OPENCL) || defined(USE_CUDA)
  //code that uses params1
#else
    nn_warn("TinyDNN was not build with OpenCL or CUDA support.");
#endif
}
```

@bhack suggested to propose one of these mechanisms: https://sites.google.com/site/opensourceconstriubtions/ettl-martin-1/articles/suppress-unused-parameter-compiler-warning

Since I have very little knowledge about typical environments/compilers where tiny-dnn is being used I will refrain from suggesting any particular way to fix the warnings (or whether or not they need to be fixed at all).

**Comment by nyanp** [comment]
@festlv 
Hi,
You can use a macro for this purpose:
https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/util/macro.h#L29

It's equivalent to the solution 3 in your link.
I'd very happy if you can send a PR to solve them :)

**Comment by bhack** [comment]
@nyanp I think that for third_party we could try to sync components before opening an upstream issue.

**Comment by beru** [comment]
According to the version number, they are still the same at the moment.
https://github.com/nothings/stb/blob/master/stb_image.h
https://github.com/nothings/stb/blob/master/stb_image_resize.h
https://github.com/nothings/stb/blob/master/stb_image_write.h
https://github.com/tiny-dnn/tiny-dnn/blob/master/third_party/stb/stb_image.h
https://github.com/tiny-dnn/tiny-dnn/blob/master/third_party/stb/stb_image_resize.h
https://github.com/tiny-dnn/tiny-dnn/blob/master/third_party/stb/stb_image_write.h

**Comment by bhack** [comment]
Ok @festlv you can check between [this upstream issues](https://github.com/nothings/stb/search?q=compile+warning&state=open&type=Issues&utf8=✓) or open an new one and comment here for reference.

**Comment by festlv** [comment]
There is already an open PR upstream for at least some of the warnings: https://github.com/nothings/stb/pull/344

**Comment by nothings** [comment]
I have fixed all current PRs for stb_image, but not for the other libs. Also, some are currently just issues rather than PRs and I didn't touch those. They'll get fixed eventually, but PRs will get fixed sooner.

**Comment by bhack** [comment]
@nothings Thank you

**Comment by festlv** [comment]
I gave a shot at merging stb_image.h after changes by @nothings but it appears that stb_image.h has been modified (i.e. it's already a "forked" copy).
Diff here: https://paste.ee/p/Le2ro

**Comment by bhack** [comment]
@festlv What is the status of this issue? Need we only to resync with stb and gemmlowp?

**Comment by festlv** [comment]
Yes, I think so. I will send a PR with the merges.

**Comment by beru** [comment]
@nyanp `stb_image.h` is different from original one. Do you know anything about it?
https://github.com/tiny-dnn/tiny-dnn/pull/337/files#diff-4ebfa7a69f20cef256e0c8bcee634d0f

**Comment by festlv** [comment]
I believe this issue is not present in the latest version of tiny-dnn anymore. 

This was important to be able to use tiny-dnn in precompiled header in QtCreator when using "-Werror -Wall -Wextra -Wpedantic" compiler flags to enable all warnings.

**Comment by Randl** [comment]
Now that `-Werror` is not recommended, mainly since third party line might still produce warnings
