### ISSUE TITLE
Windows Support for Caffe

### ISSUE THREAD

**Issue by mrgloom** [tiny-dnn/tiny-dnn#442]
Hello, Caffe now have `Windows Support`, you can build it with VS2013, so your table is outdated.

**Comment by beru** [comment]
Anyone can send PRs to update it but what about moving [the table](https://github.com/tiny-dnn/tiny-dnn#comparison-with-other-libraries) to a new Wiki page?

**Comment by beru** [comment]
@mrgloom I updated the `README.md`. The table is in Wiki section, so please check it.
https://github.com/tiny-dnn/tiny-dnn/wiki/Comparison-with-other-libraries
Now, Caffe's `Windows support` is `Yes`.

**Comment by edgarriba** [comment]
@mrgloom @beru can we close this?

**Comment by beru** [comment]
@edgarriba It's OK for me. Is there anything to add more? @mrgloom
