### ISSUE TITLE
About artistic style transfer  implementation

### ISSUE THREAD

**Issue by yuchen112358** [tiny-dnn/tiny-dnn#447]
Could you please tell me whether has a tinycnn implementation of the paper A Neural Algorithm of Artistic Style by Leon A. Gatys, Alexander S. Ecker, and Matthias Bethge or not ?

**Comment by bhack** [comment]
If you want to train that network you can try to build and see what festure is missing. If you have a pretrained caffe model of that you can try to use tiny-dnn caffe converter

**Comment by yuchen112358** [comment]
Tanks! By the way, can I use tinycnn to train vgg16 or vgg19? Are there some examples about training vgg16 or vgg19 using tiny?

**Comment by yuchen112358** [comment]
@bhack Tanks! By the way, can I use tinycnn to train vgg16 or vgg19? Are there some examples about training vgg16 or vgg19 using tiny?

**Comment by bhack** [comment]
You can start to import pretrained from Caffe or compose yourself.

**Comment by yuchen112358** [comment]
@bhack Thanks a lot!

**Comment by Randl** [comment]
@yuchen112358 Have you succeeded? If not what are the problems?

**Comment by Randl** [comment]
No answer for more than a week. Closing
