### ISSUE TITLE
proposal: rename How-to-contribute.md to CONTRIBUTING.md

### ISSUE THREAD

**Issue by yumetodo** [tiny-dnn/tiny-dnn#454]
https://github.com/blog/1184-contributing-guidelines

Github will add a link to ``CONTRIBUTING.md`` when a contributor creates an Issue or opens a Pull Request.

https://github.com/tiny-dnn/tiny-dnn/blob/master/docs/developer_guides/How-to-contribute.md
rename that and move root

**Comment by Randl** [comment]
For such small changes I suppose you directly send PR instead of creating issue.

**Comment by yumetodo** [comment]
@Randl To avoid conflict, this issue should be resolved at #453, I think.

**Comment by edgarriba** [comment]
I close this since it's merged in https://github.com/tiny-dnn/tiny-dnn/issues/463
