### ISSUE TITLE
Can't import DetectNet model from DIGITS

### ISSUE THREAD

**Issue by reunanen** [tiny-dnn/tiny-dnn#459]
I have trained a [DetectNet](https://devblogs.nvidia.com/parallelforall/detectnet-deep-neural-network-object-detection-digits/) model in DIGITS, and I'm trying to import it to tiny-dnn.

Unfortunately, I can't import it – I get `nn_error("unsupported padding type")` [here](https://github.com/tiny-dnn/tiny-dnn/blob/341da33a62d9bac97f782420d4438e0e43137cb4/tiny_dnn/io/caffe/layer_factory_impl.h#L273). (`w_pad` is 1, `pool_size_w` is 3.)

Will try to find the time to study the problem and hopefully create a PR – but not entirely sure what is the correct way to fix this, so any tips would be greatly appreciated.

Also, not sure, but guessing the same might apply even to vanilla GoogLeNet trained in DIGITS (DetectNet is based on GoogLeNet).

**Comment by reunanen** [comment]
For what it's worth, this comes from a max-pooling layer.

**Comment by reunanen** [comment]
[This change](https://github.com/reunanen/tiny-dnn/commit/38adeae05f9bacc8f921ae712f20fa2ac5dddcdd) at least makes the import apparently succeed. But quite unsure about it, so not creating a PR for now.

**Comment by bhack** [comment]
Any news? Can you propose a draft PR?

**Comment by reunanen** [comment]
@bhack No news. As [I wrote](https://github.com/tiny-dnn/tiny-dnn/issues/459#issuecomment-267341135), [this change](https://github.com/reunanen/tiny-dnn/commit/38adeae05f9bacc8f921ae712f20fa2ac5dddcdd) made the import apparently succeed, but I have no clue if it breaks something else.

**Comment by bhack** [comment]
Try to propose it as PR. We will put in the PR review queue.

**Comment by Randl** [comment]
@reunanen After merge of https://github.com/tiny-dnn/tiny-dnn/pull/557 , this one can be closed, right?

**Comment by bhack** [comment]
Can we close also https://github.com/tiny-dnn/tiny-dnn/issues/146?

**Comment by reunanen** [comment]
@Randl Yes, I think so. Closing.
