### ISSUE TITLE
Same matching accuracy always

### ISSUE THREAD

**Issue by skazmi1** [tiny-dnn/tiny-dnn#460]
I created my idx3,idx1 files in mnisten. I then trained them in tiny dnn using example_mnist_train and tested them with example_mnist_test. I always get the same accuracy regardless of what testing image I use. Has anyone else encountered this before?

P.S I am using black on white backgrounds like it is supposed to be.

**Comment by bhack** [comment]
We need a little bit more of detail. Have you a code snipset? Can you retry with master?

**Comment by Randl** [comment]
No answer for a week, closing
