### ISSUE TITLE
the openmp configure is not working？

### ISSUE THREAD

**Issue by zhengq200618** [tiny-dnn/tiny-dnn#461]
After I use -DUSE_OMP=ON to build the benchmarks_all example. Then run. I find the program just run on one core and  I don't have any speed up. I don't know why.

**Comment by pi-null-mezon** [comment]
Note that to enable openmp you should additionally link your application with openmp binaries. What compiler and in what IDE you have used?

**Comment by bhack** [comment]
Any news on this?

**Comment by Randl** [comment]
No answer for a week, closing
