### ISSUE TITLE
How to compile and run the mnist example on MacOS ?

### ISSUE THREAD

**Issue by lisuichan** [tiny-dnn/tiny-dnn#467]
Hi ,I'm a new to this ,Can someone tell me how to compile and run the mnist example on MacOS?

**Comment by Randl** [comment]
What the problem you have?

**Comment by lisuichan** [comment]
I have already solved the problem by wiki : "A beginner's guide to build examples"!

**Comment by edgarriba** [comment]
@lisuichan  since problem solved I close this
