### ISSUE TITLE
CMakeLists for caffe importer

### ISSUE THREAD

**Issue by rperrot** [tiny-dnn/tiny-dnn#468]
Hi, 

First of all, thank you for this simple and really easy to use den library (maybe the only c++ dnn library  that compiles effortless).

I tried caffe importer, that seems to work well. And I have a suggestion to ease the compilation. Using CMake it's possible to make protobuf usage more simple (and transparent to the user), here are the revenant lines : 

```
# Get the Protobuf files 
find_package( Protobuf REQUIRED )

... 

# generate CPP file for connexion between protobuf and tiny_dnn 
PROTOBUF_GENERATE_CPP( PROTO_SRC PROTO_HDR ${CMAKE_CURRENT_SOURCE_DIR}/../tiny_dnn/io/caffe/caffe.proto )

# Add the caffe.pb.cc and caffe.pb.h 
add_executable( Classifier caffe_converter.cc ${PROTO_SRC} ${PROTO_HDR} )

# Add the include dir (protobuf and current binary, where the caffe.pb.h is)
target_include_directories( Classifier PRIVATE ${CMAKE_CURRENT_BINARY_DIR} ${PROTOBUF_INCLUDE_DIR} )

# Link with protobuf 
target_link_libraries( Classifier ${PROTOBUF_LIBRARY} )

# set c++11 compilation  
set_target_properties( Classifier PROPERTIES CXX_STANDARD 11 )
```

Hope it helps.

**Comment by bhack** [comment]
Can you prepare a PR?

**Comment by rperrot** [comment]
Ok, I'll do it soon.

**Comment by animetrics** [comment]
What about issue #429 which says that caffe converted models don't currently work properly?  Are converted models working properly for you?

**Comment by rperrot** [comment]
No, I've got almost the same results as @rmbarbosa : 

> n02090721 Irish wolfhound,0.870046
n03976657 pole,0.0188539
n03814906 necklace,0.0151208
n03124043 cowboy boot,0.00946627
n03063689 coffeepot,0.00499565
