### ISSUE TITLE
tiny-dnn does not support this layer type:slice

### ISSUE THREAD

**Issue by kingvision** [tiny-dnn/tiny-dnn#494]
Hi:
    i got an error:
    tiny-dnn does not support this layer type:slice.
    is there slice layer in tiny-dnn?
thanks

**Comment by bhack** [comment]
It is supported. See https://github.com/tiny-dnn/tiny-dnn/pull/233. Are you using caffe converter?

**Comment by kingvision** [comment]
yes ,i am using caffe converter.

**Comment by bhack** [comment]
Caffe converter still needs to support this. See https://github.com/tiny-dnn/tiny-dnn/issues/146#issuecomment-233126470

**Comment by kingvision** [comment]
@bhack caffe converter support maxout ?

**Comment by bhack** [comment]
Tiny-dnn still require maxout to be contributed then caffe convert could support it.

**Comment by bhack** [comment]
I close this as duplicate. Please open a new PR or ISSUE for maxout.
