### ISSUE TITLE
Style Guideline

### ISSUE THREAD

**Issue by edgarriba** [tiny-dnn/tiny-dnn#495]
I open this issue in order to vote coding style.
Just put  a comment with the feature you and vote it with a :+1: 
If possible no large discussions in order to easily count.

**Comment by edgarriba** [comment]
4 spaces

**Comment by edgarriba** [comment]
2 spaces

**Comment by edgarriba** [comment]
line-width 80

**Comment by edgarriba** [comment]
line-width 120

**Comment by Randl** [comment]
80 chars line with 2 spaces is adopted.
