### ISSUE TITLE
error in vs2013

### ISSUE THREAD

**Issue by bluekingdom** [tiny-dnn/tiny-dnn#503]
met error like this:
`1>D:\download\tiny-dnn-master\cereal/archives/json.hpp(266): error C2783: “void cereal::JSONOutputArchive::saveLong(T)”: 未能为“__formal”推导 模板 参数
1>          D:\download\tiny-dnn-master\cereal/archives/json.hpp(261) : 参见“cereal::JSONOutputArchive::saveLong”的声明`
can anyone give some tip? thx~~~

**Comment by beru** [comment]
@bhack I have no idea.

**Comment by bhack** [comment]
@bluekingdom We need a snippet of code so that we can reproduce it. Can you share it?

**Comment by bluekingdom** [comment]
all compile output like this:
![image](https://cloud.githubusercontent.com/assets/6635281/21748939/362accb0-d5cd-11e6-8e2c-352b9f5a5030.png)
and i double click the error, it direct to the function named saveLong() in json.hpp.
![image](https://cloud.githubusercontent.com/assets/6635281/21748955/8ceeeae0-d5cd-11e6-98eb-b3c7327ccddd.png)
i think the msvc2013 can not deduce the template about saveLong, but i has not idea how to fix it.

**Comment by beru** [comment]
@bluekingdom I don't see those errors with Visual Studio 2013 Update 5.
![image](https://cloud.githubusercontent.com/assets/1131125/21750281/fd58c6d2-d5f2-11e6-966a-c8433033e82b.png)

If you still haven't applied the update, you may download the updater program from this page.
https://www.microsoft.com/zh-CN/download/details.aspx?id=48129
And please consider migrating to Visual Studio 2015 Update 3 if it'd be possible for you to do so.

**Comment by bluekingdom** [comment]
@beru thx~ i update my vs to the version update 5, and then compile success !
