### ISSUE TITLE
How use TBB to complie the project?

### ISSUE THREAD

**Issue by lji72** [tiny-dnn/tiny-dnn#51]
Hi,I'm very grateful to your work.It's so nice.I  have a work which  need the cnn.because of the big data,I want to try the TBB,but I know little about TBB and the knowledge is so absent.I want to know the detail steps to complie and run the project. I would be very appreciative to you if you can give me some tips.

**Comment by lji72** [comment]
I use c++ and linux g++

**Comment by shenck0** [comment]
Hi, I'm using Visual Studio to compile in windows.
I think the section 'building sample project' of README.md can help you.
If you want to enable TBB in tiny_cnn, you should edit config.h and uncomment the line:
'''C++
//#define CNN_USE_TBB
'''
The other code will include TBB's header files and use them when the macro CNN_USE_TBB is defined, so you should :
1. Let your compiler know the TBB's include directory
2. Let your linker link to tbb.lib(in windows)/tbb.a(in linux, I guess)
3. Configure environment variable to make sure the program can find tbb.dll(in windows)/tbb.so(tbb's shared library)

**Comment by lji72** [comment]
Thanks! your answer is so detail.I have used the TBB successfully now.Thank you again for your work.

**Comment by zhangqianhui** [comment]
i success in useing tbb to compile the project.
And i use config tbb lib  and path in vs .
you can google 
how to config tbb in vs 2013 or vs 2012 and so on

**Comment by edgarriba** [comment]
@lji72 Tiny's last version should be able to find TBB in case that it's somewhere inside you system. Still having this issue?

**Comment by Randl** [comment]
@lji72 Do you still have thiss issue?

**Comment by pliptor** [comment]
@Randl lji72 last comment above indicates he was able to use TBB. I think this ticket can be closed.
