### ISSUE TITLE
Mat to image conversion

### ISSUE THREAD

**Issue by skazmi1** [tiny-dnn/tiny-dnn#512]
Hey guys. Does anyone know if tinydnn contains a tool to convert opencv mat to dnn image format?

**Comment by Randl** [comment]
If I get you right, you want to convert `Mat` to `std::vector`, which is used in tiny-dnn.
I believe, this may help: https://stackoverflow.com/questions/26681713/convert-mat-to-array-vector-in-opencv

**Comment by Randl** [comment]
No answer for a week, closing
