### ISSUE TITLE
invalid use of incomplete type std::ifstream

### ISSUE THREAD

**Issue by noonv** [tiny-dnn/tiny-dnn#519]
Try to build example under Qt 5.2.1 (mingw48_32)
and got errors:

> tiny-dnn-master\tiny_dnn\network.h:628: error: invalid use of incomplete type 'std::ifstream {aka class std::basic_ifstream<char>}' if (ifs.fail() || ifs.bad()) ^

> tiny-dnn-master\tiny_dnn\network.h:657: error: invalid use of incomplete type 'std::ofstream {aka class std::basic_ofstream<char>}'
>          if (ofs.fail() || ofs.bad())
>                 ^

and so on.

Add string 
`#include <fstream>`
to file **network.h** and it's solved the problem.

**Comment by Randl** [comment]
I suppose you to send this as PR

**Comment by bhack** [comment]
@edgarriba Can you close this?
