### ISSUE TITLE
why not consider using std:move/move constructor to enhance performance ？

### ISSUE THREAD

**Issue by liwangqian** [tiny-dnn/tiny-dnn#523]

**Comment by Randl** [comment]
Where exactly?

**Comment by liwangqian** [comment]
for example, the vector return from lossfunction and activation_function:
`
static vec_t df(const vec_t& y, const vec_t& t){
    vec_t d(t.size());
    ...;
    return d;
}
`
using

**Comment by nyanp** [comment]
@liwangqian 
In this case, we don't need to use ```std::move``` because compilers can use the technique called RVO.

http://stackoverflow.com/questions/17473753/c11-return-value-optimization-or-move

**Comment by beru** [comment]
But it still creates a temporary vec_t instance during the operation.
```cpp
static void df(vec_t& d, const vec_t& y, const vec_t& t){ d.resize(t.size()); ...; }
```
I prefer this style since it may reduce the amount of work of heap manager.
Just my two cents.

**Comment by Randl** [comment]
@liwangqian If you believe there are places you can introduce speedup, please send us PR with speed measurements

**Comment by Randl** [comment]
Closing, if there are places with confirmed speedup, please send a PR
