### ISSUE TITLE
Error C2327 exist in "tensor.h", not a type name, static or enumerator

### ISSUE THREAD

**Issue by yw155** [tiny-dnn/tiny-dnn#524]
Hi, 
I build a project and compile it in the windows with VS 2013. There is an error of the type C2327 in "tensor.h":
error C2327: “tiny_dnn::Tensor<U,kDimensions,kConst,Allocator>::array”: is not a type name, static or enumerator	...\tiny_dnn\core\framework\tensor.h   line 293.
void reshape(const std::array<size_t, kDimensions>& sz) {
        static_assert(!kConst, "Non-constant operation on constant Tensor");
        //No size change for reshape
        if (calcSize() != product(sz)) {
            throw nn_error("Reshape to Tensor of different size.");
        }
        shape_ = sz;
    }
Anyone knows how to solve this error?

**Comment by Randl** [comment]
VS2013 isn't supported anymore. Try VS2015 or minGW or Linux or older version of lib

**Comment by yw155** [comment]
I got that. Thank you!
