### ISSUE TITLE
Online learning

### ISSUE THREAD

**Issue by YuriOsokin** [tiny-dnn/tiny-dnn#533]
I'd like to use this library to learn the weights online.
I have a physical simulation, which provides me the input and output. I want to implement the controller with this library. But instead of standard to machine learning mini-batch approach I would like to update the weights of the NN each sample. Is it possible to do it now, and if yes, then how?
I did not find any NN.learn(x,y), vector x, vector y function in the library.

**Comment by kecsap** [comment]
Is not the online training means only to learn new samples for the model while it is in use?

I would just call the NN.train() with one-sample batch to be learned each time when a new feature vector comes in. Maybe I am missing something.

**Comment by YuriOsokin** [comment]
Yes, this is the essence of online learning.
So each simulation time step I call the NN.train() with mini batch. But will the NN object preserve the state(weights), or does it initialize itself each time train method is called?
Also, I am worried about the memory leakages. If the code was not developed for such a use case, I'd like to better understand how to use it better.
Thank you.

**Comment by kecsap** [comment]
I looked into the sources and also tried. You can call train() again without any problem, the weights are preserved and you can train the network with new samples.

In details:
init_weight() function initialized the weights and mark the initialized_ variable true. init_weight() is never called if initialized_ is true.

**Comment by bhack** [comment]
Can we close this?

**Comment by YuriOsokin** [comment]
Yes, thank you. I've been able to integrate your library very well.

**Comment by bhack** [comment]
Ok please open a PR if you think that we need to add something to the doc by you experience.
