### ISSUE TITLE
Transfer learning with convnets

### ISSUE THREAD

**Issue by smissan** [tiny-dnn/tiny-dnn#535]
Hi all,

is it possible to "freeze" certain layers in training, preventing the weights from changing? That would allow to first train the entire net (expensive), and later only modify just fully-connected layers, leaving convolution layers constant (as a constant feature extractor). Is there a good strategy to achieve this with tiny-dnn? thanks

**Comment by bhack** [comment]
See freeze layer section of https://github.com/tiny-dnn/tiny-dnn/blob/master/docs/how_tos/How-Tos.md

**Comment by smissan** [comment]
thanks!
