### ISSUE TITLE
Fresh developer

### ISSUE THREAD

**Issue by mani94454182** [tiny-dnn/tiny-dnn#544]
Hello
I'm a fresh developer and I want to contribute to this project up to level I can
Once I get comfortable in the work I ensure you that you wont be disappointed from me
I'm waiting for a chance to prove myself capable enough
hope to get a chance this time
Thanking you,

**Comment by Randl** [comment]
Hi @mani94454182 !

We are happy to welcome new developers. Check our gitter: https://gitter.im/tiny-dnn/developers
For the beginning you might want to choose some small issue and try to fix it to get familiar with the code base.

**Comment by Randl** [comment]
@mani94454182 
I suppose you join our gitter chat. If you have any particular questions you can ask them there. If you have some problem - feel free to open the issue or ask in the chat - whatever you believe is more appropriate and convenient for you.

Is it OK if I close the issue?

**Comment by mani94454182** [comment]
yeah thanks for the advise 
you can surely mark this as solved
