### ISSUE TITLE
Compare with Intel Caffe

### ISSUE THREAD

**Issue by fastalgo** [tiny-dnn/tiny-dnn#576]
Is there any result for comparing tiny-dnn with Intel optimized version Caffe on Xeon CPUs?

**Comment by Randl** [comment]
I believe there isn't, but I can do one at the moment we have https://arxiv.org/abs/1702.03044 fixed.

**Comment by Randl** [comment]
https://github.com/tiny-dnn/tiny-dnn/issues/75 related

**Comment by fastalgo** [comment]
Thanks!

**Comment by edgarriba** [comment]
I close this since question solved
