### ISSUE TITLE
Misused comma operator in serialization test

### ISSUE THREAD

**Issue by Randl** [tiny-dnn/tiny-dnn#578]
In https://github.com/tiny-dnn/tiny-dnn/blob/master/test/test_serialization.h#L408
```cpp
s1 << (f2, f3) << c4;
```
intends to connect both f2 and f3 to s1 and c4, but it actually connects only f3 (this is how comma operator works).

Solution proposed by @edgarriba is to use a dynamic array (probably initialization list would work nice here: `s1 << {f2, f3} << c4;`) instead.

**Comment by Abello966** [comment]
Is there no solution to this? I'm having the same problem with a multi-input graph network. When I use the concat/add layer it ends up connecting to only one, and then depending on the order I declare the inputs in the construct_graph it makes two different nets. 
Also, this seems to work differently in different contexts. With a smaller net it worked for some reason.
I tried the solution proposed in the OP but it didn't compile for me (error: expected ‘;’ before ‘}’ token). Also tried connecting separately in different lines, but it threw an exception on run-time

For clarity I'm attaching the gif's from the graph_visualizer of two cases:
1) success.gif - from the smaller net in which the concat layer actually worked

![success](https://cloud.githubusercontent.com/assets/4400081/23319985/9e8e22f2-fab7-11e6-8999-c75d0da232b5.gif)

Code for this network:
```  network<graph> nn;

  input_layer i1(shape3d(2,1,1));
  fully_connected_layer<activation::tan_h> fc1(2, 4);
  i1 << fc1;

  input_layer i2(shape3d(1,1,1));
  fully_connected_layer<activation::tan_h> fc2(1,4);
  i2 << fc2;

  concat_layer cc({shape3d(4,1,1), shape3d(4,1,1)});
  (fc1, fc2) << cc;

  fully_connected_layer<softmax> out(8,1);

  cc << out;

  construct_graph(nn, {&i2, &i1}, {&out});
```

2 an 3) separated1.gif and separated2.gif - from the big net where it didn't work
![separated1](https://cloud.githubusercontent.com/assets/4400081/23320253/b565ae2c-fab8-11e6-9fd6-1a9e143ebfa6.gif)

![separated2](https://cloud.githubusercontent.com/assets/4400081/23320268/c1ed6612-fab8-11e6-8dc1-ec90311e9192.gif)

Code for this (these?) network(s):
```
  const serial_size_t n_fmaps  = 8;  ///< number of feature maps for upper layer
  const serial_size_t n_fmaps2 = 16;  ///< number of feature maps for lower layer
  const serial_size_t n_fc     = 16;  ///< number of hidden units in fully-connected layer

  //Deep model
  input_layer i1(shape3d(32, 32, 3));
  convolutional_layer<activation::relu> cl1(32, 32, 5, 3, n_fmaps, padding::same);
  convolutional_layer<activation::relu> cl2(32, 32, 2, n_fmaps, n_fmaps, padding::valid, true, 2, 2);
  convolutional_layer<activation::relu> cl3(16, 16, 2, n_fmaps, n_fmaps, padding::valid, true, 2, 2);
  convolutional_layer<activation::relu> cl4(8, 8, 2, n_fmaps, n_fmaps2, padding::valid, true, 2, 2);
  fully_connected_layer<activation::identity> fc1(4 * 4 * n_fmaps2, n_fc);

  i1 << cl1 << cl2 << cl3 << cl4 << fc1;

  //Wide model 
  input_layer i2(shape3d(2, 1, 1));
  fully_connected_layer<tan_h> fc2(2, n_fc);

  i2 << fc2;

  //Combine
  concat_layer cc({shape3d{n_fc, 1, 1}, shape3d{n_fc, 1, 1}});
  (fc1, fc2) << cc;

  //Output
  fully_connected_layer<softmax> out(n_fc * 2, 10);
  cc << out;

  construct_graph(nn1, {&i1, &i2}, {&out}); //separated1
  construct_graph(nn2, {&i2, &i1}, {&out}); //separated2
```

**Comment by edgarriba** [comment]
You probably might need to dig in the code. Some hints where you could find the issue
https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/node.h#L172-193

This lines of code need a refactor to handle dynamic arrays. Alternatively, we discussed about having a Merge container. The first would will be more direct as a first step though.

**Comment by Abello966** [comment]
Found it! The difference was that in the first case both fully connected layers had the same activation, in the second, one had identity and other tan_h so the expression wasn't recognized as a tuple (node_tuple struct implies that nodes have same type). This seems to be the problem in the serialization test too :) 

I'm a begginer to C++ but I think it would be somewhat simple to extend the struct as to make it more type-agnostic. I'll work on that and let me know if you want me to make a PR later

**Comment by Abello966** [comment]
Ok so this is actually a little bit beyond my skills as a C++ programmer I think. 
Tried changing the functions definitions from 
```
template <typename T>
node_tuple<T *>
```
to
```
node_tuple<layer *> 
node_tuple<std::shared_ptr<layer>>
```
Respectively, but got some error about const in line 231. Whichever way I tried to change it it didnt work (e.g wouldnt compile, would not pass no duplicate symbols test, etc)

**Comment by Randl** [comment]
After @karandesai-96 finishes decoupling of activations, we will probably can concat `tanh` with `fully_connected` to achieve desired result.

**Comment by Abello966** [comment]
Great! I will leave it to the pros then

**Comment by karandesai-96** [comment]
I cannot reproduce this bug in `feat/decouple_activations` anymore. I think you guessed it correct @Abello966, about the types of members in node_tuple being different. @Randl was correct as well, since layers and activations are decoupled, I concatenate them successfully.

**Comment by karandesai-96** [comment]
@Abello966 please pull from latest upstream and test your code, it should work now :smile:

**Comment by Abello966** [comment]
@karandesai-96 will do! thanks a lot! Hope I could be of some assistance in this

**Comment by karandesai-96** [comment]
@Abello966 your code snippet and diagram served as a good reference!
