### ISSUE TITLE
Question: Does anyone have a cifar10 weight pre-computed for sharing?

### ISSUE THREAD

**Issue by pliptor** [tiny-dnn/tiny-dnn#588]
My computer seems way too slow to train it with the default setup.

Thank you!

**Comment by Randl** [comment]
I can run one for you. Do you want default parameters?

**Comment by pliptor** [comment]
@Randl Sweet. Yes, it would be useful for the newcomers if the run into the same problem. How long does it take to train in your box?

**Comment by Randl** [comment]
@pliptor I've put it right now with all defaults and `time`. One epoch takes ~140 secs, with TBB and AVX (note it's 4 socket server).

**Comment by pliptor** [comment]
That's roughly that it takes for me to train one MNIST epoch :( Thanks again.

**Comment by Randl** [comment]
Here are the weights: [cifar-weights.zip](https://github.com/tiny-dnn/tiny-dnn/files/786674/cifar-weights.zip). I'll send PR adding them and couple of other changes later today

**Comment by pliptor** [comment]
Thank you! Now I can fully test the test code too.
