### ISSUE TITLE
Is it possible to print the value of a "vec_t" vector?

### ISSUE THREAD

**Issue by Toby237** [tiny-dnn/tiny-dnn#597]
I am new to tiny-dnn and I am trying to convert images to "vec_t", however I don't know if I'm doing it right. I have therefore been trying to print my "vec_t" vector to see if it changes, but so far I haven't been able to find a way to do this.
Is there a way to print out a "vec_t" vector?

**Comment by Randl** [comment]
`vec-t` is just a typedef for a vector of floats. You can iterate over it as over regular vector and print it's members. For example:
```cpp
for(auto &x: vec) 
 std::cout << x << " ";
```

**Comment by Toby237** [comment]
Thanks for the reply. I figured out I had to treat it like a "vector inside a vector" kind of way, because I declared the vector like this "std::vector<vec_t> vec". So after combining this realization with the code you supplied, I ended up with this (which worked):
`for (auto &v : vec)
	{
		for (auto x : v) std::cout << x << " ";
		std::cout << endl;
	}`
