### ISSUE TITLE
Really disappointed, it highly depends on Microsoft c++, Cannot compile in Xcode.

### ISSUE THREAD

**Issue by WenboTien** [tiny-dnn/tiny-dnn#598]
When I drag this project in the Xcode, I get the error 'Use this header only with Microsoft Visual C++ compilers!'

**Comment by WenboTien** [comment]
I found a lot of file have this "#include<stdint>"

**Comment by Randl** [comment]
`stdint` isn't MSVC header. We are testing library under OS X and it passes all the tests. Please try building via CMake as described in readme.

**Comment by beru** [comment]
The error comes from `cereal/external/rapidjson/msinttypes/stdint.h` and `cereal/external/rapidjson/msinttypes/inttypes.h`.

They are meant to be used with MSVC compilers so use your senses when you setup your projects.

**Comment by WenboTien** [comment]
Ok, I'll try it soon
