### ISSUE TITLE
Question: Contrast Normalization

### ISSUE THREAD

**Issue by omimo** [tiny-dnn/tiny-dnn#599]
How can I apply contrast normalization? It is stated in the README but I can't find it in the code. 

Thanks!

**Comment by pliptor** [comment]
It might be this. I'm trying to get familiar with too.

https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/layers/lrn_layer.h

**Comment by omimo** [comment]
thanks @pliptor. 

I don't think they are the same thing (I might be wrong).

I was actually referring to Instance Normalization as explained in [Instance Normalization: The Missing Ingredient for Fast Stylization](https://arxiv.org/abs/1607.08022)

The authors say instance normalization is also known as contrast normalization. So I was hoping that it is already implemented there.

**Comment by bhack** [comment]
@omimo See thread https://github.com/yusuketomoto/chainer-fast-neuralstyle/issues/19

**Comment by omimo** [comment]
thanks @bhack. I'll try the batchsize=1 with the BN layer.

**Comment by pliptor** [comment]
@omimo I think you are right. That's an interesting paper.
