### ISSUE TITLE
Not supported engine: NNPACK

### ISSUE THREAD

**Issue by kristoffzoghbi** [tiny-dnn/tiny-dnn#602]
I'm trying to use NNPACK as a backend for faster training time. When I run the cifar10 example with `--backend_type nnpack` I'm getting the following error:

`terminate called after throwing an instance of 'tiny_dnn::nn_error'
  what():  Not supported engine: NNPACK`

Is NNPACK supported yet? If yes, how can I implement it as backend?

**Comment by edgarriba** [comment]
@kristoffzoghbi NNPACK doesn't support backward method

**Comment by kristoffzoghbi** [comment]
@edgarriba so NNPACK can't be used with `convolutional_layer`? Can you please give me an example of how or where I can use NNPACK as backend? 

Thank you!

**Comment by edgarriba** [comment]
@kristoffzoghbi yes you can, but just for inference

**Comment by bhack** [comment]
I think backward it is missing in fullconnected right? See upstream https://github.com/Maratyszcza/NNPACK/issues/1#issuecomment-279171247.

**Comment by bhack** [comment]
You can set engine x layer. So on training you cannot set NNPACK for fullconnected untill upstream will implement it. Please reopen if you find another kind of problem.

**Comment by kristoffzoghbi** [comment]
@bhack what do you mean by engine x layer?

**Comment by bhack** [comment]
That you can use set_backend_type at layer level and so switch on another engine for fully connected layers.

**Comment by kristoffzoghbi** [comment]
@bhack you mean like this?
    
```
	core::backend_t backend_type = parse_backend_name("nnpack");
	typedef convolutional_layer<activation::identity> conv;
	typedef max_pooling_layer<relu> pool;

	net << conv(1664, 64, 5, 4, 16, padding::same, true, 1, 1, backend_type)
	   << pool(1664 64, 16, 2, core::default_engine())
	   << conv(832, 32, 5, 16, 16, padding::same, true, 1, 1, backend_type)
	   << pool(832, 32, 16, 2, core::default_engine())
	   << conv(416,16, 5, 16, 32, padding::same, true, 1, 1, backend_type)
	   << pool(416, 16, 32, 2, core::default_engine())
	   << fully_connected_layer<activation::identity>(1664 * 32, 64, true, core::default_engine())
	   << fully_connected_layer<activation::identity>(64, 1, true, core::default_engine());
```

I'm only using **NNPACK** on _convolutional_layer_ and the **internal backend** on _max_pooling_layer_ and _fully_connected_layer_ but I'm still getting `terminate called after throwing an instance of 'tiny_dnn::nn_error'
  what():  Not supported engine: NNPACK`

Am I doing something wrong?

**Comment by bhack** [comment]
@edgarriba?

**Comment by edgarriba** [comment]
@kristoffzoghbi that's really weird. Wait are running your code for training?

**Comment by kristoffzoghbi** [comment]
@edgarriba yes I am using the code for training. I see your point now. 

So I'll use a network for training (convolutional layer with internal backend) and a slightly different one for evaluation (convolutional layer with NNPACK backend).

Sorry for wasting your time.

**Comment by edgarriba** [comment]
well yes and no wasting time

check https://github.com/Maratyszcza/NNPACK#layers

we have no backward routines implemented, but nnpack offers them. Maybe you could try PR with that implementation.

**Comment by bhack** [comment]
Yes a PR to enable NNPACK backward could be very appreciated.
