### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by AraHaan** [tiny-dnn/tiny-dnn#607]
I have an Repo on github that requires the filesystem TS in C++ 14. Sadly I have been trying for weeks to get g++ and clang++ to the absolute latest release version to no success. It did get to the point that I switched my focus to doozer to strugle with that as well for trying to get gcc and g++ 6.3 to install on that as well. I have been working on things like that since. If you are interested in helping me get one of those things working for things like appending the binaries to the release stuff then I would like that. travis and / or doozer is the thing preventing me from officially making the release. So yeah for me it is an release blocker.

https://github.com/AraHaan/bin2c

Also your gus's library looks promising as well.

**Comment by Randl** [comment]
I'm sorry, but this is generally not the right place to ask for these things
