### ISSUE TITLE
Question: Predicting on trained model.

### ISSUE THREAD

**Issue by Toby237** [tiny-dnn/tiny-dnn#610]
I am trying to use the "net.predict(...)" code in the "_How To_"-docs to predict output of my "test_images" vector. However I can not get it to work by passing my whole "**vector<vec_t>> test_images**" vector which contains all my test data, but if I pass only one row of the vector, like this: **net.predict(test_images[0])**, it works. 
So I was just wondering if the correct way to use "predict" is to use a **loop** that iterates through the **test_images** vector? 
I thought maybe "predict" automatically looped through the vector, and if that's true I certainty don't want to make a loop by myself which would be the wrong way to use this great library :)

**Comment by beru** [comment]
I suppose you're using `network::predict` methods. There are several overloaded methods and one of them takes `vector<vec_t>` (that is `tensor_t`) so it should work and when I look its implementation, `network::predict` methods simply call matching `network::fprop` methods.

I'm not sure how it doesn't work in your case. Can you post reproducible code?

**Comment by Toby237** [comment]
It looks like I got it to work now with a loop that iterates over every row of my **"test_images"** vector. 

But the code I used when I got an **error** was this:
I copied the "construct convolutional neural networks" **example** (https://github.com/tiny-dnn/tiny-dnn), but trained with my own _"train_images"_ and _"train_labels"_.

After I trained the network I tried to assign the "prediction" to a vector like this: `auto y_vector = net.predict(test_images);` ("test_images" is a vector<vec_t> vector). That line of code compiled, but threw an error when I ran it.
 I took a closer look at the error-message which said: **"Assertion failed: reordered_data.size() == 1".** Therefore I created a loop instead so I only pass 1 row at a time, and that seems to work.

**Comment by Randl** [comment]
@Toby237 So the issue can be

**Comment by m-toman** [comment]
I'm having the same issue. So I am also running in a loop, but that's more a workaround than a solution. Is the call with a tensor faster than sequential calls with vectors?
