### ISSUE TITLE
performance issue(vectorization)

### ISSUE THREAD

**Issue by LudwigBoltzmann** [tiny-dnn/tiny-dnn#614]
it seems that there is a bug about product function that in function
reduce_aligned at product.h, it is using loadu that loadu is for the unaligned function. it seems it has to be changed to load function. For my case it enhanced the performance a lot. 

Cheers,
Noh-hoon Lee

**Comment by beru** [comment]
@LudwigBoltzmann You are correct.

**Comment by bhack** [comment]
Fixed in https://github.com/tiny-dnn/tiny-dnn/pull/622. @beru Is this solving any other avx issue already opened?

**Comment by beru** [comment]
@bhack It's very unlikely as this issue is all about performance due to the use of unaligned load instructions even if source and dest addresses are aligned to register sizes.
