### ISSUE TITLE
Dropout

### ISSUE THREAD

**Issue by dicroce** [tiny-dnn/tiny-dnn#62]
Is dropout support fully implemented?

I notice that convolutional_layer<> takes an optional Filter template argument and then does nothing with it. Also, I am running into trouble using "fully_connected_dropout_layer" on the upper levels of my network. A convolutional_layer( 64, 64, 7, 3, 16 ) requires a fully_connected_dropout_layer with 53824 inputs and outputs... and I run out of memory. Am I using this wrong?

**Comment by nyanp** [comment]
@dicroce
I'm sorry to late reply! 
Previously dropout was supported only for fully-connected layer (and as you say, Filter template argument do nothing in conv-layer...).
Now tiny-cnn has new "dropout-layer" which is independent from fully-connected layer, so you can write like this:

```cpp
convolutional_layer c1(64, 64, 7, 3, 16);
dropout_layer drop(58*58*16, 0.5); // 58==64-7+1

nn << c1 << drop << ...
```

**Comment by edgarriba** [comment]
@dicroce Did you solve that?

Check this for Dropout usage:
https://github.com/nyanp/tiny-cnn/blob/master/test/test_network.h#L102-L110

**Comment by Randl** [comment]
@dicroce Can we close the issue?

**Comment by Randl** [comment]
No answer for a week, closing
