### ISSUE TITLE
Unbalanced data

### ISSUE THREAD

**Issue by hellbago** [tiny-dnn/tiny-dnn#623]
Suppose i have to solve an n-way classification problem and i have an unbalanced training set (let's say that some classes have twice the number of elements than the other ones). What happens in the training algorithm inside tiny-dnn? Can it manage such situation, for instance, by updating the weights of the net proportionally to the number of samples of different classes inside a minibatch? Or to avoid problems linked to unbalanced data the user must provide a balanced dataset in input? Thanks
@nyanp @edgarriba @Randl

**Comment by pliptor** [comment]
It seems the question you describe is not specific to a particular method or algorithm of machine learning. I'd suggest looking for insights from titles similar to this [paper](https://link.springer.com/chapter/10.1007/978-0-387-09823-4_45) on how to handle unbalanced training sets.

**Comment by bhack** [comment]
I'm closing this. it is really a general topic.

**Comment by nyanp** [comment]
@hellbago 
tiny-dnn provides "target cost" parameter for rebalancing training data. [this test case](https://github.com/tiny-dnn/tiny-dnn/blob/master/test/test_target_cost.h#L143) would help you.

**Comment by pliptor** [comment]
@nyanp That's a neat example. In technical terms, what you are saying is that "target cost" would help those that have enough bayesian (true a priory probability and conditional probabilities of the n classes) information make their due use during training.
