### ISSUE TITLE
Error: "identity" is ambigous

### ISSUE THREAD

**Issue by shimiaoli** [tiny-dnn/tiny-dnn#627]
Hi,

I have defined  network as : 
net << convolutional_layer< identity >(128, 128, 5, 1, 8, padding::valid) 
	        << max_pooling_layer< relu >(124, 124, 8, 4) 
			<< ...
			<< fully_connected_layer< identity >(1024, 30) 
			<< fully_connected_layer< identity >(30, 40); 

Then I have got syntax error in my IDE (VC2010) with both the CNN layer and the FC layers saying: Error: "identity" is ambiguous. 

Any idea on why this happens and how to fix it?

Thanks a lot !

Best Regards
Shimiao

**Comment by Randl** [comment]
Your compiler isn't supported, please use more recent VS or mingw

**Comment by nyanp** [comment]
Please use Visual Studio 2013 or later version.

> Any idea on why this happens and how to fix it?

Maybe it is caused by ambiguity between ```std::identity``` and ```tiny_dnn::activation::identity```. 

```cpp
using namespace std;
using namespace tiny_dnn::activation;

...
identity; // a compiler can't distinguish between std::identity and tiny_dnn::activation::identity
...
```

This error will occur on more recent VS, but removing using directive or replacing ```identity``` with fully qualified name would resolve the problem.

**Comment by shimiaoli** [comment]
This problem does not happen in VS2015. Thank you all.
