### ISSUE TITLE
Question on weight index in CNN layer

### ISSUE THREAD

**Issue by shimiaoli** [tiny-dnn/tiny-dnn#628]
Hi,

In tiny-dnn documentation 1.0.0a1
it is mentioned:
get weight vector
std::vector<vec_t*> weights = nn[i]->get_weights();
Number of elements differs by layer types and settings. For example, in fully-connected layer with bias term, weights[0] represents weight matrix and weights[1] represents bias vector.

I am wondering how are the number of elements in cnn layer case.

If the nn[i] layer is a cnn layer, with 8 convolutional filters , each filter has size 5 * 5 * 6:

Then does weights[0] represent the 1st cnn filter weight matrix, weight[1] represent the 2nd cnn filter weight matrix, ... and weight[8] represent the bias vector ?

Or the 5 * 5 * 6 * 8 tensor is all packed into weights[0], weights[1] contains only bias vector?

Many thanks.

**Comment by beru** [comment]
https://github.com/tiny-dnn/tiny-dnn/blob/6d764671f989e034030e5d88661ae49e4b4ce9ae/tiny_dnn/util/util.h#L155
Each implementation uses `index3d::get_index` method for indexing.

The size of weights is `depth` x `height` x `width` and when depth: 6 height:5 width:5,
indexes are
ch:0 y:0 x:0 idx:0
ch:0 y:0 x:1 idx:1
ch:0 y:1 x:0 idx:5
ch:0 y:1 x:1 idx:6
ch:1 y:0 x:0 idx:25
ch:1 y:0 x:1 idx:26
ch:1 y:1 x:0 idx:30
ch:1 y:1 x:1 idx:31
ch:5 y:4 x:4 idx:149
