### ISSUE TITLE
load_validation_data is redundant

### ISSUE THREAD

**Issue by tomjaguarpaw** [tiny-dnn/tiny-dnn#634]
`load_validation_data` doesn't actually do anything.

https://github.com/tiny-dnn/tiny-dnn/blob/master/examples/caffe_converter/caffe_converter.cpp#L82

and it seems like it's never done anything since it was created:

https://github.com/tiny-dnn/tiny-dnn/commit/dc517eeb52dd61f54e171f3ad7ac2a32b9fa0c03#diff-f7cc8b0f12f719aac419390b58e1217fR119

**Comment by Randl** [comment]
ping @nyanp

**Comment by nyanp** [comment]
Something went wrong from #154. validation.size() is always 1, so outer for-loop is meaningless... I will fix it. @tomjaguarpaw Thank you for your reporting :)
