### ISSUE TITLE
run tiny-cnn on my mac terminal

### ISSUE THREAD

**Issue by gary30404** [tiny-dnn/tiny-dnn#64]
can i run tiny-can on my mac terminal?
i have tried and i have installed C++ boost library. However, when i tried ''./waf build'', there is an error:

---

wlib-d-116:tiny-cnn-master gary$ ./waf build
Waf: Entering directory `/Users/gary/Desktop/tiny-cnn-master/build'
[2/2] Linking build/example/main
ld: library not found for -lboost_timer-mt
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Waf: Leaving directory `/Users/gary/Desktop/tiny-cnn-master/build'
Build failed
 -> task in 'main' failed (exit status 1): 
    {task 4340392080: cxxprogram main.cpp.1.o -> main}
## ['/usr/bin/clang++', 'example/main.cpp.1.o', '-o', '/Users/gary/Desktop/tiny-cnn-master/build/example/main', '-L../', '-lstdc++', '-lboost_timer-mt', '-ltbb']

Is this mean that i didn't successfully install boost?
how can i do??

**Comment by nyanp** [comment]
@gary30404 
Now example code of tiny-cnn doesn't require boost libraries, so please retry in latest version.

**Comment by edgarriba** [comment]
@gary30404 Notice that v.0.1.0 was released
https://github.com/nyanp/tiny-cnn/releases/tag/v0.1.0

Still having the issue?

**Comment by Randl** [comment]
@gary30404 Check the latest version if you're still interested
