### ISSUE TITLE
problem with semantic segmentation and deconvolution

### ISSUE THREAD

**Issue by vishnureghu007** [tiny-dnn/tiny-dnn#652]
I tried to run semantic segmentation using fcn alexnet in tinydnn using model - prototxt:
[https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/voc-fcn-alexnet/val.prototxt](url)
Modifications i made in tiny dnn is for padding(100) and a crop layer is implemented.
The deconvolution layer output from caffe and tiny-dnn for the same network is attached with this.The output from tinydnn is shifted and not the exact one what we should get from deconv layer.
Could you please help me to understand the reason for this.

![tiny](https://cloud.githubusercontent.com/assets/15410424/24942755/96cf11d8-1f70-11e7-8877-619aa736820a.png)
![output](https://cloud.githubusercontent.com/assets/15410424/24942763/a0a0aa28-1f70-11e7-865b-7262f95f1321.png)
![input](https://cloud.githubusercontent.com/assets/15410424/24942764/a29f313c-1f70-11e7-8c70-a6680864134e.png)

**Comment by Randl** [comment]
Deconvolutional layers have some problems, see https://github.com/tiny-dnn/tiny-dnn/issues/560
Hopefully, they'll be fixed soon. @karandesai-96 @wangyida 
BTW, we'll be glad to receive changes you made to our code as PR, if you can.

**Comment by vishnureghu007** [comment]
The problem was with padding 100 in the first convolution layer.(it throw an error " padding size not supported").
when i gave the input after padding (no padding in the convolution layer of prototxt ) the problem got solved.Now Iam able to get the same output like caffe.
Thanks

**Comment by Randl** [comment]
Yeah, arbitrary padding isn't supported yet
