### ISSUE TITLE
Using tiny_dnn with MFC (C++)?

### ISSUE THREAD

**Issue by Toby237** [tiny-dnn/tiny-dnn#659]
I am trying to make my first MFC and want to use tiny_dnn, but I'm having some trouble. When I try to include the "tiny_dnn.h" header file I get 106 syntax errors, the first one is saying: 

**Error C2146 syntax error: missing ';' before identifier 'rectified_linear'**	

I have tried a lot of different approaches, and for example if I include "tiny_dnn/util/util.h" it will compile.
Also when I try to use almost the exact same settings in a simple C++ project-file I can include "tiny_dnn.h" and everything works just fine. So I guess there is something going on under the hood of the MFC that is making a significant and important difference which prevents it from working.

Does anyone know what may be causing this problem, and how to fix it so I can include the "tiny_dnn.h" header file?

**Comment by beru** [comment]
Which version of Microsoft Visual Studio do you use?
Can you post reproducable code?

**Comment by Toby237** [comment]
Thanks for reply, the Microsoft Visual Studio version I use is 2015. 

I am not sure how to make good reproducible code because after I started the MFC project, Visual Studio automatically made a lot of files which depends on each other. However in the bottom of the "stdafx.h" file I put this code:
`#include "tiny_dnn\tiny_dnn.h"`
After I then try to compile I get 106 syntax errors. 

I tried to start a new MFC and not edit anything except setting the "include settings" to:
"C:\tiny-dnn\tiny-dnn-master"
And then in the bottom of "stdafx.h" I pasted: 
`#include "tiny_dnn\tiny_dnn.h"`
This gave me the same 106 errors. 
Also as mentioned earlier if I do the same steps in a plain and simple C++ project (no MFC) it compiles and runs. 
I could also mention that I have included other libraries which works just fine.

**Comment by beru** [comment]
Can you post those 106 errors you see on Visual Studio's Output window?
I don't have Windows environment right now so it's hard to reproduce the errors.

**Comment by Toby237** [comment]
I understand, here are all the errors:

Code	Description	Line
C2146	syntax error: missing ';' before identifier 'rectified_linear'	110
C2143	syntax error: missing ';' before '}'	100
C2143	syntax error: missing ';' before '}'	241
C2143	syntax error: missing ';' before '}'	80
C2143	syntax error: missing ';' before '{'	100
C2143	syntax error: missing ';' before '{'	11
C2143	syntax error: missing ';' before '{'	81
C2143	syntax error: missing ',' before '&'	89
C2143	syntax error: missing ',' before '&'	102
C2143	syntax error: missing ')' before ';'	100
C2143	syntax error: missing ')' before ';'	81
C2061	syntax error: identifier 'serial_size_t'	93
C2061	syntax error: identifier 'serial_size_t'	107
C2059	syntax error: '}'	241
C2059	syntax error: 'static_cast'	81
C2059	syntax error: '?'	80
C2059	syntax error: '>'	100
C2059	syntax error: '>'	81
C2059	syntax error: '::'	100
C2059	syntax error: '::'	81
C2059	syntax error: ':'	100
C2059	syntax error: ')'	100
C2059	syntax error: ')'	81
C4430	missing type specifier - int assumed. Note: C++ does not support default-int	100
C4430	missing type specifier - int assumed. Note: C++ does not support default-int	110
C4430	missing type specifier - int assumed. Note: C++ does not support default-int	89
C4430	missing type specifier - int assumed. Note: C++ does not support default-int	102
C2228	left of '.size' must have class/struct/union	94
C2228	left of '.size' must have class/struct/union	108
C2228	left of '.resize' must have class/struct/union	96
C2228	left of '.resize' must have class/struct/union	113
C2228	left of '.end' must have class/struct/union	97
C2228	left of '.end' must have class/struct/union	114
C2228	left of '.begin' must have class/struct/union	97
C2228	left of '.begin' must have class/struct/union	114
C2084	function 'void moments(const int)' already has a body	106
C1003	error count exceeds 100; stopping compilation	116
C2447	'{': missing function header (old-style formal list?)	11
C2780	'void std::fill(_FwdIt,_FwdIt,const _Ty &)': expects 3 arguments - 2 provided	97
C2780	'void std::fill(_FwdIt,_FwdIt,const _Ty &)': expects 3 arguments - 2 provided	114
C3861	'vector_div': identifier not found	99
C2065	'variance': undeclared identifier	113
C2065	'variance': undeclared identifier	114
C2065	'variance': undeclared identifier	116
C3668	'tiny_dnn::tan_hp1m2::scale': method with override specifier 'override' did not override any base class methods	235
C3668	'tiny_dnn::tan_hp1m2::f': method with override specifier 'override' did not override any base class methods	229
C3668	'tiny_dnn::tan_hp1m2::df': method with override specifier 'override' did not override any base class methods	234
C3668	'tiny_dnn::tan_h::scale': method with override specifier 'override' did not override any base class methods	209
C3668	'tiny_dnn::tan_h::f': method with override specifier 'override' did not override any base class methods	180
C3668	'tiny_dnn::tan_h::df': method with override specifier 'override' did not override any base class methods	199
C3668	'tiny_dnn::softmax::scale': method with override specifier 'override' did not override any base class methods	171
C3668	'tiny_dnn::softmax::one_hot': method with override specifier 'override' did not override any base class methods	169
C3668	'tiny_dnn::softmax::f': method with override specifier 'override' did not override any base class methods	142
C3668	'tiny_dnn::softmax::df': method with override specifier 'override' did not override any base class methods	161
C3668	'tiny_dnn::softmax::df': method with override specifier 'override' did not override any base class methods	159
C3668	'tiny_dnn::leaky_relu::scale': method with override specifier 'override' did not override any base class methods	121
C3668	'tiny_dnn::leaky_relu::f': method with override specifier 'override' did not override any base class methods	115
C3668	'tiny_dnn::leaky_relu::df': method with override specifier 'override' did not override any base class methods	118
C3668	'tiny_dnn::elu::scale': method with override specifier 'override' did not override any base class methods	135
C3668	'tiny_dnn::elu::f': method with override specifier 'override' did not override any base class methods	129
C3668	'tiny_dnn::elu::df': method with override specifier 'override' did not override any base class methods	132
C2672	'std::fill': no matching overloaded function found	97
C2672	'std::fill': no matching overloaded function found	114
C2065	'spatial_dim': undeclared identifier	94
C2065	'spatial_dim': undeclared identifier	98
C2065	'spatial_dim': undeclared identifier	99
C2065	'spatial_dim': undeclared identifier	108
C2065	'spatial_dim': undeclared identifier	111
C2065	'spatial_dim': undeclared identifier	115
C3861	'moments_impl_calc_mean': identifier not found	98
C2065	'mean': undeclared identifier	96
C2065	'mean': undeclared identifier	97
C2065	'mean': undeclared identifier	98
C2065	'mean': undeclared identifier	99
C2065	'mean': undeclared identifier	111
C2065	'mean': undeclared identifier	116
C2065	'in': undeclared identifier	94
C2065	'in': undeclared identifier	98
C2065	'in': undeclared identifier	108
C2065	'in': undeclared identifier	111
C2065	'in': undeclared identifier	115
C2065	'i': undeclared identifier	100
C2653	'function': is not a class or namespace name	114
C2653	'function': is not a class or namespace name	128
C2653	'function': is not a class or namespace name	178
C2653	'function': is not a class or namespace name	228
C2504	'function': base class undefined	112
C2504	'function': base class undefined	126
C2504	'function': base class undefined	140
C2504	'function': base class undefined	176
C2504	'function': base class undefined	226
C2873	'df': symbol cannot be used in a using-declaration	114
C2873	'df': symbol cannot be used in a using-declaration	128
C2873	'df': symbol cannot be used in a using-declaration	178
C2873	'df': symbol cannot be used in a using-declaration	228
C2653	'detail': is not a class or namespace name	98
C2653	'detail': is not a class or namespace name	115
C2065	'channels': undeclared identifier	94
C2065	'channels': undeclared identifier	96
C2065	'channels': undeclared identifier	98
C2065	'channels': undeclared identifier	108
C2065	'channels': undeclared identifier	111
C2065	'channels': undeclared identifier	113
C2065	'channels': undeclared identifier	115
C2589	'(': illegal token on right side of '::'	100
C2589	'(': illegal token on right side of '::'	81

**Comment by Toby237** [comment]
I think I got it to work! I had to put the  
`#include "tiny_dnn\tiny_dnn"`
 before
 `#include <afxwin.h>` 
in the "stdafx.h" file in the MFC.
