### ISSUE TITLE
How to convert opencv Mat(3 channels) to tiny-dnn vec_t??

### ISSUE THREAD

**Issue by chibai** [tiny-dnn/tiny-dnn#660]
In wiki, I can only found 1 channel Mat example 
here's how I process 3 channel Mat, but the answer is wrong.

tiny_dnn::vec_t patch2vect_t(cv::Mat patch)
{
	tiny_dnn::vec_t res;
	int Irow = patch.rows, Icol = patch.cols, i, j;
	if (patch.isContinuous() && patch.isContinuous())
	{
		Icol = Irow * Icol;
		Irow = 1;
	}
	const uchar* srcData;
	for ( i = 0; i < Irow; i++)
	{
		srcData = patch.ptr<uchar>(i);
		for ( j = 0; j < Icol; j++)
		{
			res.push_back(float_t(*srcData));
			srcData++;
			res.push_back(float_t(*srcData));
			srcData++;
			res.push_back(float_t(*srcData));
			srcData++;
		}
	}
	return res;
}

**Comment by beru** [comment]
@chibai Please place triple backticks ``` before and after the code block for readability.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by chibai** [comment]
``` c++
tiny_dnn::vec_t patch2vect_t(cv::Mat patch)
{
tiny_dnn::vec_t res;
int Irow = patch.rows, Icol = patch.cols, i, j;
if (patch.isContinuous() && patch.isContinuous())
{
Icol = Irow * Icol;
Irow = 1;
}
const uchar* srcData;
for ( i = 0; i < Irow; i++)
{
srcData = patch.ptr(i);
for ( j = 0; j < Icol; j++)
{
res.push_back(float_t(*srcData));
srcData++;
res.push_back(float_t(*srcData));
srcData++;
res.push_back(float_t(*srcData));
srcData++;
}
}
return res;
}
```

**Comment by pi-null-mezon** [comment]
@chibai you can find it here: https://github.com/pi-null-mezon/OpenIST/blob/master/CMDUtils/ClassNet/cnnclassnet.cpp#L236

**Comment by edgarriba** [comment]
@chibai check official opencv implementation for this use case
https://github.com/opencv/opencv_contrib/blob/master/modules/dnn_modern/src/caffe_converter.cpp#L172
