### ISSUE TITLE
Training after weights load drops network accuracy

### ISSUE THREAD

**Issue by pi-null-mezon** [tiny-dnn/tiny-dnn#663]
This question is respect to the latest release v1.0.0.a3. I have found strange behaviour when try to update network weights. I have created a network, then trained it (let's suppose after first training we have got 85.77 % accuracy) and saved it on the hard drive. Ok. Then I have load it, have checked the accuracy on the same data (also have got 85.77 %) and have decide to train another one epoch. Surprisingly after first epoch of the secon training accuracy of the network drops to 38.3 %. Why??? Maybe when I call train() method some weights reinitialization happens? How to prevent this behaviour?

**Comment by Randl** [comment]
Connected: https://github.com/tiny-dnn/tiny-dnn/issues/567

**Comment by pliptor** [comment]
I think it is interesting to consider this together #616. The issue on weight initialization there is different (weights get reset when new layers are added) but @nyanp explanation on how weights initialization are tracked and handled is a reference. @pi-null-mezon has a great SegNet tool written with tiny-dnn, hopefully this can be solved.

**Comment by pi-null-mezon** [comment]
@pliptor thanks for the reference. I have to mention in the beginning of the issue that I am using my own serialization code. Thanks to the reference I have found what goes wrong in my code. Now all works as expected to be.
