### ISSUE TITLE
The output of Caffe and Tiny-dnn with the same model are quite different....

### ISSUE THREAD

**Issue by zeyuan1987** [tiny-dnn/tiny-dnn#668]
I test the output probabilitys of a Caffe model and a tiny-dnn model which is transformed from Caffe. But I found the outputs are totally different...

**Comment by Randl** [comment]
Can you give now information?

**Comment by zeyuan1987** [comment]
I  used the following code to convert Caffe model to tiny-dnn model. @Randl 
 17 void convert(const string& model_file,
 18           const string& trained_file ) {
 19 
 20     // load model and weights
 21     auto net = create_net_from_caffe_prototxt(model_file);
 22     reload_weight_from_caffe_protobinary(trained_file, net.get());
 23 
 24     // save model, weights, architecture
 25     net->save("tiny-model");
 26     net->save("tiny-weights-json", content_type::weights, file_format::json);
 27     net->save("tiny-weights-binary", content_type::weights, file_format::binary);
 28     net->save("tiny-architecture", content_type::model, file_format::json);
 29 
}

**Comment by Randl** [comment]
Can you provide full reproducible example so I could try to run it on my PC?

**Comment by edgarriba** [comment]
@karandesai-96 you been playing with models right? could you also re-check this?

**Comment by zeyuan1987** [comment]
Thanks. I have that the recent version is right for the converting example. I used 1.0.3a to have the dismataching problem.

**Comment by Randl** [comment]
Can we close it?
