### ISSUE TITLE
Hi, when I  use cnn in video and meet  with "network dimension: 1024(conv:[[32x32x1],[5x5x6],[1x1x6]])"

### ISSUE THREAD

**Issue by mypython3** [tiny-dnn/tiny-dnn#686]
but I try to find out  one picture with digit in video ,I still face this problem.

**Comment by mypython3** [comment]
someone can help me?

**Comment by Randl** [comment]
Can you elaborate with code and detailed description of the problem

**Comment by mypython3** [comment]
It's done. Thank you
