### ISSUE TITLE
Fix random fails of appveyor tests 

### ISSUE THREAD

**Issue by Randl** [tiny-dnn/tiny-dnn#689]
For example
https://github.com/tiny-dnn/tiny-dnn/pull/679
https://github.com/tiny-dnn/tiny-dnn/pull/557

**Comment by Randl** [comment]
https://ci.appveyor.com/project/tinydnn/tiny-dnn/build/master-852/job/9ry4twox1e48nqvl
https://ci.appveyor.com/project/tinydnn/tiny-dnn/build/master-1028/job/l28f2eu4eabattx1
https://ci.appveyor.com/project/tinydnn/tiny-dnn/build/master-1032/job/r28nmme04bbga9rf

**Comment by beru** [comment]
I've confirmed this issue is reproducible with `tiny_dnn_test`.

**Comment by beru** [comment]
It seems random fails don't occur with `-DUSE_AVX=OFF` cmake setting.
So I suspect the problems lie within AVX conv fprop/bprop routines.

**Comment by Randl** [comment]
@beru one more https://github.com/tiny-dnn/tiny-dnn/pull/692#pullrequestreview-36668020

**Comment by beru** [comment]
The random unit test failures disappear with `#define CNN_SINGLE_THREAD` and tests run a lot faster.

**Comment by Randl** [comment]
Probably fixed in #694
