### ISSUE TITLE
make_mlp doesn't accept tanh as its activation function

### ISSUE THREAD

**Issue by darktrial** [tiny-dnn/tiny-dnn#704]
Compilation errors shows 
`simple.cpp:17:15: error: parse error in template argument list
  auto mynet = make_mlp<tanh>({ 32 * 32, 300, 10 });`

**Comment by MasterOfMemroy** [comment]
It's not a bug: The wiki might be wrong. Try using `tan_h` instead of `tan`.

**Comment by karandesai-96** [comment]
@MasterOfMemroy the wiki is slightly outdated. @darktrial are you putting `using namespace tiny_dnn::activation` in the file? Because mine works properly on latest master.

**Comment by darktrial** [comment]
sorry it is my mistake. It is working fine.  Putting a `using namespace std` will cause this error if you don't modify the code in wiki.

**Comment by karandesai-96** [comment]
Yes, there will be a conflict due to same names.

**Comment by karandesai-96** [comment]
Yes, there will be a conflict due to same names.
