### ISSUE TITLE
I meet a problem when i test the tiny-dnn with the main in file which named examples

### ISSUE THREAD

**Issue by zfs1993** [tiny-dnn/tiny-dnn#711]
i build a project with vs2013,and i replace the source file with the main in the examples file.Then i compile it,but there is a lot of errors.one of it is “tiny_dnn::tanh_layer::tanh_layer:there is no overload function to accept three parameters”,and there are many problems about tanh_layer.I just work on it for several days，and i didnt find the problems,

**Comment by weiyu322** [comment]
i got the same problem with vs2013,vs2015 is fine

**Comment by Randl** [comment]
VS2013 isn't supported anymore
