### ISSUE TITLE
error: tiny_dnn/tiny_dnn.h: No such file or directory

### ISSUE THREAD

**Issue by teodorToshkov** [tiny-dnn/tiny-dnn#728]
Hello,
I am trying to include tiny-dnn in a Qt application on Windows 10 64-bit.
I have included the tiny_dnn.h header like so:
`#include "tiny_dnn/tiny_dnn.h"`
and in the .pro file:
`INCLUDEPATH += absolute_path(D:\Teodor Toshkov\Documents\Neural Networks\tiny-dnn)`
but it throws an error:
`error: tiny_dnn/tiny_dnn.h: No such file or directory`
Where could the problem be?

I ran `cmake -G "Visual Studio 14 2015 Win64" -DBUILD_EXAMPLES=ON`
and I built from `tiny_dnn.sln` with `ALL_BUILD`

Thank you!

**Comment by pliptor** [comment]
I'm not sure if this helps you but I forked this full blown application that uses QT + tiny_dnn

https://github.com/pliptor/OpenIST

I compiled it in Linux but upstream has hooks for both Windows and Linux. Maybe referencing his files would help you.

**Comment by teodorToshkov** [comment]
Thank you very much!
The issue was in that I had whitespace in the path to where I downloaded tiny-dnn, I moved it to another location and now it runs!

Have an awesome day!

**Comment by pliptor** [comment]
Cool have fun.

**Comment by Randl** [comment]
resolved
