### ISSUE TITLE
tiny-dnn does not support this layer type:Concat

### ISSUE THREAD

**Issue by zchrissirhcz** [tiny-dnn/tiny-dnn#742]
Hi, I'm trying to use tiny with my caffemodel and prototxt files. The model can be run correctly under Caffe framework, but fails in converting. I wonder if anyone met similar error?

I modified `tiny-dnn/examples/caffe_converter/caffe_converter.cpp` to use my models.

The modified source code can be compiled correctly, and when running, it complains that `Concat` layer is not suported. I have checked that `tiny-dnn/tiny_dnn/io/caffe/caffe.proto` contains `concat` layer related configuration, and tiny-dnn's official readme also says concat layer is supported. Just don't know my executable outputs this:

```
before...
[INFO] convert Convolution => N8tiny_dnn19convolutional_layerE
[INFO] shape:49x49x64
[INFO] convert ReLU => N8tiny_dnn10relu_layerE
[INFO] shape:49x49x64
[INFO] convert Pooling => N8tiny_dnn17max_pooling_layerE
[INFO] shape:24x24x64
[INFO] convert Convolution => N8tiny_dnn19convolutional_layerE
[INFO] shape:24x24x16
[INFO] convert ReLU => N8tiny_dnn10relu_layerE
[INFO] shape:24x24x16
[INFO] convert Convolution => N8tiny_dnn19convolutional_layerE
[INFO] shape:24x24x64
[INFO] convert ReLU => N8tiny_dnn10relu_layerE
[INFO] shape:24x24x64
error: tiny-dnn does not support this layer type:Concat
test...
```

Is there anyone can help me? Thanks!

**Comment by edgarriba** [comment]
@zchrissirhcz 
check this https://github.com/tiny-dnn/tiny-dnn/blob/94419fe11e78f3338ea01bae874c30b58aa1d097/tiny_dnn/io/caffe/layer_factory_impl.h#L789

Which model are you trying to load? @karandesai-96 is working on that

**Comment by zchrissirhcz** [comment]
@edgarriba @karandesai-96 I'm using a face detection model, which is not publicly released. The problem is that Concat layer is actually not suported yet. I wonder when will Concat layer be supported? If not very soon, I also recommend modify readme's supported layers, thanks.

**Comment by bhack** [comment]
I think that it is not supported by the converter code. We have a concat layer https://github.com/tiny-dnn/tiny-dnn/blob/feat/generic-computational-graph/tiny_cnn/layers/concat_layer.h

**Comment by zchrissirhcz** [comment]
Sorry, I misunderstood the readme. The converter code do not support concat layer.

**Comment by edgarriba** [comment]
I think that the best approach to load a trained model in tiny-dnn is to define your architecture in cpp and import the parameters "by hand". The main problem is that each framework has it's internal representation when they serialize and having a generalized loader might be a bit difficult. @karandesai-96 is working on that.

**Comment by ChenZhaobin** [comment]
@zchrissirhcz  I met with the same problem, I use squeezenet  caffe model ,then got exception"tiny-dnn does not support this layer type:Concat "
