### ISSUE TITLE
Caffe_Converter isn't compatible with the latest master branch

### ISSUE THREAD

**Issue by blitzkriegbooes** [tiny-dnn/tiny-dnn#744]
Hi,

I pulled the master, and tried compiling the **caffe_converter** using **VS 2013 (vc12 solution)**. But, I found the that the example caffe_converter code given with the checkout is **incompatible with the header files of tiny_dnn** (specifically **alexnet.h, optimizer.h, convolutional_layer.h** etc etc) as in, I got these errors -

_Error	16	error C2661: 'tiny_dnn::relu_layer::relu_layer' : no overloaded function takes 3 arguments	D:\tinyDNN\tiny-dnn-master\tiny_dnn\models\alexnet.h	24	1	caffe_converter
Error	17	error C2661: 'tiny_dnn::relu_layer::relu_layer' : no overloaded function takes 3 arguments	D:\tinyDNN\tiny-dnn-master\tiny_dnn\models\alexnet.h	27	1	caffe_converter
Error	18	error C2661: 'tiny_dnn::relu_layer::relu_layer' : no overloaded function takes 3 arguments	D:\tinyDNN\tiny-dnn-master\tiny_dnn\models\alexnet.h	30	1	caffe_converter
Error	19	error C2661: 'tiny_dnn::relu_layer::relu_layer' : no overloaded function takes 3 arguments	D:\tinyDNN\tiny-dnn-master\tiny_dnn\models\alexnet.h	32	1	caffe_converter
Error	20	error C2661: 'tiny_dnn::relu_layer::relu_layer' : no overloaded function takes 3 arguments	D:\tinyDNN\tiny-dnn-master\tiny_dnn\models\alexnet.h	34	1	caffe_converter
Error	1	error C2610: 'tiny_dnn::optimizer::optimizer(tiny_dnn::optimizer &&)' : is not a special member function which can be defaulted	D:\tinyDNN\tiny-dnn-master\tiny_dnn\optimizers\optimizer.h	24	1	caffe_converter
Error	2	error C2610: 'tiny_dnn::optimizer &tiny_dnn::optimizer::operator =(tiny_dnn::optimizer &&)' : is not a special member function which can be defaulted	D:\tinyDNN\tiny-dnn-master\tiny_dnn\optimizers\optimizer.h	26	1	caffe_converter
Error	3	error C2610: 'tiny_dnn::layer::layer(tiny_dnn::layer &&)' : is not a special member function which can be defaulted	D:\tinyDNN\tiny-dnn-master\tiny_dnn\layers\layer.h	77	1	caffe_converter
Error	4	error C2610: 'tiny_dnn::layer &tiny_dnn::layer::operator =(tiny_dnn::layer &&)' : is not a special member function which can be defaulted	D:\tinyDNN\tiny-dnn-master\tiny_dnn\layers\layer.h	78	1	caffe_converter
Error	7	error C2610: 'tiny_dnn::dropout_layer::dropout_layer(tiny_dnn::dropout_layer &&)' : is not a special member function which can be defaulted	D:\tinyDNN\tiny-dnn-master\tiny_dnn\layers\dropout_layer.h	42	1	caffe_converter
Error	8	error C2610: 'tiny_dnn::dropout_layer &tiny_dnn::dropout_layer::operator =(tiny_dnn::dropout_layer &&)' : is not a special member function which can be defaulted	D:\tinyDNN\tiny-dnn-master\tiny_dnn\layers\dropout_layer.h	44	1	caffe_converter
Error	5	error C2264: 'tiny_dnn::layer::layer' : error in function definition or declaration; function not called	D:\tinyDNN\tiny-dnn-master\tiny_dnn\layers\convolutional_layer.h	239	1	caffe_converter
Error	6	error C2264: 'tiny_dnn::layer::layer' : error in function definition or declaration; function not called	D:\tinyDNN\tiny-dnn-master\tiny_dnn\layers\deconvolutional_layer.h	217	1	caffe_converter
Error	9	error C2264: 'tiny_dnn::layer::layer' : error in function definition or declaration; function not called	D:\tinyDNN\tiny-dnn-master\tiny_dnn\layers\fully_connected_layer.h	43	1	caffe_converter
Error	10	error C2264: 'tiny_dnn::layer::layer' : error in function definition or declaration; function not called	D:\tinyDNN\tiny-dnn-master\tiny_dnn\layers\max_pooling_layer.h	108	1	caffe_converter
Error	12	error C2264: 'tiny_dnn::layer::layer' : error in function definition or declaration; function not called	D:\tinyDNN\tiny-dnn-master\tiny_dnn\layers\quantized_convolutional_layer.h	219	1	caffe_converter
Error	13	error C2264: 'tiny_dnn::layer::layer' : error in function definition or declaration; function not called	D:\tinyDNN\tiny-dnn-master\tiny_dnn\layers\quantized_deconvolutional_layer.h	220	1	caffe_converter
Error	14	error C2264: 'tiny_dnn::layer::layer' : error in function definition or declaration; function not called	D:\tinyDNN\tiny-dnn-master\tiny_dnn\layers\global_average_pooling_layer.h	51	1	caffe_converter
Error	15	error C2264: 'tiny_dnn::layer::layer' : error in function definition or declaration; function not called	D:\tinyDNN\tiny-dnn-master\tiny_dnn\layers\quantized_fully_connected_layer.h	38	1	caffe_converter_

So, Does this mean the caffe-converter.cpp that gets checked out in the master branch is incompatible with the header files in the latest master version ? Then what Version of tiny-DNN should I use to compile the caffe-converter and run it successfully ?

Note: I used the tiny-dnn-1.0.0a3 version's header files, which were compatible with caffe_converter, but faced the same problem as faced by issue #429

**Comment by Randl** [comment]
VS 2013 isn't supported anymore, please use VS 2015+
