### ISSUE TITLE
width/height not multiple of pooling size

### ISSUE THREAD

**Issue by zchrissirhcz** [tiny-dnn/tiny-dnn#752]
Hi, I'm trying to construct a net, my code can build successfully but run with exception.

Here's my code
```c++
        layers::input input(shape3d(3, 100, 100));
        layers::conv conv1(100, 100, 3, 3, 64, padding::same);
        layers::ave_pool pool1(49, 49, 64, 3, 2);
        activation::relu relu1;
        input << conv1 << relu1 << pool1;
        
        layers::fc out(3, 2);
        
        activation::relu r;
        
        // connect
        input << conv1 << r;
        // register to graph
        network<graph> net;
        construct_graph(net, { &input}, {&out});
        
        net.save("graph-xxx");
```

The running output:
```bash
➜  Debug git:(master) ✗ ./caffe_converter
libc++abi.dylib: terminating with uncaught exception of type tiny_dnn::nn_error: width/height not multiple of pooling size
WxH:49x49
pooling-size:3x3

[1]    50868 abort      ./caffe_converter
```

How can I eliminate this error?

**Comment by edgarriba** [comment]
@zchrissirhcz please run it in debug mode and backtrace the error so that we can verify what's happening

**Comment by zchrissirhcz** [comment]
@edgarriba I follow your advice and run my C++ in CLion, now I see the concrete code line that throws exception:
![tinydnn1](https://user-images.githubusercontent.com/3831847/26859061-b8da4c20-4b67-11e7-921d-ef929b17a573.png)

Since 49%3!=0, it throws error:
```
throw nn_error("width/height not multiple of pooling size" + detail_info);
```

**Comment by zchrissirhcz** [comment]
@edgarriba Actually, I don't think it necessary to ensure that, in pooling layer, the width/height being multiple of pooling size. At lease in Caffe, it's OK be not multiple.

**Comment by edgarriba** [comment]
@zchrissirhcz that would be awesome! thx!

**Comment by ccnankai** [comment]
@zchrissirhcz  @edgarriba 
I am a novice.
I added a file, train.cpp, in the root directory, and added dd_executable(abc train.cpp) in cmakelists.txt. After compiling, how to run this train.cpp in clion.there is no run option in the right button.
