### ISSUE TITLE
A link to a built version of document points wrong URL.

### ISSUE THREAD

**Issue by whenimg0ne** [tiny-dnn/tiny-dnn#758]
Hello, docs/readme.md states   
> A built version of document is available at http://tiny-dnn.readthedocs.io/en/latest/index.html.  

but the hyperlink is pointing https://github.com/tiny-dnn/tiny-dnn/blob/master/docs/here.   
  
I've found that readme.md is not written properly.  
Following line in readme.md  
```
A built version of document is available at [http://tiny-dnn.readthedocs.io/en/latest/index.html](here).
```
should be like this.  
```
A built version of document is available at [here](http://tiny-dnn.readthedocs.io/en/latest/index.html).
```
  
It's really helpful that the link points right URL especially for newbies (including me).  I can post a PR if I should do so.    
  
Thanks.

**Comment by edgarriba** [comment]
@whenimg0ne sure! We'll appreciate that
