### ISSUE TITLE
mnist example run failure after installation

### ISSUE THREAD

**Issue by AvishekParajuli** [tiny-dnn/tiny-dnn#779]
Failure in running mnist example immediately after tinydnn installation. 
System configuration:ubuntu 16.04; intel core i5; 
system is upto date and no errors seen in tinydnn installation; example run fails

**Reproductions steps:**
follow the example to install tiny dnn and run sample example to confirm installation.
what am i missing? Error: failed to open "LeNet-Model"
```

cd ~/install_path # adjust `install_path` where you want to install tiny-dnn
git clone https://github.com/tiny-dnn/tiny-dnn.git  
cd tiny-dnn  
mkdir build & cd build   
cmake -DBUILD_EXAMPLES=ON .. & make  
cd examples   
./example_mnist_train 
./example_mnist_test img4.bmp
```
avishek@avishek-Aspire-TC-710:~/deep-learning/tiny-dnn/build/examples$ ./example_mnist_test img4.bmp
terminate called after throwing an instance of 'tiny_dnn::nn_error'
  what():  failed to open:LeNet-model
Aborted (core dumped)
![tinydnnfailure](https://user-images.githubusercontent.com/26102326/27519939-da74d4ea-59cc-11e7-99bf-b9d042f92160.jpg)

**Comment by edgarriba** [comment]
Your testing app doesn't load any trained model. The reason is because your training app didn't train any model. To train you need to specify `--data_path` and wait until the model converges.

**Comment by AvishekParajuli** [comment]
Thank you. That worked. However, during testing for img4, i get " 4, 109.582"
how can it be 109.582 % confidence? see the attached screenshot.
However there is one suggestions:
1) Make the message clear to the user. During Mnist training either specify Error or failure and then give usage. make usage as , ./example_mnist_train --data_path <insert data path> --learning_rat <rate>

![test4](https://user-images.githubusercontent.com/26102326/27524637-d55619fa-5a04-11e7-87dd-8b91a5b1955c.png)

**Comment by edgarriba** [comment]
That's due to the scale factor in activation which I really don't understand the purpose of its existence. @nyanp introduced it

**Comment by AvishekParajuli** [comment]
Would you like to fix the enhancements requests and the scaling?
OR i can fix them and you can code review it?
The tinydnn has a cleaner API and having good message will help the usets to get started easily.

Thanks
===============================================
Avishek Parajuli
________________________________

**Comment by Vivian4u** [comment]
<img width="1369" alt="2018-04-05 10 01 21" src="https://user-images.githubusercontent.com/20376808/38370642-2b7630e8-391d-11e8-8f0f-f2b1ba39f886.png">
My system is up to date and no errors seen in tiny-dnn installation，but example run fails.
Could you please help me to solve this problem？I am not clear about why I can not load model. @edgarriba @AvishekParajuli

**Comment by dendisuhubdy** [comment]
@Vivian4u that happened to mine too, any information?
