### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by gantoday** [tiny-dnn/tiny-dnn#783]
![image](https://user-images.githubusercontent.com/7780154/27618393-bfb40634-5bee-11e7-9561-9bb50e26eb7c.png)

how to fix it?

**Comment by edgarriba** [comment]
make sure that your compiler supports c++14

**Comment by gantoday** [comment]
@edgarriba not c++11?
![image](https://user-images.githubusercontent.com/7780154/27619370-68d6c88c-5bf4-11e7-90a5-5c6701a30a41.png)
I'm using g++ 4.4.7

**Comment by edgarriba** [comment]
it should support it
https://stackoverflow.com/questions/23523634/compiling-c11-on-g-4-4-7-in-red-hat-linux

what do you do for compiling? did you follow the instructions from the readme/wiki ?

**Comment by gantoday** [comment]
@edgarriba I make it follow the wiki:
![image](https://user-images.githubusercontent.com/7780154/27619641-96805954-5bf6-11e7-92b1-235c5888ef83.png)
I'm updating my gcc version now.

**Comment by edgarriba** [comment]
looks good, let me know. Just a comment, with cmake is also recommended to have a build directory. But anyways, it should work.

**Comment by gantoday** [comment]
gcc version 6.3.0 works well.
Thank you very much.
