### ISSUE TITLE
Headers are not compiling

### ISSUE THREAD

**Issue by john-alessi** [tiny-dnn/tiny-dnn#792]
Hello, I am having trouble compiling a test program using the tiny-dnn headers.  The test program contains the following:
`#include "tiny_dnn/tiny/dnn.h`

I tried compiling it with the following command:
`g++ test.cpp -I tiny-dnn -o test`

It produced the following output:
[log.txt](https://github.com/tiny-dnn/tiny-dnn/files/1129051/log.txt)

**Comment by edgarriba** [comment]
@john-alessi did you follow this?
http://tiny-dnn.readthedocs.io/en/latest/how_tos/Integrate-with-your-application.html#integrate-with-your-application

**Comment by john-alessi** [comment]
Yes, except I forgot to include the -O3 flag.  However that wasnt the issue.

**Comment by valmat** [comment]
Hi, John!
I looked your log. It looks like you forgot `-pthread` option.
For example my make file outputs following:
```
clang++ -I. -I"../incl/tiny-dnn" -O3 -pedantic -Wall -Wextra -Wno-unused-parameter -Wno-deprecated-declarations -std=c++14 -pthread -c -o o/run.o run.cpp
clang++ -std=c++14 -O3 -pedantic -Wall -Wextra -Wno-unused-parameter -pthread -o run.bin o/run.o
```

**Comment by john-alessi** [comment]
That was the problem, it works now.  Thanks for the help!
