### ISSUE TITLE
i want to know how to enable opencv?

### ISSUE THREAD

**Issue by zfs1993** [tiny-dnn/tiny-dnn#802]
it used to be in cmakelist.txt ,but i cannot find it now

**Comment by edgarriba** [comment]
we dropped support for opencv by default. However, you can include OpenCV in your cmake project in the standard way
http://docs.opencv.org/trunk/db/df5/tutorial_linux_gcc_cmake.html

the conversion between `cv::Mat <-> tiny_dnn::vec_t/tensor_t/Tensor` should be direct
http://docs.opencv.org/3.1.0/d3/d63/classcv_1_1Mat.html#a5fafc033e089143062fd31015b5d0f40
