### ISSUE TITLE
Missed namespace for NNPackInitializer object initialization

### ISSUE THREAD

**Issue by Kolkir** [tiny-dnn/tiny-dnn#828]
Now there are compilation errors like these ones, with defined USE_NNPACK:
`/home/kirill/progi/tiny-dnn/tiny_dnn/core/kernels/fully_connected_op_nnpack.h:24:3: error: ‘NNPackInitializer’ has not been declared
   NNPackInitializer::getInstance().initialize();
`
`/home/kirill/progi/tiny-dnn/tiny_dnn/core/kernels/maxpool_op_nnpack.h:21:3: error: ‘NNPackInitializer’ has not been declared
   NNPackInitializer::getInstance().initialize();
`
To resolve them `core::NNPackInitializer` should be used

**Comment by hoangt** [comment]
Replace line #24 of tiny_dnn/core/kernels/fully_connected_op_nnpack.h
**core::NNPackInitializer::getInstance().initialize();**

**Comment by edgarriba** [comment]
@Kolkir @hoangt could you send a PR with the fixes ?

**Comment by Kolkir** [comment]
Already fixed in the issue #887
