### ISSUE TITLE
Why  tiny_cnn renamed to tiny_rnn?

### ISSUE THREAD

**Issue by shede1988** [tiny-dnn/tiny-dnn#830]
Why  tiny_cnn renamed to tiny_rnn?

**Comment by prlz77** [comment]
I guess you mean tiny_dnn. I think it was a way to show that the library is open to do other than convolutions.

**Comment by nyanp** [comment]
> I think it was a way to show that the library is open to do other than convolutions.

Yes this is why we renamed it :)
