### ISSUE TITLE
Regression issues

### ISSUE THREAD

**Issue by costashatz** [tiny-dnn/tiny-dnn#843]
Hello,

First of all thanks for this great library!

I am trying to use it for some regression tasks, but I cannot get it working. I have created the simplest code that fails:

```cpp
#define CNN_USE_TBB
#define CNN_USE_AVX
#define CNN_USE_SSE
#define CNN_USE_AVX2
#define CNN_USE_DOUBLE
#include <tiny_dnn/tiny_dnn.h>

using namespace tiny_dnn;
using namespace tiny_dnn::layers;

int main() {
    network<sequential> net;
    adagrad opt;
    net << layers::fc(2, 3) << activation::tanh()
        << layers::fc(3, 1) << activation::softmax();

    for (int i = 0; i < net.depth(); i++) {
        std::cout << "#layer :" << i << "\n";
        std::cout << "#\ttype  :" << net[i]->layer_type() << "\n";
        std::cout << "#\tinput :" << net[i]->in_data_size() << "(" << net[i]->in_data_shape() << ")\n";
        std::cout << "#\toutput:" << net[i]->out_data_size() << "(" << net[i]->out_data_shape() << ")\n"
                  << std::endl;
    }

    // 2training data, each data type is 2-dimensional array
    std::vector<vec_t> input_data{{1, 0}, {0, 2}};
    std::vector<vec_t> desired_out{{2}, {1}};
    size_t batch_size = 2;
    size_t epochs = 30;

    net.fit<mse>(opt, input_data, desired_out, batch_size, epochs);
}
```

As soon as the `net.fit` function is called, I get an assertion fail:

```
tiny_dnn/layers/layer.h:241: void tiny_dnn::layer::set_in_data(const std::vector<const std::vector<double, tiny_dnn::aligned_allocator<double, 64ul> >*>*, std::size_t): Assertion `dst_data[j].size() == src_data[j]->size()' failed.
[1]    959 abort (core dumped)  ./build/exp/test_nn/test_nn
```

If I set the `batch_size` to 1, it works but the performance/accuracy is not good (not on this simple case, I tried in other functions -- which I could find proper parameters with other libraries). If the `batch_size` is something different to 1 then it does not work.

The output for the layer information is the following (seems legit to me):

```
#layer :0
#	type  :fully-connected
#	input :2([[2x1x1]])
#	output:3([[3x1x1]])

#layer :1
#	type  :tanh-activation
#	input :3([[3x1x1]])
#	output:3([[3x1x1]])

#layer :2
#	type  :fully-connected
#	input :3([[3x1x1]])
#	output:1([[1x1x1]])

#layer :3
#	type  :softmax-activation
#	input :1([[1x1x1]])
#	output:1([[1x1x1]])
```

I have pulled the latest master branch (i.e., commit: `8c5d999fb63396197df347274ab383f418ed2a58`) and I tried both with g++ 4.9.2 and clang 3.6. I also tried the examples for MNIST and CIFAR-10 (classification tasks and I didn't touch the code), and I get the same error message..

Do you have any idea what is wrong?

Many thanks,
Konstantinos

**Comment by DJuego** [comment]
Yes! I can confirm the same problem in Visual Studio 2017/Windows 10 x64. 

It is reproducible in the examples (i test the MNIST example).

The problem occurs in Debug mode. Not Release mode. And effectively; The problem is 'fixed' with batch_size to 1. 

DJuego

**Comment by mikedias** [comment]
Same here in Xcode 8.3.3 / macOS Sierra 10.12.5. I commented the assert line and move on.

**Comment by DJuego** [comment]
@mikedias The problem seems resolved recently.  Have you test the last master branch commit a9cacd3  
 (2017/08/15)? Indeed, there are a "fix assertion". In fact our "assertion". :-)

DJuego

**Comment by mikedias** [comment]
@DJuego that's great! I'll test again with the updated master. Thx!

**Comment by DJuego** [comment]
You are welcome, but all acknowledgment should go to for **nyanp**.  :-) Thank you **nyanp**.

DJuego

**Comment by mikedias** [comment]
I tested with the master and it works! This issue can be closed.

cc @costashatz @DJuego @nyanp
