### ISSUE TITLE
Syntax Error in NNPack kernel

### ISSUE THREAD

**Issue by noio** [tiny-dnn/tiny-dnn#886]
Closing parens in definition of `padding` at https://github.com/tiny-dnn/tiny-dnn/blob/master/tiny_dnn/core/kernels/conv2d_op_nnpack.h#L45 .

**Comment by bhack** [comment]
Can you submit a PR?

**Comment by noio** [comment]
https://github.com/tiny-dnn/tiny-dnn/pull/887
