### ISSUE TITLE
Applying clang-format shouldn't be compulsory with pull requests

### ISSUE THREAD

**Issue by beru** [tiny-dnn/tiny-dnn#911]
Right now, many pull requests are abandoned because a lot of submitters don't know or pay attention to the rule. To name a few,

#887 #878 #873 #722 

Actually, reviewers asked submitters to apply clang-format but they didn't do so and the pull requests are abandoned.

I asked one of the owners of this project @edgarriba to change the rule but he wasn't positive about it and didn't continue conversation in gitter's channel.

Is keeping consistent code format that important above any changes that can be brought by pull requests?

My idea is maintainers can apply clang-format time to time such as before making releases or once in a month and that's fine for me.

What's the advantage of keeping consistent code format at every commits in master branch? I don't think it is super beneficial...

**Comment by noio** [comment]
I can actually apply the formatting, just haven't gotten around to it.

**Comment by beru** [comment]
We don't have clang-format check anymore with [this commit](c5afeda82f4c09d395257761eb118aec11194b25). 

Further discussion at #984.
