### ISSUE TITLE
Why no conv2d_grad_op_nnpack.h ?

### ISSUE THREAD

**Issue by zeno40** [tiny-dnn/tiny-dnn#912]
Why is there no integration of NNPACK in the convolution backprop step?

thanks

**Comment by zeno40** [comment]
`/*
Copyright (c) 2013, Taiga Nomi and the respective contributors
All rights reserved.

Use of this source code is governed by a BSD-style license that can be found
in the LICENSE file.
*/
#pragma once

#include <vector>
#include "tiny_dnn/core/kernels/conv2d_op_internal.h"
#include "tiny_dnn/core/params/conv_params.h"

namespace tiny_dnn {
	namespace kernels {

		inline void conv2d_grad_op_nnpack(const tensor_t &prev_out,
			const vec_t &W,
			tensor_t &dW,
			tensor_t &db,
			tensor_t &curr_delta,
			tensor_t &prev_delta,
			const core::conv_params &params,
			const bool layer_parallelize) {
#ifdef CNN_USE_NNPACK
			// call singleton to initialize NNPACK
			core::NNPackInitializer::getInstance().initialize();

			const auto algorithm = core::nnp_algorithm();
			const auto kernel_transform_strategy = core::nnp_kts();

			const size_t batch_size = prev_out.size();
			const size_t input_channels = params.in.depth_;
			const size_t output_channels = params.out.depth_;

			// input data passed by convolution layer has been padded already
			// set input_size to padded size
			const nnp_size input_size = { params.in_padded.width_,
				params.in_padded.height_ };

			const nnp_size kernel_size = { params.weight.width_, params.weight.height_ };

			// input padded ,so no need to do padding
			const float_t dx{ 0.0 };  // params.in_padded.width_  - params.in.width_;
			const float_t dy{ 0.0 };  // params.in_padded.height_ - params.in.height_;

									  // we'll assume that padding is symmetric

			const nnp_padding pad = {
				dy / 2,  // top
				dx / 2,  // right
				dy / 2,  // bottom
				dx / 2   // left
			};

			const nnp_size stride = { params.w_stride, params.h_stride };

			const float *input_ptr = prev_out[0].data();
			const float *grad_output = curr_delta[0].data();
			const float *kernel_ptr = W.data();
			float *grad_input = prev_delta[0].data();
			float *grad_kernel = dW[0].data();

			// TODO(edgarriba): embed it into a class
			nnp_profile *profile = nullptr;

			nnp_status status = nnp_convolution_kernel_gradient(algorithm, batch_size, input_channels, output_channels, input_size, pad, kernel_size, input_ptr, grad_output, grad_kernel, profile);

			if (status != nnp_status_success) {
				throw nn_error("Could not succeed with nnp_convolution_kernel_gradient");
			}

			status = nnp_convolution_input_gradient(algorithm, batch_size, input_channels, output_channels, input_size, pad, kernel_size, grad_output, kernel_ptr, grad_input, profile);

			if (status != nnp_status_success) {
				throw nn_error("Could not succeed with nnp_convolution_input_gradient");
			}

#else
			conv2d_op_internal(prev_out, W, dW, db, curr_delta, prev_delta, params,
				layer_parallelize);
#endif
		}
	}  // namespace kernels
}  // namespace tiny_dnn`

**Comment by zeno40** [comment]
I posted a possible conv2d_grad_op_nnpack.h you could use in tiny-dnn. One should also modify conv2d_grad_op.h to make use of nnpack:

`/*
    Copyright (c) 2013, Taiga Nomi and the respective contributors
    All rights reserved.

    Use of this source code is governed by a BSD-style license that can be found
    in the LICENSE file.
*/
#pragma once

#include "tiny_dnn/core/framework/op_kernel.h"

#include "tiny_dnn/core/kernels/conv2d_grad_op_avx.h"
#include "tiny_dnn/core/kernels/conv2d_grad_op_nnpack.h"
#include "tiny_dnn/core/kernels/conv2d_op_internal.h"

namespace tiny_dnn {

class Conv2dGradOp : public core::OpKernel {
 public:
  explicit Conv2dGradOp(const core::OpKernelConstruction &context)
    : core::OpKernel(context) {}

  void compute(core::OpKernelContext &context) override {
    auto params = OpKernel::params_->conv();

    // incoming/outcoming data
    const tensor_t &prev_out = context.input(0);
    const tensor_t &W        = context.input(1);
    tensor_t &dW             = context.input_grad(1);
    tensor_t &db             = context.input_grad(2);
    tensor_t &prev_delta     = context.input_grad(0);
    tensor_t &curr_delta     = context.output_grad(0);

    // initalize outputs
    fill_tensor(prev_delta, float_t{0});

    // call convolution algorithm depending
    // on the selected engine type

    const core::backend_t engine = context.engine();

    if (engine == core::backend_t::internal) {
      kernels::conv2d_op_internal(prev_out, W[0], dW, db, curr_delta,
                                  prev_delta, params, context.parallelize());
    } else if (engine == core::backend_t::avx) {
      kernels::conv2d_grad_op_avx(prev_out, W[0], dW, db, curr_delta,
                                 prev_delta, params, context.parallelize());
	}
	else if (engine == core::backend_t::nnpack) {
		kernels::conv2d_grad_op_nnpack(prev_out, W[0], dW, db, curr_delta,
			prev_delta, params, context.parallelize());
	} else {
      throw nn_error("Not supported engine: " + to_string(engine));
    }
  }
};

}  // namespace tiny_dnn`

**Comment by zeno40** [comment]
I'm not completely sure the above is correct but it seems to function. I'm wondering the batch_size is correct.

**Comment by edgarriba** [comment]
@zeno40 the way the check it is preparing a unit test for that case.

**Comment by zeno40** [comment]
Yes, a unit test is required! I get some exception access violation. There still is something wrong I cannot pinpoint.

**Comment by zeno40** [comment]
tensor_t is not natively compatible with the NNPACK convolution functions who wants a single linear address space. So to use NNPACK one has to allocate and convert the tint_dnn tensor_t to one chunck of memory. And after calling the NNPACK function one has to convert back the memory to te corresponding tiny_dnn tensor_t allocation. This creates lots of overhead.
