### ISSUE TITLE
Gsoc 2018

### ISSUE THREAD

**Issue by bhack** [tiny-dnn/tiny-dnn#921]
After GSCOC 2017 initial support in tinydnn we want to disambiguate a little bit the overlap points between xtensor/xsimd and nnvm/tvm for GSOC 2018 proposals.

/cc @edgarriba @nyanp @Randl @beru @prlz77 

Any upstream feedback it is appreciated /cc @tqchen @SylvainCorlay @JohanMabille

**Comment by bhack** [comment]
Two main topics are:

- [ ] Graph rappresentation and optimizzation pass (NNVM)
- [ ] xtensor/xsimd ops (subset?) overlap with [TOPI](http://docs.tvmlang.org/doxygen/namespacetopi.html)

**Comment by tqchen** [comment]
[some recent result](http://www.tvmlang.org/2018/01/16/opt-mali-gpu.html) that might interests you for mobile gpu deployment

**Comment by bhack** [comment]
@tqchen So I suppose that we to produce an NVVM frontend for [our graph](https://github.com/tiny-dnn/tiny-dnn/blob/master/docs/how_tos/How-Tos.md#graph-model).
What are the differences between Onnx Graph IR and NVVM Graph IR?

**Comment by bhack** [comment]
Also If I understand correctly we could compile the graph only with the python interface (so not with c++) but then we could control the deployment/execution with c++. Is this right?

**Comment by bhack** [comment]
I.e. for reference http://nnvm.tvmlang.org/tutorials/from_onnx.html

**Comment by tqchen** [comment]
C++ interfacing is a WIP, but yes for now python interface is better supported. deployment can be done in any language(c++, python, javascript, java)

**Comment by bhack** [comment]
@tqchen Do you see any difference between ONNX, that has basically a models list "contract", and NNVM? 
So is ONNX really proof only on the [model list](https://github.com/onnx/models) that it has mandatory in the "standard"? And what is the case on NNVM?

**Comment by tqchen** [comment]
Again I don't think one computational graph spec would be that much different from one way or another, we need some common ground, ONNX is a good example of doing that. 

NNVM tries to think what other things can be done once we have the graph, be it onnx or tiny-dnn, can we transform them to optimize for different devices, can we precompute certain part of parameters like the pre-packing optimizations.

**Comment by bhack** [comment]
Ok thanks

**Comment by xiaoerlaigeid** [comment]
Hi! I am new here. I want to particpate gsoc this project. could you give me some advice on this ? Thanks a lot

**Comment by edgarriba** [comment]
@tqchen I still have some doubts about tvm, what's the real difference between tvm and halide ? It seems you rewrote the same thing. The final goal is to integrate somehow tinydnn into opencv or at least make opencv-dnn more complete. However, we already have the opencv-dnn module which already implements halide. What do you think that should be the point of having both backends ?  We evaluated the fact of including tvm into opencv but it's as large as opencv itself and which could add extra maintenance efforts. Timings are impressive thought.

**Comment by edgarriba** [comment]
@xiaoerlaigeid once the accepted organizations are announced we'll publish the final ideas list. Now we are still evaluating possible projects to work on. As said, the idea it's to merge tiny-dnn to opencv-dnn and it's not clear yet what benefits can provide tiny-dnn to opencv. So keep tuned.

**Comment by xiaoerlaigeid** [comment]
@edgarriba I am glad to hear that. If I want to contribute to the project where should I start?

**Comment by bhack** [comment]
@edgarriba https://github.com/dmlc/tvm/issues/682
