### ISSUE TITLE
32bit model binary load in 64bit platform

### ISSUE THREAD

**Issue by kakumanu-sudhir** [tiny-dnn/tiny-dnn#938]
Is it possible to load an 32bit weights binary into an 64bit platform?

I saved an 32bit model binary in an 32bit platform and tried to load it in an 64bit platform. How can I achieve it?

**Comment by beru** [comment]
I don't think it's impossible with current implementation since tiny-dnn uses the binary archive of cereal library. Using portable version of binary archive would achieve your objective.

https://uscilab.github.io/cereal/serialization_archives.html

**Comment by kakumanu-sudhir** [comment]
Hi, thanks for the pointer. 

But, it seems that the portable binary archive (portable_binary.hpp) only takes care of the endianness and not about the size types of machine.

following is the info comment for the class **PortableBinaryOutputArchive**

>  This archive will record the endianness of the data and assuming that
>       the user takes care of ensuring serialized types are the same size
>       across machines, is portable over different architectures.

and for the class **PortableBinaryInputArchive**

>  It is recommended to use portable archives only if you know that you will
>       be sending binary data to machines with different endianness.
> 
>       The archive will do nothing to ensure types are the same size - that is
>       the responsibility of the user.


As i earlier said, the weights binary is saved from a 32-bit platform and when i am loading this from an 64-bt platform, i am reading junk data and seeing crashes.

So i want to understand how to make this binary generic so that it can be saved in 32bit and loadable in 32bit/64bit cpu architectures.

**Comment by beru** [comment]
@kakumanu-sudhir I've checked the problem and posted a PR #940.

Unfortunately, compatibility with the archives saved with different versions of this library are not guaranteed so you would probably need to train again to make new archive file.

**Comment by beru** [comment]
Let me close this issue.
