### ISSUE TITLE
Apparent syntax error in xiterable.hpp:740

### ISSUE THREAD

**Issue by AnthonyWinder** [tiny-dnn/tiny-dnn#958]
An apparent syntax error is encountered when compiling the examples according to the steps in:
_https://github.com/tiny-dnn/tiny-dnn/wiki/A-beginner's-guide-to-build-examples_

The exact commands required to produce the error are as follows: 
`git clone https://github.com/tiny-dnn/tiny-dnn.git`
`cd tiny-dnn`
`mkdir build`
`cd build`
`cmake -DBUILD_EXAMPLES=ON ..`
`make`

The error itself produces the following console output:
`tiny-dnn/tiny_dnn/xtensor/xiterable.hpp:740:19: error: expected primary-expression before ‘)’ token
   return begin<L>();`

I have attached a [file containing the full stack trace](https://github.com/tiny-dnn/tiny-dnn/files/2032803/errlog_xiterable.txt) if this is useful. In attempting to solve it, I have done the following:

- Verified that I have the newest version of CMake. I am using 3.11.1.
- Verified that my compiler supports the C++14 standard. I am using GCC 8.1.0.
- Verified that I had the newest release of tiny-dnn (commit 1c52594 on Mar 11 2018)
- Viewed the code in qtCreator. The IDE expected `begin<L>(&shape)` over `begin<L>()`

**Comment by AnthonyWinder** [comment]
I just discovered that this issue does not arise if the examples are compiled with docker using the tiny-dnn/dev-env.sh script. Perhaps the wiki could be updated to suggest using this script.

**Comment by sinkingsugar** [comment]
This issue exists, and it's related to probably gcc 8+, not really a tiny-dnn bug but would be nice to have it worked around.

**Comment by ghost** [comment]
In the event that any person having the same problem cannot feasibly use the Docker virtual environment, they can use an older version of gcc as sinkingsugar suggested via the following commands: 
`export CC=/usr/bin/gcc-6`
`export CXX=/usr/bin/g++-6`
`cd /path/to/build/folder`
`cmake .. && make`

Note that the path to your gcc-6/g++-6 may be different than mine, or may not yet be installed.
